VOICEVOX/voicevox_core

README.md, example/python/requirements.txt
=> C#のサンプルコードを追加

README.md
#44 の問題を一度main上で試して失敗する前に気付けるように、READMEでお知らせする
ref #44
=> #44の内容をREADMEに表示する

.github/workflows/build.yml
onnxruntimeのビルドがなぜか通りません。
良い機会なので別リポジトリに移動してみたいと思います。
ref #54
=> armhfビルドを別リポジトリに移動

core/src/core.cpp
音声が途切れることに対するworkaround
refs #17
=> C++側に無音区間workaroundのための処理を実装した

README.md, example/python/requirements.txt
現状のサンプル実行手順を「コアライブラリのビルド」に移し、代わりに製品版(releases)を利用する方法に変更しました。
close #66 
手でコピーする作業がいくつかあるが自動化すべきか？
=> READMEのサンプルを、製品版のものを実行する用途のコードに変更する

.github/workflows/build.yml
arm64 向けの自動ビルドを追加します。
64bitのRaspberry Pi OSで正常に動作することを確認しています。
close #67
=> arm64 向けの自動ビルドを追加

.gitignore, README.md, configure.py, requirements.txt
```
$ python configure.py
$ pip install -r requirements.txt
$ pip install .
```
で動きます。1行目では、onnxruntime, voicevoxのリリースを自動的に取得し、適切なディレクトリに配置します。
sample output
```
$ python configure.py 
Downloading onnxruntime from https://github.com/microsoft/onnxruntime/releases/download/v1.9.0/onnxruntime-linux-x64-1.9.0.tgz...
Downloading voicevox from https://github.com/VOICEVOX/voicevox_core/releases/download/0.10.0/core.zip...
Please enter number to select which library to use.
0: /Users/xuzijian/voicevox_core/release/libcore_cpu_armhf.so
1: /Users/xuzijian/voicevox_core/release/libcore_cpu_x64.so
2: /Users/xuzijian/voicevox_core/release/libcore_gpu_x64_nvidia.so
Your choice: 1
Successfully configured!
```
rel: #76 #77
=> 環境構築のスクリプトを追加

.github/workflows/build.yml
=> Github Actionsでpipをキャッシュするように

CMakeLists.txt, core/src/core.h, core/src/engine/synthesis_engine.cpp
=> Ubuntu環境上でのビルドエラーを修正

.github/workflows/build.yml
題の通りです。
マージしてから、ビルドが回らないことに気づくと言ったことを防ぎたく、本PRを作成しました。
後に、関数テストとかもこの中で回せると良いのかなと思いました。
=> ビルドテストをプルリクエスト時にも行うようにする

.github/workflows/build.yml
- https://github.com/VOICEVOX/voicevox_core/issues/130
の関連プルリクエストです。
とりあえずダミーとして、リポジトリのREADMEをコピーするようにしてみました。
=> ビルド時にREADMEファイルを追加する

core/src/core.cpp
- https://github.com/VOICEVOX/voicevox_core/issues/143
の解決プルリクエストです。
yukarin_sとyukarin_saはCPUで推論するということにしようと思います。
GPUでのエラーの迂回も兼ねていますが、おそらくCPUの方がGPU待機が入らないため速いのが主要因です。
close #143
=> hotfix イントネーションの推論をCPUで行うように

.github/workflows/test.yml, Cargo.lock, crates/voicevox_core/Cargo.toml, crates/voicevox_core/src/c_export.rs, crates/voicevox_core/src/error.rs, crates/voicevox_core/src/internal.rs, crates/voicevox_core/src/status.rs
Status.load_metasとそれに関連する dllで exportする用のC API関数であるmetas関数の実装を行った
refs #128
initialize関数内部でstatus.load_metasを呼び出すようにした
#139 が mergeされてからレビューすること
=> [Rust]load_metas,metasを実装した

Cargo.lock, crates/voicevox_core/Cargo.toml, crates/voicevox_core/src/status.rs
load_modelのテストを実装してみたが、Invalid dimensionsが発生する。
なんかやり方が悪いのかも？
間違ってる点があれば教えていただきたいです
refs #128
=> [Rust]load_modelの際にInvalid dimensionsが発生する

crates/voicevox_core/src/c_export.rs, crates/voicevox_core/src/error.rs, crates/voicevox_core/src/internal.rs
statusの方にのみ実装されていたのでinternal.rsに実装した
#128
=> [Rust]internal.rsに load_modelを実装した

crates/voicevox_core/src/c_export.rs, crates/voicevox_core/src/error.rs, crates/voicevox_core/src/internal.rs, crates/voicevox_core/src/status.rs
ErrorがPartialEqで比較できるようにした
assert_eq!で比較できるところは比較するようにした
refs #128
=> ErrorがPartialEqで比較できるようにした

.github/workflows/audit.yml
[cargo-audit](https://crates.io/crates/cargo-audit) をCI上で実行することにより脆弱性のあるライブラリを使っていないか確認できるようにする
refs #128
=> [Rust]cargo auditを追加

crates/voicevox_core/src/internal.rs
=> [Rust]internalのfinalizeを実装した

Cargo.lock, crates/voicevox_core/Cargo.toml, crates/voicevox_core/src/engine/mod.rs, crates/voicevox_core/src/engine/open_jtalk.rs
voicevox_coreで使うOpenJtalk部分を実装した
refs #128
=> OpenJtalkを実装した

crates/voicevox_core/src/include_models.rs, crates/voicevox_core/src/include_speaker_id_map.rs, crates/voicevox_core/src/internal.rs, crates/voicevox_core/src/status.rs
実際のmodel差し替えがどのように行われてるかわかってないのですが、こんな感じだとやりやすそうかなと思ってやってみました
refs #128
=> [Rust]リリース版バイナリを作成するときのmodel差し替えを行いやすいようにした

Cargo.lock, crates/voicevox_core/Cargo.toml
=> [Rust]onnxruntimeがGPUのbuildで通らなくなってたためその修正のupdate反映をする

.github/workflows/build_and_deploy.yml, Cargo.lock, crates/voicevox_core/Cargo.toml
T/O
refs #128
deployは未実装
workflow_runでtest workflowが実行されてから実行される設定にしてるが、この設定はworkflow_runが設定されてるworkflowがdefault branchにマージしないと動作しないらしく現段階だとどうさせることができないそうです
=> [Rust]release用のbuildとdeployのCI設定を作った

crates/voicevox_core/src/c_export.rs, crates/voicevox_core/src/engine/full_context_label.rs, crates/voicevox_core/src/engine/synthesis_engine.rs, crates/voicevox_core/src/internal.rs
`adjust_interrogative_accent_phrases` 関数を追加し、疑問文に対応しました。
ref #128
=> [Rust] 疑問文対応

Cargo.lock, crates/voicevox_core/Cargo.toml
=> dependenciesをVOICEVOX hostしてるものに変更した

.github/workflows/build_and_deploy.yml
=> release経路を足す

.github/workflows/build_and_deploy.yml
=> [Rust]拡張子変更し忘れてたので修正

README.md
時間がたったあとに実行するとfindできないので、消しても良さそう？
#128
=> [Rust] READMEでctime 0をなくす

README.md
=> READMEにビルド時にcmakeが必要な旨を追記

.github/workflows/test.yml
一部テストが失敗してるのに表示上は成功になっているのを修正
https://github.com/VOICEVOX/voicevox_core/runs/7716458374?check_suite_focus=true
CLI環境がよくなかったようなのでbashを使うようにした
=> CIテストでWindowsのテストが表示上成功してるが実は失敗しているのを修正した

.github/workflows/build_and_deploy.yml
linuxのGPU buildでprovidersが含まれないことがわかったのでshared libraryを全て含めるように変更した
refs #213 https://github.com/VOICEVOX/voicevox_core/issues/213#issuecomment-1211418599
=> onnxruntimeの全てのshared libraryをartifactに含めるようにした

crates/voicevox_core/src/engine/open_jtalk.rs
extract_fullcontext時にrefleshしわすれていたのが原因だったのでrefleshするようにした
https://github.com/VOICEVOX/voicevox_core/issues/213#issuecomment-1214026896
=> 回数を重ねるとtts結果が変わってしまうバグを修正した

crates/voicevox_core/Cargo.toml
必要であるけどCargo.tomlでは有効化されておらず`dev-dependencies`によりたまたま有効化されている、feature `serde/derive`を明示的に有効化します。
Closes #240.
=> `serde/derive`を有効化する

example/python/run.py
Pythonのサンプルを高速化しました。
load_all_modelsをFalseにし、必要な話者のモデルだけload_modelすることによって高速化しています。
（なし）
（なし）
=> Improve: exampleを高速化

.github/workflows/build_and_deploy.yml
conflict修正失敗したかなと思ったんですが結構前から失敗していたようです
=> release buildが失敗するようになっていたのを修正した

Cargo.lock, crates/voicevox_core/Cargo.toml
version指定だと参照先のrepoのmainブランチのバージョンが更新されると古いバージョンを参照していたそれまでのものはビルドが通らなくなってしまうため
close #248
=> voicevoxで管理しているライブラリの参照はrevにした

.github/workflows/build_and_deploy.yml
- https://github.com/VOICEVOX/voicevox_core/issues/267
を解決します。
close #267
=> code_signingがtrueじゃないとき「false」environmentを使おうとしてしまう問題を解決

README.md
現状のmainはまだ一部動かないことがあったり、破壊的変更が加えられてもexamleが追従できてなかったりし、しばらく工事中だと思われます。
比較的安定している`0.13.0`の案内をREADMEに書くことで、ユーザーが迷子になることを防ぐPRです。
=> 0.13.0への案内を書く

crates/voicevox_core_c_api/build.rs, crates/voicevox_core_c_api/cbindgen.toml
現在voicevox\_core\_c\_apiのbuild.rsに書かれているcbindgen.tomlの設定を、cbindgen.tomlに移行します。
ref #282
=> cbindgenの設定をcbindgen.tomlに移行

README.md
Deps.rsのバッジを追加します。
Closes #289.
=> Add Deps.rs badge

crates/voicevox_core_c_api/src/helpers.rs, crates/voicevox_core_c_api/src/lib.rs
no_mangleついてないことによりc API化されていなかったAPIを出るようにした
convert_result以外でresult codeをreturnしているところを標準エラー、debugに出力されるようにした
=> いくつかのC APIに関するバグを修正

.github/workflows/audit.yml, .github/workflows/build_and_deploy.yml, .github/workflows/download_test.yml, .github/workflows/test.yml, .github/workflows/update_rust_toolchain.yml
アップデートできるactionをアップデートします。
VOICEVOX/voicevox#987
- [actions/checkoutのchangelog](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- [actions/setup-pythonのリリース](https://github.com/actions/setup-python/releases)
- [actions-setup-cmakeのリリース](https://github.com/jwlawson/actions-setup-cmake/releases)
- [rust-cacheのchangelog](https://github.com/Swatinem/rust-cache/blob/master/CHANGELOG.md)
=> actionをアップデートする

crates/voicevox_core_c_api/src/lib.rs, crates/voicevox_core_python_api/python/voicevox_core/_models.py, crates/voicevox_core_python_api/python/voicevox_core/_rust.pyi
エディタ上で表示するため、PythonAPIのdocstringだけ書いてしまいます。
#294
=> Python APIのドキュメントを書く

crates/voicevox_core_python_api/python/voicevox_core/_models.py, crates/voicevox_core_python_api/python/voicevox_core/_rust.pyi, crates/voicevox_core_python_api/src/lib.rs
`sed -i 's/_list/_vector/g' ./crates/voicevox_core_python_api/**/{*.pyi,*.rs}`しました。
Fixes #317.
#316 に続くPRです。
=> Python APIのパラメータ名を修正

.github/workflows/build_and_deploy.yml, Cargo.toml, crates/voicevox_core/Cargo.toml, crates/voicevox_core_c_api/Cargo.toml, crates/voicevox_core_python_api/Cargo.toml, crates/xtask/Cargo.toml
#287 には`初心者歓迎タスク`を付けてましたが、メリットがそこそこあるため今やってしまいます。
Resolves #287.
=> workspace inheritanceを利用する

.github/workflows/build_and_deploy.yml, .github/workflows/download_test.yml, .github/workflows/test.yml, .github/workflows/update_rust_toolchain.yml, build_util/codesign.bash, scripts/downloads/download.sh
[ShellCheck](https://www.shellcheck.net/)と[actionlint](https://github.com/rhysd/actionlint)を導入します。
ref #310
=> ShellCheckとactionlintを導入

.github/workflows/psscriptanalyzer.yml
[PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer)を`main`ブランチ上で動かし、結果がcode scanningに出るようにします。
https://github.com/VOICEVOX/voicevox_core/issues/343#issuecomment-1345516267 のような出かたになると思われます。
Resolves #343.
=> PSScriptAnalyzerを導入する

Cargo.lock, crates/voicevox_core/Cargo.toml
onnxruntime-rsを更新します。
- #347
- https://github.com/VOICEVOX/onnxruntime-rs/pull/14
=> onnxruntime-rsを更新

scripts/downloads/download.sh
wsl環境でWindows向けのバイナリをダウンロードできるようにするため
=> bash版ダウンローダーでダウンロードするosの指定をできるようにした

deny.toml
=> deny.tomlを更新

.github/workflows/build_and_deploy.yml
#371 の解決です。実際に動くのかはまだ試せていません。
clse #371 
ChatGPT君がこれが正しいと言っていました！
=> windowsのzipコマンド代わりをCompress-Archiveではなく7zコマンドを使う

example/python/run.py
=> 出力先オプションの追加

scripts/downloads/download.sh
=> Fix: Typo修正

.github/labeler.yml
- https://github.com/VOICEVOX/voicevox_core/pull/387
の修正漏れです！
=> labeler.yml忘れ

README.md, example/pyo3/README.md
0.13工事中の表記を消します。
そういえばダウンローダーがちゃんと動くかチェックできそう？
あとwheel版pythonもexampleあるととても便利そう。
=> 0.13工事中の表記を消す

.github/workflows/download_test.yml
Fixes #409.
そういえばmacOS用のテスト無いのでは...?
=> download_testを0.14.0に対応させる

.github/workflows/build_and_deploy.yml
=> download-windows-x64.exeをコード署名する

.github/workflows/download_test.yml
download\_testの`on.pull_request.push`に #375 で追加したRust版ダウンローダーを入れます。
=> download_testのトリガーを更新

.github/workflows/test.yml, example/cpp/windows/README.md, example/cpp/windows/simple_tts/simple_tts.cpp, example/cpp/windows/simple_tts/simple_tts.h, example/cpp/windows/simple_tts/simple_tts.vcxproj
Windows用サンプルがビルドできなかったので、ビルドできるように修正します。
=> Windows c++サンプル修正

README.md
ScalaによるFFIラッパを作成したため、事例紹介に追加させていただきました。
=> voicevoxcore4s(Scala FFI Wrapper)を事例紹介に追加

crates/voicevox_core_c_api/src/lib.rs, crates/voicevox_core_python_api/python/voicevox_core/_rust.pyi
テキストの文字コードはUTF8だと案内します。
ツイッターで迷っている方を見かけたので https://twitter.com/zero_kawa_denko/status/1634964340523806720
=> テキストの文字コードはUTF8だと案内

crates/voicevox_core/src/lib.rs, crates/voicevox_core/src/publish.rs, crates/voicevox_core/src/result_code.rs, crates/voicevox_core_c_api/src/helpers.rs, crates/voicevox_core_c_api/src/lib.rs
以下のAPIを追加します：
- voicevox_accent_phrases
- voicevox_mora_pitch
- voicevox_mora_length
- voicevox_mora_data
（なし）
（なし）
=> Add: C APIに中レベル（？）のAPIを追加

example/python/README.md
<https://github.com/VOICEVOX/voicevox_core/pull/421#discussion_r1193078233> について、PowerShell側をやっていませんでした。
- #421
=> Fix up #421

crates/voicevox_core_python_api/python/voicevox_core/__init__.py, example/python/README.md, example/python/run.py
1. example/pythonのdead codeを削ります。
2. isort(`profile=black`)をかけます。
特に1.は忘れそうなので今PRを出しておきます。
=> Pythonコードをリファクタ

Cargo.toml, crates/voicevox_core/Cargo.toml, crates/voicevox_core_c_api/Cargo.toml
<https://github.com/rust-lang/rustfmt/pull/5240>の最新のコミットである<https://github.com/rust-lang/rustfmt/pull/5240/commits/093e19fea7ab3646ffccedb6cd43f8504842d1f5>でCargo.tomlをフォーマットします。
Resolves #469.
=> Cargo.tomlをフォーマットする

README.md
=> READMEのスペースが足りてなかった

crates/voicevox_core_c_api/include/voicevox_core.h, crates/voicevox_core_c_api/src/lib.rs, crates/voicevox_core_c_api/tests/e2e/symbols.rs
<https://github.com/VOICEVOX/voicevox_core/pull/370#discussion_r1141398622>
- #370
- #497
=> [project-vvm-async-api] `voicevox_{,synthesizer_}is_loaded_voice_model`

.github/workflows/build_and_deploy.yml
project-s用の推論で、なぜかF0が変に0になる箇所が多かったのを解消するプルリクエストです。
モデルの更新のみなのでコードはほぼ変わりません。
- https://github.com/VOICEVOX/voicevox_project/issues/15
=> [project-s] voicedの判定がかなりイマイチだったのでモデルを更新

README.md
=> [project-vvm-async-api] 工事中の案内を書く

README.md
C# の参考実装を作成したため、READMEに実装例として載せました。
ref: https://github.com/VOICEVOX/voicevox_core/issues/559
自前で調整せずとも C# のラッパーが生成出来る状態であれば、例えばこのリポジトリで提供できれば…？と思いましたが、
現状自前で調整が必要な箇所が多いため、現実的ではないと判断しました。
=> C# の参考実装のリポジトリをREADMEに記載する

crates/voicevox_core_python_api/python/voicevox_core/__init__.py
=> Fix: Python APIで__version__が再エクスポートされていなかったのを修正

crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/VoiceModel.java
=> Java API：Visibilityを修正

example/python/run.py
example/pythonをblackでフォーマットします。これでmainのCIが落ちないようになるはずです。
- #598 
（なし）
=> Code: blackでフォーマット

.github/workflows/java_lint.yml, .github/workflows/python_lint.yml, example/python/run.py
=> Fix: Python Lint Workflowの実行条件を変更

.github/workflows/build_and_deploy.yml, build_util/codesign.bash
0.14.5をmainブランチにマージします。
コンフリクトは解消済みのはずです。
（`.github/workflows/build_and_deploy.yml`の環境変数変更のとこがコンフリクトしただけでした）
=> merge 0.14.5

.github/workflows/build_and_deploy.yml
mainブランチに書かれているリソースのバージョン（特にvoicevox_fat_resource）が低くてdownload_testがエラーになっていたので修正です。
（READMEが入ってませんでした。。）
- https://github.com/VOICEVOX/voicevox_core/issues/619
=> リソースのバージョンを更新

.github/workflows/build_and_deploy_downloader.yml
- https://github.com/VOICEVOX/voicevox_core/pull/627
の時に変更した証明書周りのビルドコードですが、ダウンローダーの方に変更加えるの忘れていました。
- https://github.com/VOICEVOX/voicevox_project/issues/37
=> 証明書周りのミス修正

crates/voicevox_core_java_api/lib/build.gradle, crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/OpenJtalk.java
AndroidだとTMPDIR環境変数を用意しないと動かないのを修正します。
- ref: https://github.com/VOICEVOX/voicevox_mobile/pull/40#discussion_r1394088913
（なし）
=> Add: Androidでの注意を追加

crates/voicevox_core/src/publish.rs, model/metas.json
- https://github.com/VOICEVOX/voicevox_project/issues/15#issuecomment-1917673233
に従って、サンプルのスタイルタイプの名称を変更します。
- https://github.com/VOICEVOX/voicevox_project/issues/15
ついでに「decoder」という言葉を使っている唯一の場所を消しておきました。
=> [project-s] スタイルタイプの名称変更

.github/workflows/download_test.yml
=> 一時的にDownload test workflowを無効化する

crates/voicevox_core_java_api/src/common.rs, crates/voicevox_core_java_api/src/lib.rs, crates/voicevox_core_java_api/src/logger.rs
=> Javaの`initLogger`のnative実装を移動

crates/voicevox_core_java_api/lib/src/test/java/jp/hiroshiba/voicevoxcore/VoiceModelTest.java
<https://github.com/VOICEVOX/voicevox_core/pull/796#discussion_r1613490555>が心配なのでテストを書きます。
ref #796
=> chore: #796 に対するJavaのテストを追加

.github/workflows/build_and_deploy.yml, .github/workflows/build_and_deploy_downloader.yml, .github/workflows/cargo-deny.yml, .github/workflows/download_test.yml, .github/workflows/generate_document.yml, .github/workflows/java_lint.yml, .github/workflows/labeler.yml, .github/workflows/python_lint.yml, .github/workflows/test.yml, .github/workflows/typos.yml, _typos.toml
すべてのアクションのバージョンを最新バージョンにアップグレードしました
- 他のアクションは問題ありませんが、[github/issue-labeler@v3](https://github.com/github/issue-labeler/releases/tag/v3.0)において以下のようなブレイキングチェンジが発生しましたが、無視しても問題ないでしょうか？
> Breaking change: Issue labels that do not match a regex will no longer be removed by default unless you set sync-labels: to 1
- "PNGs"単語にタイポの問題が発生したため、無視するように設定しました。
=> Bump actions

crates/voicevox_core_python_api/pyproject.toml
=> chore: `tool.maturin.skip-auditwheel = false`

Cargo.lock, Cargo.toml, crates/voicevox_core/src/infer/runtimes/onnxruntime.rs
=> update: ortを更新

deny.toml
Refs: #876, #855
CIが壊れてるので、優先してマージするべき
=> fix(ci): fix up #876: update deny.toml

crates/voicevox_core_c_api/tests/e2e/log_mask.rs
=> fix(test): C APIのテストがWindowsで壊れているのを直す

Cargo.lock, Cargo.toml, deny.toml
Refs: VOICEVOX/open_jtalk-rs#32
=> chore(deps): bump open_jtalk-rs

crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/StyleType.java, crates/voicevox_core_python_api/python/voicevox_core/_models.py
#894 をやってるときに[発見](https://github.com/VOICEVOX/voicevox_core/pull/894#discussion_r1885088121)しました。
=> fix: fix up #761: JavaとPythonの`StyleType`を埋める

crates/voicevox_core/src/synthesizer.rs, crates/voicevox_core_c_api/tests/e2e/log_mask.rs, crates/voicevox_core_c_api/tests/e2e/snapshots.toml
<https://github.com/VOICEVOX/voicevox_core/pull/865/files#r1823086190>で入れた`mod inner`を消します。
Hide whitespace changesでちょうどよく見える感じになってるかと。
=> refactor: `mod inner`を削除

.github/workflows/build_and_deploy_downloader.yml
- https://github.com/VOICEVOX/voicevox_core/pull/905
と同じ処理を今のmainブランチにも適用します。
`$OS`は意図と違うので`$runner_OS`にします。
release-0.15をmergeしようかと思ったのですが、ファイル名が変わっている（downlaoder.ymlのになってる）のもあってちょっと面倒そうだったので普通にプルリクエストにしてしまいました！
=> fix: OS -> RUNNER_OS

Cargo.lock, Cargo.toml
=> fix: bump ort

.github/workflows/test.yml, crates/voicevox_core_c_api/src/compatible_engine.rs
`compatible_engine`に対してもClippyがかかるようにする。
=> chore: `--features load-onnxruntime`でClippyをかける

crates/voicevox_core_python_api/python/test/conftest.py, crates/voicevox_core_python_api/python/test/test_type_stub_consts.py, crates/voicevox_core_python_api/python/voicevox_core/_models.py, crates/voicevox_core_python_api/python/voicevox_core/_rust/asyncio.pyi, crates/voicevox_core_python_api/python/voicevox_core/_rust/blocking.pyi
=> refactor: Python 3.9と3.10の新機能を使う

crates/downloader/src/main.rs
=> refactor: #928 用のコード移動

crates/voicevox_core_python_api/python/voicevox_core/_models.py
=> fix(docs): `SpeakerMeta.{speaker_uuid,version}`が逆だった

crates/downloader/src/main.rs
これまでは`core` (i.e. C API)が必要無くても`--core-repo qryxip/voicevox_core --version 999.999.999`のようにしないとエラーとなる状態であったが、それを解消する。
=> feat: [downloader] 対象外の`DownloadTarget`を見に行かないように

.github/workflows/build_and_deploy.yml
<https://github.com/VOICEVOX/voicevox_core/pull/954#issuecomment-2619315282>
=> build: fix up #825: fix a typo

build_util/make_ios_xcframework.bash
=> build(fix): fix up #954: fix `build_xcframework`

crates/downloader/src/main.rs
\[追記\] 0.0.1-preview.4の VOICEVOX/voicevox_vvm#9 も。
BREAKING-CHANGE: VOICEVOX/voicevox_vvm#5 の反映。
Refs: #545
=> feat!: [downloader] voicevox_vvmを`0.0.1-preview.4`に

example/python/run-asyncio.py
=> fix: [example] [Python] fix up #944: run-asyncio.pyも更新

crates/voicevox_core_python_api/python/test/test_asyncio_user_dict_manipulate.py, crates/voicevox_core_python_api/python/test/test_blocking_user_dict_manipulate.py, crates/voicevox_core_python_api/python/voicevox_core/_rust/asyncio.pyi, crates/voicevox_core_python_api/python/voicevox_core/_rust/blocking.pyi, crates/voicevox_core_python_api/src/lib.rs
Java APIの`UserDict#toHashMap`に合わせる。
`to_python_dict`とかでもよかったかも？
=> feat!: [Python] `UserDict.words` → `UserDict.to_dict`

.github/workflows/build_and_deploy.yml
#979 をやっているときにたまたま気付きました。危なかった！
=> build(fix): fix up #954: codesign.bashの引数も更新

crates/downloader/src/main.rs
VOICEVOX/onnxruntime-builder#75 に対応する。
```
----------BEGIN VOICEVOX ONNX RUNTIME TERMS OF USE----------
1. 商用・非商用問わず利用することができます
2. アプリケーションに組み込んで再配布することができます
3. 作成された音声を利用する際は、各音声ライブラリの規約に従ってください
4. 作成された音声の利用を他者に許諾する際は、当該他者に対し本許諾内容の 3 及び 4 の遵守を義務付けてください
- 逆コンパイル・リバースエンジニアリング及びこれらの方法の公開すること
- 製作者または第三者に不利益をもたらす行為
- 公序良俗に反する行為
本ソフトウェアにより生じた損害・不利益について、製作者は一切の責任を負いません。
ご利用の際は VOICEVOX を利用したことがわかるクレジット表記が必要です。
----------END VOICEVOX ONNX RUNTIME TERMS OF USE----------
上記の利用規約に同意しますか？ (Do you agree with the above terms of use?) (y/N): y
```
=> feat: [downloader] `onnxruntime`でも利用規約への同意を求める

crates/voicevox_core/src/synthesizer.rs, crates/voicevox_core/src/version.rs, crates/voicevox_core_c_api/include/voicevox_core.h, crates/voicevox_core_c_api/src/lib.rs, crates/voicevox_core_python_api/README.md, crates/voicevox_core_python_api/python/voicevox_core/asyncio.py, crates/voicevox_core_python_api/python/voicevox_core/blocking.py, example/kotlin/README.md
readmeやAPIドキュメントのうち、軽く解決できそうなものだけやる。面倒そうなのは放置。
=> docs: 軽く解決可能なTODOとFIXMEを解消

crates/voicevox_core_python_api/python/voicevox_core/_rust/asyncio.pyi, crates/voicevox_core_python_api/src/lib.rs
=> feat: [Python] fix up #988: `asyncio.OpenJtalk`もやる

Cargo.lock, Cargo.toml
=> chore(deps): update voicevox-ort

.github/workflows/download_test.yml
`Download test workflow`が動くようにする。
**最低限今動くようにしただけ**。近いうちにテスト内容を再考する必要がある。
=> ci: `download_test`を直す

deny.toml
次の ~~二~~ 一つに関してdeny.tomlを更新する。
1. #962 にて忘れていた分。
2. ~~つい数時間前に出た[RUSTSEC-2025-0007]。 #962 は無関係。~~
- ~~対応については本PRの中身を参照。~~
- RUSTSEC-2025-0007は撤回された。
[RUSTSEC-2025-0007]: https://rustsec.org/advisories/RUSTSEC-2025-0007
1.についてはどうにかしたい感がある。PR出している人がVOICEVOX/reviewerである場合に限ってPRでも動作するとか？
=> ci(fix): fix up #962: 更新し忘れたdeny.tomlを更新

docs/guide/user/downloader.md
#1017 における次の事項を解決する。
> ### [Downloader](https://github.com/VOICEVOX/voicevox_core/blob/main/docs/guide/user/downloader.md)
>
> - [ ] ダウンロードするものの説明が少ないかも？
=> docs: "ダウンローダーがダウンロードするもの"の節を追加

crates/downloader/src/main.rs
Refs: VOICEVOX/voicevox_vvm#12, VOICEVOX/voicevox_vvm#14
=> feat: [downloader] voicevox_vvmを`0.0.1-preview.5`に

.github/workflows/build_and_deploy.yml
=> build!: sample.vvmのデプロイをやめる

README.md
=> docs: 「工事中」を消す

.github/workflows/check-release-target-tuples.yml
=> ci: fix up #1012: `[ -n`と間違えて`[ -z`としてたのを修正

crates/downloader/src/main.rs
Refs: https://github.com/VOICEVOX/voicevox_vvm/releases/tag/0.1.0
=> feat(downloader): voicevox_vvmを0.1に

.github/workflows/build_and_deploy.yml
タイトルのとおりです。
特に要らなくなってるのが残ってるのに気づいたので消してみました。
0.16までにマージされてる必要はなさそう！
=> chore(ci): 不要になっている環境変数を消す

deny.toml
#1078 で更新し忘れたdeny.tomlを更新。
もう何度目かもわからないためどうにかしたい…というのも何度か言っている気がしている…。
=> ci: deny.tomlを更新して`bans`を直す

crates/voicevox_core_c_api/tests/e2e/testcases/global_info.rs
=> refactor: 謎のコードを削除

deny.toml
- #1082 にて不要になった`onig_sys`の記述を削除。
- #1086 で更新し忘れた分の更新。
=> ci: deny.tomlを更新

crates/downloader/src/main.rs
リトライ機能を`--retry`で実装。引数の数字の分だけ上乗せでリトライする。
close #1071
Cloneつかいまくってます。
=> feat(downloader): リトライ機構を実装

.github/workflows/download_test.yml, .github/workflows/generate_document.yml, .github/workflows/test.yml, build_util/codesign.bash
VOICEVOX/voicevox_engine#1775 と同じようなことを行う。ただしこのリポジトリにおいては、どちらかというと`--retry`を付けるのがメイン。
=> chore: curlは`-f --retry 3 --retry-delay 5`で用いる

CHANGELOG.md, crates/downloader/src/main.rs
#641 などで追加した`--*-repo <REPOSITORY>`と、 #1093 で追加した`--models-pattern <GLOB>`にhelpを書いていなかったので書く。
=> feat(downloader): 書いていなかったオプションのhelpを埋める

CHANGELOG.md, crates/downloader/src/main.rs, docs/guide/user/downloader.md
#350 から存在していたがドキュメントで言及されていなかった機能を、正式に説明する。
cf. <https://github.com/VOICEVOX/voicevox_core/issues/1120#issuecomment-3155791344>
=> feat(downloader): `$GITHUB_TOKEN`について説明する
