VOICEVOX/voicevox_core

- core.h
core.h内で無条件でDLLExportが指定されておりincludeされることを想定されていなかったため、`VOICEVOX_CORE_EXPORTS`マクロが存在する場合のみに`__declspec(dllexport)`を、存在しない場合は`__declspec(dllimport)`を指定するように変更しました。
> ヘッダを利用時にinclude可能なように変更

- example/python/forwarder.py
ONNX版コアのRaspberry Pi（32bit armv7l hardware float環境）向けのビルドを試しています。
そこで、サンプルコード実行時、`example/python/forwarder.py` 内の`numpy.repeat`の呼び出しで`TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'`というエラーが発生しました。
- https://numpy.org/devdocs/reference/generated/numpy.repeat.html
このPRは、`numpy.repeat`の繰り返し回数`repeats`として`numpy.int64`型を渡していた部分を`numpy.int32`型に変更し、numpy内部で縮小変換（int64→int32の変換）させないようにすることで、実行時例外が起きないようにします。
~~32bit環境か64bit環境かによって変わるかもしれないので、こちらで検証したらドラフトを外します。
変更が必要であれば、このPRのまま対応するつもりです。~~
→ 64bit環境でもint32で動作しました。
Raspberry Pi 4B実機でのログ
<details>
- 使用したONNXRuntimeバイナリ: https://github.com/aoirint/onnxruntime-arm-build/releases/tag/v1.8.2-8
```shell
$ pip3 show numpy --version
Name: numpy
Version: 1.21.3
$ python3 ../../example/python/run.py …
```
> Pythonサンプルコード: 数値型の縮小変換により実行時例外が起きる問題の修正（32bit環境）

- .github/workflows/build.yml
ONNX版自動ビルドにおいて、
共有ライブラリのビルド後の処理 `cmake --install` が抜けていたため、追加します。
- https://github.com/Hiroshiba/voicevox_core/blob/8cc011035e2570c4f2a87cbfa6dfb0ee95e4c274/onnx/README.md#1-%E3%82%B3%E3%82%A2%E3%83%90%E3%82%A4%E3%83%8A%E3%83%AA%E3%81%AE%E4%BD%9C%E6%88%90
Linux用ビルドでは、`cmake --install`を実行しない場合、rpathに`$ORIGIN`が設定されないため、同じディレクトリにおいた共有ライブラリを読み出せない問題があったと思います。
#33
> ONNX版自動ビルド: cmake --install処理の追加

- README.md
ref: https://github.com/Hiroshiba/voicevox_core/issues/23
> 全体構成への言及を追加

- .github/workflows/build.yml
Artifactに自動ビルドの成果物をアップロードする際、
core.zipに圧縮してからアップロードしていたため、
Artifactのzipの中にcore.zipが入った、入れ子の状態になっていました。
このPRは、入れ子を解消し、core.zipを直接Artifact一覧からダウンロードできるようにします。
- 現在のArtifact（artifact） https://github.com/Hiroshiba/voicevox_core/actions/runs/1413653469
- 解消したArtifact（core） https://github.com/aoirint/voicevox_core/actions/runs/1414117128
> ONNX版自動ビルド: Release用Artifactが入れ子のzipになっていたのを解消

- .github/workflows/build.yml
> core.hの場所が変わったのでbuild.ymlを追従

- core/__init__.py
* PATH指定が壊れていた ( 追加パスと既存のパスとの間に `;` が挟まっていなかった )
* onnxruntime_providers_cuda.dll はLoadLibraryすると壊れる (https://qiita.com/elftune/items/cd2dabc06343a5ecf39a) 実際のところロードするdllはcore.dllのみで十分だったためそのように変更
pytorchからのコピペとはいえ__init__.pyの可読性がよろしくないので、依存dllを`site-packages/core/lib/*.dll`に置くのではなく`site-packages/core`直下に置きたい。が、そのようなsetup.pyが上手く書けないのでだれかやってほしい
> bugfix: windows環境でのdllロードを修正

- core/_core.pxd
- core/_core.pyx
- core/src/core.cpp
- core/src/core.h
関数の引数ではlongで定義されているものが、実際に使用する前にint64_tへキャストしてから使用していたので、引数の定義をint64_tへ変えてキャストしないようにしました。
この変更に伴い、cython関連のコードも変更しています。
ビルドは通りましたが、cythonのコードがビルドに関連しているかわからないので、確認をお願いします。
無し
無し
> int,longを全てint64_tへ変更して不要なキャストを削除

- .github/workflows/build.yml
- CMakeLists.txt
- README.md
- core/CMakeLists.txt
- core/_core.pxd
- core/_core.pyx
- core/src/core.cpp
- core/src/core.h
- requirements.txt
- setup.py
- tests/core_test.py
* これまでpip install時に自動でcmakeが走っていたが、これを取りやめてcmake buildを手動でやるようにする
* cpu版/cuda版を統一し、ダウンロードしてきたonnx runtimeがcudaに対応しているかどうかを実行時に確認するように変更
* 単体テストをgithub actionに追加
close #50 
ref #16 : cudaをサポートしているかどうかを確認する `supports_cuda` という関数を実装したので、良さそうならこれをAPIに追加しようと思います
> cmakeとsetup.pyを切り離す、テストの追加

- README.md
サンプルコードに` \`が入ってなかったっぽかったので、気になったので修正してみました。
> サンプルコードの \ 入れ忘れを修正

- .github/workflows/build.yml
- README.md
armhfビルドについて、 #55 で ONNX Runtimeのビルドが [別リポジトリ](https://github.com/VOICEVOX/onnxruntime-builder)に切り出されたため、
そのReleaseを使ったビルドに書き換えて再開します。
ONNX Runtimeのビルド成果物は切り出し先のReleaseにアップロードされるようになったので、
同梱しないようにしています。
切り出し先Releaseの圧縮ファイル構造の修正が必要です。
- <https://github.com/VOICEVOX/onnxruntime-builder/pull/2>
- <https://github.com/VOICEVOX/voicevox_core/issues/54#issuecomment-1003274192>
構造が修正されたReleaseでビルドの動作を確認したらDraftを外します。
- <https://github.com/aoirint/voicevox_core/actions/runs/1640531481>
- close #54
> armhfビルド: ONNX Runtimeビルドのリポジトリ切り出しに対応

- README.md
- core/_core.pxd
- core/_core.pyx
- core/src/core.cpp
- core/src/core.h
- example/python/run.py
#63 の実装です
ref #63 
ref VOICEVOX/voicevox_engine#282
VV_NUM_THREADSに不正な値が入ったときは例外をcatchせず落ちるようにしていますがこの方針でいいでしょうか？
またstd::getenvを使うとVC++だとwarningが出るのでいい方法があれば教えて下さい。よろしくおねがいします
> CPU使用スレッド数を設定できるようにする

- .github/workflows/build.yml
題の通り
1.10でONNX RuntimeでもUniversal Binaryが配布される様になったので、併せてMac版のUniversal Binaryをビルドする様にし、配布名も`libcore_cpu_x64.dylib`から`libcore_cpu_universal2.dylib`に変更しました。
残念ながら、arm64な環境のテストは実行できないので、x64のみのままにしています
- close #60 
- @.aoirint さん、ONNX Runtime Builder側の対応感謝します...! 
これをマージしてビルドしたコアをエンジンで利用する場合は、エンジンのGitHub ActionでONNX Runtimeのバージョンアップに対応した形に修正する必要があります。
> ONNX Runtimeのバージョンを1.10にアップグレードする

- README.md
自然言語によりコードの一部だけがMITライセンスっぽくなっていたので、コードは全部MITライセンスであることを明示してみました。
現在のコードの大半は @Yosshi999 さん作になりそうです。
MITライセンスにしちゃいたいのですが、大丈夫でしょうか･･･？👀
> コードはMITライセンスであることを明示する

- .github/workflows/build.yml
- .gitmodules
- CMakeLists.txt
- core/CMakeLists.txt
- core/src/core.h
- core/src/engine.cpp
- core/src/engine/acoustic_feature_extractor.cpp
- core/src/engine/acoustic_feature_extractor.h
- core/src/engine/full_context_label.cpp
- core/src/engine/full_context_label.h
- core/src/engine/kana_parser.cpp
- core/src/engine/kana_parser.h
- core/src/engine/model.h
- core/src/engine/mora_list.cpp
- core/src/engine/mora_list.h
- core/src/engine/openjtalk.cpp
- core/src/engine/openjtalk.h
- core/src/engine/synthesis_engine.cpp
- core/src/engine/synthesis_engine.h
~~今のところ動きません~~とりあえず動くようになりました
~~wavの生成周りは多分うまくいっていますが、それを実際に実行(https://gist.github.com/y-chan/5d09177b3771bd17bfa946623b1fd905 )してみるとうまく行きません...(正しくないと思われるノイズ音声が再生されます)~~
https://gist.github.com/y-chan/5d09177b3771bd17bfa946623b1fd905 に実行のためのファイルと説明を置いておいたので、良ければ検証にご利用ください。
ref #43
> C++音声合成ライブラリの追加

- core/src/engine/full_context_label.cpp
cpp-libraryブランチにおいて`core\src\engine\full_context_label.cpp`のdebug用と思われるcoutを消去
> debug用と思われるcoutを消去

- core/src/core.h
- core/src/engine.cpp
- voicevox_tts内でエラー発生してもユーザーが知ることができないのでResultCode用のenumを定義し、戻り値にした
- voicevox_ttsでもともとの戻り値だった音声データのポインタはそのさらにポインタを関数の引数として受け取って成功時に出力するように変更した
- ResultCodeをメッセージに変換する関数を定義
- C言語では extern "C" を使えないのでC++を使ってるときのみ extern"C"するように変更
- VOICEVOX_CORE_APIは関数宣言時のみにあれば良いので使い終わったらundefするように変更
- engine.cpp内でthrowしてるところがあったが、他言語ではC++の例外をcatchすることができないので例外が発生したらアプリケーションが確定で終了してしまう。そのため例外を投げるのではなくError Result Codeを返すように変更した
> C API定義の改善と実装を行った(既存実装に影響でない範囲で)

- .github/workflows/build.yml
Actionsでonnxruntimeをダウンロードする際、ファイルコピーのパスをDirectMLに合わせた事によって通常版でのコピーに失敗していたので、修正しました
Actionsのcacheによってダウンロードがスキップされていたことでこちらのリポジトリでは問題が現れませんでした。
> DirectML対応によるActionsの問題の修正

- .gitmodules
題の通り。
mecabの問題でしたので、依存するsubmoduleを変更しておきました。
ただし、私(y-chan)のリポジトリを指しているので、それを改善するまで(OpenJTalk側に出したPRがマージされるまで)Draftにします
> Windows ARM64環境でビルドできない問題の改善

- core/src/engine.cpp
- core/src/engine/full_context_label.cpp
- core/src/engine/full_context_label.h
- core/src/engine/synthesis_engine.cpp
- core/src/engine/synthesis_engine.h
newしてそのまま開放されていないものがあったのでnew使うのをやめた
要動作確認
> メモリリークしていた部分を修正した

- core/CMakeLists.txt
- core/src/core.cpp
- core/src/engine.cpp
- core/src/engine/acoustic_feature_extractor.cpp
- core/src/engine/acoustic_feature_extractor.h
- core/src/engine/full_context_label.cpp
- core/src/engine/kana_parser.cpp
- core/src/engine/kana_parser.h
- core/src/engine/model.h
- core/src/engine/mora_list.cpp
- core/src/engine/mora_list.h
- core/src/engine/openjtalk.cpp
- core/src/engine/openjtalk.h
- core/src/engine/synthesis_engine.cpp
- core/src/engine/synthesis_engine.h
`cpp-library`ブランチにおいて未使用のincludeや他のheaderに依存しているinclude文を整理しました.
> include文の記述を整理

- core/src/core.h
- core/src/engine.cpp
- core/src/engine/openjtalk.cpp
- core/src/engine/openjtalk.h
- core/src/engine/synthesis_engine.cpp
- core/src/engine/synthesis_engine.h
SynthesisEngine初期化時に、OpenJTalkも同時に初期化するようにし、辞書のロードは後から行える(辞書のロードをしなくてもSynthesisEngine内の関数にアクセスできる)ようにします。
現状のままでも辞書のロードをしなくともSynthesisEngine内の関数にアクセスできますが、OpenJTalk自体や、辞書の読み込み状況などの取り回しが若干面倒だったのと、TODOを解決する目的で、このような変更を加えました。
これによるC APIユーザー側から見た挙動の変化は特にありません。
> OpenJTalkをグローバルに持たせないようにする

- core/src/engine/openjtalk.h
OpenJTalkで管理している各フィールドはコピーできてしまうと二重でclarが実行されたり、あるいはメモリリークが発生する可能性がある
これを避けるために[Copy Protection(あるいはCopy Guard)というテクニック](https://ykoreeda.blogspot.com/2014/08/c.html) を使うことによりOpenJTalkがコピーされるようなコードが書かれるとコンパイルエラーになるように実装した
> Implemented Copy Protection for OpenJTalk

- core/src/core.h
- core/src/engine.cpp
- core/src/engine/kana_parser.cpp
- core/src/engine/kana_parser.h
題の通りです。
元々AquesTalkライク記法を解釈するための関数(`parse_kana`)を備えていましたが、それが盛大にバグを含んでいたので、同時に修正です。
こちらに動作確認用のテストコードを置いています。
https://gist.github.com/y-chan/91f180f525be2415f7785b545e5011c1
> AquesTalkライク記法によるTTS関数の追加とそれに伴うバグの修正

- .github/workflows/build.yml
- .gitmodules
- CMakeLists.txt
- core/CMakeLists.txt
- core/src/core.cpp
- core/src/core.h
- core/src/engine.cpp
- core/src/engine/acoustic_feature_extractor.cpp
- core/src/engine/acoustic_feature_extractor.h
- core/src/engine/full_context_label.cpp
- core/src/engine/full_context_label.h
- core/src/engine/kana_parser.cpp
- core/src/engine/kana_parser.h
- core/src/engine/model.h
- core/src/engine/mora_list.cpp
- core/src/engine/mora_list.h
- core/src/engine/openjtalk.cpp
- core/src/engine/openjtalk.h
- core/src/engine/synthesis_engine.cpp
- core/src/engine/synthesis_engine.h
C++ TTSライブラリ作業用ブランチを`main`にマージします。
これにより、`main`ブランチにTTS機能群(通常TTS/AquesTalkライク記法TTS)が実装されます。
close #43 
C++ TTSライブラリブランチは複数人でコミットを行ったので、squshではなく通常のマージをしたいです。
> C++ TTSライブラリを`main`にマージ

- core/src/engine/synthesis_engine.cpp
wavバイナリの生成時に正しくバイナリサイズを計算できていないと思われる箇所があったので修正しました。
wavバイナリを一通り生成した後に、ファイルサイズや波形データのサイズを再計算する処理がありましたが、そこにもバグがありました。修正することも考えたのですが不要な処理のようにも思えたので削除しました。もしこの処理が必要な理由があった場合は、再計算の処理を再挿入してからバグ修正したいと思います。
> TTSライブラリにおけるwav生成処理の修正

- .github/workflows/build.yml
Windowsで暗黙的リンクできるように、libファイルをArtifactsのzipに含めます。
#112 は、暗黙的リンクを使用しています。
とくになし
Releaseへのアップロードに失敗します。
モデルファイル埋め込みによるサイズの増加が原因だと思うので、#111 がマージされると解消されると思います。
> libファイルをArtifactsのzipに含める

- .github/workflows/build.yml
#106 のzip分割を実装します
https://github.com/VOICEVOX/voicevox_core/pull/99#pullrequestreview-917911744 に倣い、動的ライブラリファイルの名称は現状と同様にリネームしています
ref #106
> Releaseのzipをターゲットごとに分割する

- .github/workflows/build.yml
core.dllをアーキテクチャごとにリネームしていましたが、 #111 で１つのzip内に１つだけdllが入るようになり、リネームしないようにしたほうがシンプルだと思います。
リネームをなくしてみる提案も兼ねてプルリクエストを作ってみました。
こちらでビルドしてみています。
https://github.com/Hiroshiba/voicevox_core/releases/tag/check-2022-04-11
> Libcoreなどをリネームしないようにする

- .github/workflows/build.yml
DirectMLが増えて、リリースするビルドが４つ増えました。
４つの違いはCPUのアーキテクチャです。１つあたり200MBを超えるので、なかなかの大容量になっています。
DirectMLの場合は、x64以外はなくてもいいのかなと思ったので、x64以外を削るPRを作ってみました。
（cuda版もx64だけなので、これで揃うと思います）
> DirectMLの対応CPUアーキテクチャ減らす

- .github/workflows/build.yml
- example/cpp/windows/README.md
現在 Releases にアップロードされる zip ファイルは、ダウンロードして `unzip` や `7z` のコマンド等で解凍すると解凍時のカレントディレクトリに直接中身が展開されるようになっています。
これまでは `core.zip` をダウンロードして解凍すると `core` ディレクトリ以下に内容が入っている状態で展開されました。それと同様になるように（解凍すると `core` ディレクトリ以下にファイル群が存在するように）zip の生成方法を変更しました。
https://github.com/PickledChair/voicevox_core/releases/tag/0.12.0-pickledchair-1 で試しにリリースしたものを公開しています。 ~~また、実装はしたのですが、修正やコメント追加等を行いたいので draft とさせていただきます。~~
以前から、`upload-to-release-cpp-shared` ジョブが走るときは `core.zip` の内容を core という artifact としてアップロードするようになっています。#111 の変更においても、Releases にアップロードされる内容を core の中に全てアップロードしています。しかし、ライブラリ１ファイルあたりのバイナリサイズがかなり大きくなったため、core のサイズも顕著に大きくなりました（OSS版であっても core のサイズは 800 MB 以上になっています。 https://github.com/PickledChair/voicevox_core/actions/runs/2176719929 で確認できます。製品版ではさらに大きくなっていると予想しています）。今回の変更でこの core …
> Releasesにアップロードされるzipの構造を変更

- .github/workflows/build.yml
- example/cpp/unix/.gitignore
- example/cpp/unix/CMakeLists.txt
- example/cpp/unix/README.md
- example/cpp/unix/simple_tts.cpp
`example/cpp/unix` ディレクトリに Linux・Mac 向けのサンプルコード (`simple_tts.cpp`) を追加します。サンプルのビルド方法は [example/cpp/unix/README.md](https://github.com/PickledChair/voicevox_core/blob/add-unix-cpp-sample/example/cpp/unix/README.md) に記載しています。また、Windows 向けのサンプルコード #112 と同様に、サンプルコードがビルドできるかどうかをチェックするCIジョブも追加しています。
https://github.com/VOICEVOX/voicevox_project/issues/1
改善したほうが良い点などありましたらご指摘ください……！
> Linux・Mac向けのサンプルコードを追加

- core/CMakeLists.txt
現在のcoreのソースコードはadd_library追加方法だと新たにcpp fileを追加するたびにadd_libraryを追加する必要がある
これではメンテの手間が増えるため、GLOB_RECURSEにより追加したsrc配下にあるcpp fileを自動的にadd_libraryするように修正した
今の実装が意図的にfile名を個別にしていてこの方法では問題あるようでしたらrejectしてください
> add_libraryに追加するファイルをメンテしやすいように修正

- core/src/core.h
core.hはC APIを意識して定義されてるが、デフォルト引数はC言語では使えないのでC++のみに有効になるように変更した
本当はデフォルト引数を消したかったが、使ってる人がいる可能性があるためC++で使ってる場合はそのままにするように修正した
> デフォルト引数はC言語では使えないのでC++のみに有効になるように変更した

- .github/workflows/build.yml
releaseを作る他に、workflow_dispatchでもビルドを開始できるようにしてみました。
デバッグでビルドしたいとき、releaseを作る方法だと毎回tagやreleaseを消去する必要がありますが、workflow_dispatchであれば途中でビルドがコケた場合はreleaseを作らないので便利です。
formatterがyamlファイルをいろいろ修正してしまいましたが、まあ良いかなということでそのままにしてあります。。
> workflow_dispatchでもビルド開始可能に

- crates/voicevox_core/src/error.rs
- crates/voicevox_core/src/internal.rs
- crates/voicevox_core/src/lib.rs
CI上でlintが走るように設定してあるのですが、それが仮実装のコードでエラー出るようになってしまっているのでその修正です
refs #128
> [Rust]CI上でのlintエラーを修正した

- .github/workflows/build.yml
- .gitignore
- CMakeLists.txt
- README.md
- core/CMakeLists.txt
- tests/CMakeLists.txt
- tests/unit_tests/core/engine/kana_parser_test.cpp
projectにunit test frameworkを導入しました。たたき台的な感じです。
ref https://github.com/VOICEVOX/voicevox_project/issues/1#issuecomment-1115204346
とりあえず導入を急ぐのと、どういう書き口で書けるのか見せるため実装してるテストケースは一つのみです。テストケースの充実は各々その機能を実装するときにでもやっていただければと思います。
Catch2で書きましたが、とりあえずコード見たほうが議論しやすいだろうと思って書いたものであり、Catch2採用が決定してるわけではないです
またCIでのテスト実行もこのPRではやりません。PR分けたほうが良さそうなので
リリース時にはテスト実行は不要なのでCIに引数を追加してます
テストコードの配置場所についてですが、とりあえず  `tests/unit_tests` の下に実装が書いてあるソースコードに対応する感じのディレクトリ構成にしました
念の為レビュー時にWindowsでもテスト実行できることを確認していただけますでしょうか
またVSCodeに[Catch2向けの拡張](https://github.com/matepek/vscode-catch2-test-adapter) があるようです
> append unit testing framework

- .github/workflows/test.yml
- crates/voicevox_core/Cargo.toml
- crates/voicevox_core/src/c_export.rs
- crates/voicevox_core/src/lib.rs
参考になりそうな簡単なテストコードと独断ですがtestingライブラリを導入しました
refs #128, #133
#133 がmergeされないとレビューできないので #133 からレビューする必要がある
> [Rust]簡単なテストコードとtestingライブラリの導入

- crates/voicevox_core/Cargo.toml
- crates/voicevox_core/build.rs
- crates/voicevox_core/src/c_export.rs
- crates/voicevox_core/src/error.rs
- crates/voicevox_core/src/internal.rs
- crates/voicevox_core/src/lib.rs
- crates/voicevox_core/src/status.rs
onnxruntimeをvoicevox_core rustに導入するPRです
refs #128
onnxruntimeの機能がちゃんと呼べてるかは get_supported_devicesのテストコードで確認している
initialize関数のボリュームが思っていた以上に重かったので、TODOコメントを残して実装は途中までにしてある
> [Rust]onnxruntimeをrust版voicevox_coreに導入

- core/src/engine/full_context_label.cpp
- core/src/engine/kana_parser.cpp
- core/src/engine/synthesis_engine.cpp
最初コードを書いていたときに、`has_value`/`value`関数を知らず、後から知って、こちらの方がコードが綺麗になることがわかったので、リファクタリングとして変更しました。
ただし、一部`std::nullopt`との比較の方が直観的で可読性が高い場所があったので、そこは残してあります。
> static castやnullopt比較をやめ、value関数などを使うようにする

- .github/workflows/build.yml
ビルド時の環境変数がなくなっていて、VERSIONファイルに虚無が書き込まれていたので、直しました。
この影響で 0.12.0 のリリースのVERSIONファイルは空白になってしまっています。
> coreのビルド時にバージョン情報がちゃんと入るようにする

- .gitignore
- example/python/.gitignore
Open JTalk 辞書を git 管理対象以外に
`python/example/run.py` が v0.12.1 に対応したことで、`open_jtalk_dic_utf_8-x.xx` を展開する必要が生じました。これを git 管理対象外とすることで、ローカルでブランチを往復するのを楽にしたいです。
#138
> .gitignore open_jtalk_dic in example

- Cargo.lock
- crates/voicevox_core/Cargo.toml
- crates/voicevox_core/src/status.rs
clang,llvmに依存しないようにするためonnxruntime-rsを更新しました
refs #128
> [Rust]onnxruntime-rs をアップデートした

- crates/voicevox_core/src/c_export.rs
- crates/voicevox_core/src/internal.rs
- crates/voicevox_core/src/status.rs
dll で export する C API のうち `supported_devices` 関数を実装しました。
C++ の実装（以下を参照）に習って、API を叩くたびに onnxruntime 側に使用できるデバイスを問い合わせる仕様にしています（必要に応じて、文字列の初期化時のみに使用できるデバイスを取得するように変更することを検討します）。
https://github.com/VOICEVOX/voicevox_core/blob/1ca62a84d515f493b15715fc8c720e07642c5a0b/core/src/core.cpp#L262-L267
ref #128 
このAPIを実装することで、Rust製コアをエンジンで読み込むことがとりあえず可能になります。
> [Rust] supported_devices を実装した

- crates/voicevox_core/src/c_export.rs
- crates/voicevox_core/src/error.rs
- crates/voicevox_core/src/internal.rs
- crates/voicevox_core/src/status.rs
#152 の変更を受けて、`internal` モジュールの `load_model` と `is_model_loaded` のテストを実装しました。
~~https://github.com/VOICEVOX/voicevox_core/pull/152#discussion_r893159188 で提案した方法でテストを実装してみています。~~
ref #128 
`load_model` 関数内で `speaker_id` から `model_index` の変換忘れを見つけたので合わせて修正しました（すみません、レビュー時に見落としていました……！）。
> [Rust] load_model と is_model_loaded のテストを実装した

- Cargo.lock
- crates/voicevox_core/Cargo.toml
- crates/voicevox_core/src/c_export.rs
- crates/voicevox_core/src/error.rs
- crates/voicevox_core/src/internal.rs
- crates/voicevox_core/src/status.rs
yukarin_s_forward を実装し、テストも書きました。とりあえず動きます。
`onnxruntime-rs` が `ndarray` と蜜結合した形で記述されていたため、素直に `ndarray` クレートを導入しました。
`ndarray` を使った経験がないため、もっと適切な書き方があるかどうかわからなかったのですが、とりあえず提出しました。
#128
> [Rust] yukarin_s_forward を実装した

- Cargo.lock
- crates/voicevox_core/Cargo.toml
- crates/voicevox_core/src/c_export.rs
- crates/voicevox_core/src/error.rs
- crates/voicevox_core/src/internal.rs
- crates/voicevox_core/src/status.rs
`yukarin_sa_forward` と `decode_forward` の実装を目指します。
~~現在、`yukarin_sa_forward` が推論に失敗するので、draft にしています。~~
現在、`decode_forward` の実装に取り組み中なので、draft にしています。
入力テンソルのうち、`length` のみが次元０であるため、引数は複数の次元のテンソルが混在する `Vec` となっています。そのためにテンソルの型を `ArrayD<i64>` にして混在できるようにしてみました~~が、それではうまくいかないようです~~。これでうまくいきました……！
ref #128
> [Rust] yukarin_sa_forward と decode_forward を実装（yukarin_s_forward の再実装含む）

- crates/voicevox_core/src/internal.rs
C++実装にあった音が途切れてしまうのを避けるworkaround実装です
refs #128
オリジナルの実装は [このあたり](https://github.com/VOICEVOX/voicevox_core/blob/main/core/src/core.cpp#L409-L448) になります
> [Rust]音が途切れてしまうのを避けるworkaround処理を追加した

- .github/workflows/build.yml
- build_util/codesign.bash
- https://github.com/VOICEVOX/voicevox_core/issues/163
の解決です。
証明書.pfxファイルをbase64エンコードしたものをsecret.CERT_BASE64に登録し、
証明書のパスワードをsecret.CERT_PASSWORDに登録して、
workflow_dispatchで「コード署名する」にチェックを入れてbuild.ymlを起動すれば、
core.dllが署名されます。
もしくは`code_signing`environmentを作成し、同様にCERT_BASE64とCERT_PASSWORDを登録して実行しても署名できます。
（こちらのフローは、OSSリポジトリ上でビルドする場合を想定しています。）
「コード署名する」にチェックを入れずにビルドしたり、releaseを作ってビルドした場合は署名用のコードが実行されないので、メンテナー以外の方は今まで通りにテストビルドができます。
close #163
こちらでビルドしてみました！
https://github.com/Hiroshiba/voicevox_core/actions/runs/2605648813
適当なwindows用のzipをダウンロードして展開、core.dllを右クリック→プロパティ→デジタル署名で署名を確認できるはずです。
> コード署名できるようにする

- .github/workflows/build.yml
inputのbooleanは文字列として渡ってくるので判定を修正しました。
- https://github.com/VOICEVOX/voicevox_core/pull/164
github actionsのbooleanはややこしい。。
> inputのbooleanは文字列として渡ってくるので判定を修正

- crates/voicevox_core/src/internal.rs
- crates/voicevox_core/src/status.rs
- `initialize` 関数中で TODO となっていた「GPUメモリを確保させる処理」を実装しました
- C++ 版では #143 の問題に対する workaround として #146 が実装されていましたが、Rust 版では未実装だったので実装しました
ref #128 
ref #143 
手元に GPU 環境がないため、正しく機能するかどうか動作確認できておりません。検証可能な方がいらっしゃれば動作テストしていただけると助かります……！
> [Rust] GPUを使う場合、初期化時にメモリ確保する。また、イントネーションの推論を常にCPUで行うようにする

- Cargo.lock
- crates/voicevox_core/Cargo.toml
[pyopenjtalkのcreate_user_dict](https://github.com/VOICEVOX/pyopenjtalk/blob/50b0296a9e1b666e5a09a41ec9e9284a2a9b608f/pyopenjtalk/__init__.py#L178-L190) を実装する目的で今後mecab_dict_index使いそうなため
mecab_dict_index関数をwrapperに追加したことによる対応です
refs #128
> open_jtalk-rsを0.1.6に上げた

- crates/voicevox_core/src/c_export.rs
- crates/voicevox_core/src/internal.rs
unsafeなコードを使う領域を減らして安全なコードな領域を増やすためinternalで使用していたunsafeなコードをc_exportがわに閉じ込めた
refs #128
> internalからunsafeを取り除いてc_export側でのみunsafeを使うようにした

- crates/voicevox_core/src/engine/mod.rs
- crates/voicevox_core/src/engine/model.rs
- crates/voicevox_core/src/engine/synthesis_engine.rs
実装を複数人で分けて行う場合、SynthesisEngineの定義がないと実装が競合したり実装を進めにくくなってしまうのであらかじめ仮実装するようにした
refs #128
> SynthesisEngineを仮実装した

- .github/workflows/test.yml
- crates/voicevox_core/src/error.rs
非テスト時のコードでdead_codeになっているものを検出できないため、 --testsなしのclippy実行も追加するようにした
refs #128
> CIで非テスト時のコードもclippyでチェックするようにした

- .github/workflows/test.yml
windows-2022 のテストが落ちることに対する姑息的な回避策を追加しました。
根本的な解決策ではありませんが、 https://github.com/VOICEVOX/voicevox_core/pull/140#issuecomment-1140276585 で行われた対策と同様に、`target/debug/deps` ディレクトリに onnxruntime.dll をコピーする方法でテストを行えるようにしています。
ref #128
> [Rust] windows-2022 でテストできないことに対する回避策を追加

- crates/voicevox_core/src/lib.rs
- crates/voicevox_core/src/status.rs
unsafe_codeをdenyにすることにより、うっかりunsafeコードを書くのを防ぐことが目的
例外としてc関数向けの実装である c_export moduleと、static領域に配置する必要があるStatus structについてはunsafeを使うことを許可している
refs #128
> [Rust]unsafeなコードを原則禁止にした

- Cargo.lock
- crates/voicevox_core/Cargo.toml
open_jtalk内の各オブジェクトのinitialize,clearはユーザーで勝手に呼び出されると予期しない動作をする可能性があるため、簡単に呼び出されないようにinitialize,clearにunsafeをつけたものを反映するためにopen_jtalkをupdateする
refs #128
> [Rust] update open_jtalk 0.1.7

- Cargo.lock
- crates/voicevox_core/Cargo.toml
- crates/voicevox_core/src/engine/full_context_label.rs
- crates/voicevox_core/src/engine/mod.rs
full_context_labelの型は他の人が実装する際に参照されることが多く、先に実装する必要がある
ひとまず参照できる程度なのでパフォーマンスの考慮やテストコードはあとで実装する
refs #128
> [Rust]full_context_labelをとりあえず他の人が参照できる程度に実装した

- .github/workflows/test.yml
> [Rust]キャッシュにonnxruntime.dllが残っているとCIテストが失敗するので修正した

- crates/voicevox_core/src/engine/acoustic_feature_extractor.rs
- crates/voicevox_core/src/engine/kana_parser.rs
- crates/voicevox_core/src/engine/mod.rs
- crates/voicevox_core/src/engine/model.rs
- crates/voicevox_core/src/engine/synthesis_engine.rs
- crates/voicevox_core/src/internal.rs
`SynthesisEngine::replace_mora_data` を実装します。また、このメソッドの実装には `SynthesisEngine::replace_phoneme_length` および `SynthesisEngine::replace_mora_pitch` も必要なので、これらのメソッドも実装します。
ref #128
> [Rust] SynthesisEngine::replace_mora_data を実装

- .github/workflows/test.yml
#182 で説明したように、 #180 で対処済みのはずの cp コマンドに起因するテスト失敗が引き続き起こっています。
cp コマンドのエラーメッセージは `will not overwrite just-created <filename> with <sameFilename>` です。以下の Q & A によると、このエラーが出ているということは、複数の onnxruntime.dll をコピーしようとしてエラーが発生している可能性があります。
https://stackoverflow.com/questions/4669420/have-you-ever-got-this-message-when-moving-a-file-mv-will-not-overwrite-just-c
実際、
```
cp target/debug/build/onnxruntime-sys-*/out/onnxruntime_*/onnxruntime-*/lib/onnxruntime.dll target/debug/deps/
```
というコマンドだと、`target/debug/build/onnxruntime-sys-*/out/onnxruntime_*/onnxruntime-*/lib/onnxruntime.dll` という形式のパスの onnxruntime.dll が複数存在すると、それらを全部コピーしようとすることになります。
このパスの形式の onnxruntime.dll がキャッシュ中に複数存在していてエラーが起こっていると仮定して、一つの onnxruntime.dll のみを選んでコピーするように対処してみました（一方、おそらく私のリポジトリでエラーが出なかったのは、onnxruntime.dll …
> [Rust] windows-2022 でのテスト時に複数のonnxruntime.dllがコピーされないように対処

- crates/voicevox_core/src/engine/open_jtalk.rs
- crates/voicevox_core/src/engine/synthesis_engine.rs
- crates/voicevox_core/src/internal.rs
`voicevox_load_openjtalk_dict` を実装しました。 #177 で一度実装していましたが、 #178 における `Internal` の設計の変更を優先するため close していました。それを再実装したものです。
`SynthesisEngine` と `Internal` それぞれで最低限のテストも実装しました。
ref #128
> [Rust] voicevox_load_openjtalk_dict を実装した

- crates/voicevox_core/src/engine/acoustic_feature_extractor.rs
https://github.com/VOICEVOX/voicevox_engine/blob/fd9f89795bd1ca9eb39d81b571404e789f9067d3/test/test_acoustic_feature_extractor.py#L178 を参考に、`acoustic_feature_extractor` のテストを現在実装している機能の範囲で追加しました。また、テストによって発見した実装の誤りを修正しました。
ref #128
> [Rust] acoustic_feature_extractor のテストを追加

- Cargo.lock
- crates/voicevox_core/Cargo.toml
- crates/voicevox_core/src/c_export.rs
- crates/voicevox_core/src/engine/full_context_label.rs
- crates/voicevox_core/src/engine/mod.rs
- crates/voicevox_core/src/engine/model.rs
- crates/voicevox_core/src/engine/synthesis_engine.rs
- crates/voicevox_core/src/error.rs
- crates/voicevox_core/src/internal.rs
`voicevox_tts` と `voicevox_wav_free` を実装します。
~~ビルド結果のコアを cpp example で呼び出せることを確認していますが、wav 自体は出力できる（wav ヘッダも問題ないように見える）ものの、音が鳴る wav を出力できていないので draft にしています。~~
ビルド結果のコアを cpp example から呼び出せます。おそらく期待通りに音声合成できていそうでした。
ref #128
> [Rust] voicevox_tts と voicevox_wav_free の実装

- .github/workflows/test.yml
https://github.com/actions/virtual-environments/issues/5583
refs #128
> [Rust]macos-10.15がdeplecatedになっていたためCIテストからとりのぞいた

- crates/voicevox_core/src/engine/mora_list.rs
- crates/voicevox_core/src/engine/synthesis_engine.rs
https://github.com/VOICEVOX/voicevox_core/pull/186/files/7d5507c3cf0e548717120c85bb8c73c7848e8952#r922725224 の指摘で、Moraをカタカナに変換する処理が抜けていたことに気づきました。これを追加します。
https://github.com/VOICEVOX/voicevox_engine/blob/master/voicevox_engine/synthesis_engine/synthesis_engine_base.py の実装を参考にしました。
#128
> [Rust] Moraをカタカナに変換する処理を実装

- crates/voicevox_core/src/c_export.rs
- crates/voicevox_core/src/engine/acoustic_feature_extractor.rs
- crates/voicevox_core/src/engine/full_context_label.rs
- crates/voicevox_core/src/engine/kana_parser.rs
- crates/voicevox_core/src/engine/mod.rs
- crates/voicevox_core/src/engine/model.rs
- crates/voicevox_core/src/engine/open_jtalk.rs
- crates/voicevox_core/src/engine/synthesis_engine.rs
- crates/voicevox_core/src/error.rs
- crates/voicevox_core/src/internal.rs
`voicevox_tts_from_kana` 関数を実装しました。
また、現段階の C++ 実装にある機能の再実装がこれでほぼ終わるので、clippy のエラーを抑制する目的で付けられていた `#[allow(dead_code)]` の対象を整理しました。
ref #128
> [Rust] voicevox_tts_from_kana の実装

- .github/workflows/build_and_deploy.yml
サンプル実装より、現在配置してるshared libraryはバージョンなしのため実行に失敗する。そのためバージョンつきのものに変更する必要がある
refs #128 https://github.com/VOICEVOX/voicevox_core/pull/197#issuecomment-1193085365
> [Rust]linux,macosのshared libraryをバージョンつきのものを配置するように変更

- .github/workflows/build_and_deploy.yml
macOS で cargo でビルドした libcore.dylib について、`otool -D libcore.dylib` で identification name を調べると
```
libcore.dylib:
/Users/runner/work/voicevox_core/voicevox_core/target/ターゲット名/release/deps/libcore.dylib
```
という、ビルド環境を反映した結果が返ってきます。これは自然ではないので修正します。
例えば `libonnxruntime.1.11.1.dylib` の場合、`otool -D libonnxruntime.1.11.1.dylib` で調べると
```
libonnxruntime.1.11.1.dylib:
@rpath/libonnxruntime.1.11.1.dylib
```
という結果となります。このように、配布する動的ライブラリの identification name は `@rpath/ファイル名` とするのが良さそうなので、このように設定しなおす処理を追加しました。
ref #128
> [Rust] macOS 向けの libcore.dylib の identification name を設定し直す

- .github/workflows/test.yml
- example/cpp/unix/.gitignore
- example/cpp/unix/CMakeLists.txt
- example/cpp/unix/README.md
- example/cpp/unix/simple_tts.cpp
example/cpp/unix/ を修正してRustで生成したバイナリが動作できるようにする
refs #128
> [Rust]C++ unix向けのexampleを修正する

- README.md
- onnxruntimeはcargo buildで自動ダウンロードされるためonnxruntimeのダウンロードに関する記載は削除
- 現状Raspberry Pi のビルドに対応できていないためRaspberry Pi に関連する記載を削除
- 現状DirectMLのビルドに対応できていないためDirectMLに関連する記載を削除
- ビルド・テスト手順をRust向けに変更
refs #128
> [Rust]Rust開発環境用のREADMEに更新する

- .github/workflows/build_and_deploy.yml
- crates/voicevox_core/build.rs
https://github.com/VOICEVOX/voicevox_core/pull/197#discussion_r928145616 によりRPATHがされていないとdynamiclink時にLD_LIBRARY_PATHの設定を行わないとlink errorになってしまうため
refs #128
> [Rust]RPATHの設定をした

- example/cpp/windows/README.md
- example/cpp/windows/simple_tts/packages.config
- example/cpp/windows/simple_tts/simple_tts.cpp
- example/cpp/windows/simple_tts/simple_tts.h
- example/cpp/windows/simple_tts/simple_tts.vcxproj
- example/cpp/windows/simple_tts/simple_tts.vcxproj.filters
rust版coreに対応するための修正をしました。
initialize関数に引数を追加しました。
initialize関数の返り値を見てfalseの場合にメッセージを表示するようにしました。
voicevox_error_result_to_message関数の返り値をワイド文字に変換してからコンソール画面に表示する関数OutErrorMessageを作成しました。
ref #128 
別でissueを出すべきだと思いますが、日本語を含むパスで動作しませんでした。
> [Rust]C++ Windows向けのexampleを修正します

- .github/workflows/build_and_deploy.yml
- .github/workflows/test.yml
- Cargo.lock
- crates/voicevox_core/Cargo.toml
directmlをサポートするためのPRです
refs #128 https://github.com/VOICEVOX/onnxruntime-rs/pull/1
https://github.com/VOICEVOX/onnxruntime-rs/pull/1 が mergeされてからreviewすること
以下の確認が必要
> directml用release buildを作成

- README.md
- crates/voicevox_core/src/internal.rs
Windowsでtestできなかったのでtest.ymlの行をコピーしました。
あと、エラーが起きる話者IDをわかりやすく異常値にしました。
- https://github.com/VOICEVOX/voicevox_core/issues/128
> [Rust] README追記、エラーが起きる話者IDを大きく

- Cargo.toml
削減できる量は少ないですがわりと簡単に設定できそうだったのでやってみました
before
```bash
> ls -lh libcore.so
-rwxrwxr-x 2 qwerty2501 qwerty2501 62M  8月  7 18:17 libcore.so
```
after
```bash
> ls -lh libcore.so
-rwxrwxr-x 2 qwerty2501 qwerty2501 57M  8月  7 18:26 libcore.so
```
> release buildのサイズが小さくなるようにした

- crates/voicevox_core/src/engine/mod.rs
- crates/voicevox_core/src/engine/synthesis_engine.rs
- crates/voicevox_core/src/internal.rs
- Re-export `OpenJtalk` in `crate::engine::synthesis_engine`
- Pass `OpenJtalk` as an argument
`OpenJtalk`を明示的に`SynthesisEngine::new`の引数として渡すようにします。
引数の順番は`inference_core`, `open_jtalk`の順にしました。
Closes #214.
> `OpenJtalk`を引数として渡す

- .github/workflows/build_and_deploy.yml
- .github/workflows/test.yml
- crates/voicevox_core/Cargo.toml
- crates/voicevox_core/build.rs
- Remove unnecessary `extern crate`
- Isolate the part for generating core.h
- Add `generate-c-header` feature and don't generate core.h by default
- Enable `generate-c-header` for CI
feature `generate-c-header`を追加し、これが有効なときのみcore.hを生成するようにしました。
Closes #215.
> core.hの生成をfeatureで制御する

- crates/voicevox_core/src/status.rs
恐らく これが linux GPU版でSIGSEGV発生してる原因になってるので修正する
https://github.com/VOICEVOX/voicevox_core/issues/227#issuecomment-1210170995
> with_disable_mem_pattern を削除(C++版ではなかったコードのため)

- crates/voicevox_core/src/c_export.rs
- crates/voicevox_core/src/engine/full_context_label.rs
- crates/voicevox_core/src/engine/kana_parser.rs
ついさっき[Rust 1.63がリリースされ](https://blog.rust-lang.org/2022/08/11/Rust-1.63.0.html)、Clippyに以下のlintが追加されたためにCIが落ちるようになってました。
- [`clippy::derive_partial_eq_without_eq`](https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq)
これに従いwarningが出る箇所に`#[derive(Eq)]`しました。
> CIを直すため`clippy::derive_partial_eq_without_eq`に従う

- crates/voicevox_core/src/internal.rs
以下の部分をちゃんと動くようにし、`use_gpu=true, load_all_models=true`で`initialize`を呼んでも動作するようにしました。
https://github.com/VOICEVOX/voicevox_core/blob/18dc02d0efd94b5076d494677b714565662b6c98/crates/voicevox_core/src/internal.rs#L203-L211
```console
❯ cd ./example/cpp/unix
❯ sed -i 's/\(initialize(\)false/\1true/' ./simple_tts.cpp
❯ cmake --build ./build && ORT_USE_CORE=1 cargo build && cp ../../../target/debug/libcore.so ./ && ./build/simple_tts あ
[ 50%] Building CXX object CMakeFiles/simple_tts.dir/simple_tts.cpp.o
[100%] Linking CXX executable simple_tts
[100%] Built target simple_tts
Compiling voicevox_core v0.1.0 (/home/ryo/src/github.com/VOICEVOX/voicevox_core/crates/voicevox_core)
Finished dev [unoptimized + debuginfo] target(s) in 3.63s
coreの初期化中...
openjtalk辞書の読み込み中...
音声生成中...
音声ファイル保存中... …
```
> `initialize`内の"一回走らせて十分なGPUメモリを確保させる"の部分を削除

- .cargo/config.toml
- .github/workflows/test.yml
- Cargo.lock
- README.md
- crates/voicevox_core/Cargo.toml
workaroundが自動化されるのでCIテスト、READMEのworkaround手順を削除
refs #213, https://github.com/VOICEVOX/onnxruntime-rs/pull/4,https://github.com/VOICEVOX/onnxruntime-rs/issues/3
経緯については https://github.com/VOICEVOX/onnxruntime-rs/pull/4 を参照
https://github.com/VOICEVOX/onnxruntime-rs/pull/4 がmergeされたのち、CIテストを再実行してからreviewすること
> Windows環境でテストエラーになるのを防ぐ処理を追加

- Cargo.lock
- crates/voicevox_core/Cargo.toml
cmakeでエラーになる問題を解決するため
https://github.com/VOICEVOX/open_jtalk-rs/pull/2 がmergeされてからreviewとCIテストすること
> 0.1.25にopen_jtalkをバージョンアップ

- .github/workflows/test.yml
恐らく onnxruntimeが depsにコピーされていないキャッシュが有効になってしまっているのが原因
> キャッシュが原因でWindows-2022のテストが失敗していたのでキャッシュキーを更新した

- Cargo.lock
- crates/voicevox_core/Cargo.toml
CIを復活させるため`onnxruntime`をアップデートし、次のライブラリもついでにアップデートしました。
- `dev-dependencies/rstest`: `0.12.0` → `0.15.0`
- `build-dependencies/cbindgen`: `0.23.0` → `0.24.3`
- その他minor/patchのアップデートがあるクレート
- [rstest](https://github.com/la10736/rstest/releases)
- [cbindgen](https://github.com/eqrion/cbindgen/releases)
> dependenciesをアップデート

- .github/workflows/test.yml
- crates/voicevox_core/Cargo.toml
- crates/voicevox_core/src/status.rs
`with_append_execution_provider_directml` の呼び出しが行われていなかったのが原因であると思われるため、呼び出しを行うようにした
~~https://github.com/VOICEVOX/onnxruntime-rs/pull/6 がmergeされないとreviewできない~~
できるようになった！
#213
> directmlでGPUが使えなかったことに対する対処

- crates/voicevox_core/src/engine/model.rs
#244 にて`AudioQueryModel`に`serde`をimplした際snake\_caseのフィールド名がすべてそのままだったため、エンジンが入出力するものとは異なる形式のJSONを入出力している状態になっています。
`accent_phrases`以外をlowerCamelCaseにリネームすることでエンジン側に合わせました。
> `AudioQueryModel`のser/deを修正

- crates/voicevox_core_c_api/build.rs
macOS の dylib に rpath として `@loader_path/` を追加しました。
以前のコメント https://github.com/VOICEVOX/voicevox_core/pull/203#discussion_r928189845 で、macOS の dylib について rpath の追加をしなくても良いということを言ったのですが、その後、ビルド済みのエンジンでは問題ないと思われるものの、ビルドしていない状態のエンジンで `--voicelib_dir` オプションでコアの場所を指定するユースケースでは特に rpath を追加した方が良いと感じました。
以前の CMake の設定を改めて確認すると `@loader_path/` を rpath として追加していたので、これと同様の設定を行いました。
https://github.com/VOICEVOX/voicevox_core/blob/7ff2e7f2ae7e635d2557e2a6114e31b8f8cf3ddd/core/CMakeLists.txt#L104-L109
ref #203
> macOS の dylib 向けに rpath を追加

- .github/workflows/test.yml
T/O
https://github.com/VOICEVOX/voicevox_core/pull/217#issuecomment-1222326918
> runner.osのUbuntu-18.04 がサポート切れていたので削除し、Ubuntu-22.04を新たに追加

- .github/workflows/test.yml
ビルド時にClangでbindコードを自動生成してたころの名残があったので消した
現在ではClangはビルド時には行っておらずテストを遅くするだけなので不要
> 不要になったCIステップを削除

- crates/voicevox_core/src/engine/kana_parser.rs
- crates/voicevox_core/src/engine/model.rs
- crates/voicevox_core/src/publish.rs
エンジンの `audio_query` の結果と比較して気づきましたが、コアの `VoicevoxCore::audio_query` 関数から返ってくる `AudioQuery` の `kana` フィールドが空文字列になっていました。エンジンでは `create_kana` で作られた AquesTalk 記法の文字列です。エンジンの以下の部分が対応するコードです。
https://github.com/VOICEVOX/voicevox_engine/blob/8057ee439767c9bfe14f323bb20f8391006d6bfd/run.py#L123-L146
エンジンと同じ挙動になるように変更を加えました。
ref #244
> audio_query 関数の返すクエリの初期値に create_kana の結果を格納

- crates/voicevox_core/src/engine/synthesis_engine.rs
https://github.com/VOICEVOX/voicevox_core/issues/213#issuecomment-1214026896 において句読点が無視されているように聞こえる問題が報告されていましたが、手元で確認したところ再現し、まだ直っていなかったことがわかりました。
原因を調査したところ、`pause_mora` の長さの設定でミスを犯していたことがわかりました（すみません……！）。本来は `vowel_length` を設定するべき数値を、`consonant_length` に設定していました（以下は C++ 版の同等の箇所。こちらの設定が正しいはずです）。
https://github.com/VOICEVOX/voicevox_core/blob/50082b69e535851a358647477bfc7b8512b43880/core/src/engine/synthesis_engine.cpp#L215-L220
これを修正したところ、句読点で音声が期待通りに区切れているように聞こえたので、修正されたと考えています。
ref #213
> 句読点の長さが適切に設定されていなかった問題を修正

- .github/workflows/build.yml
- CMakeLists.txt
#132 の影響で、0.12.1より新しいバージョンでLinux  armhf向けの製品版リリースがされておらず、以降にリリースされたキャラクターやスタイルをarmhf環境で利用できない状態にあったので、0.13.x向けのHotfixとしてPRを出します。
armhf向けのビルドの場合、リンカに`--long-plt`オプションを追加することで、製品版0.12.3以降のように埋め込みファイルが多い場合でもビルドできるようにしました。
以下のDocker BuildKit/QEMUを使ったarmhf (armv7l)エミュレーション環境で、デモモデル（`model/`のonnxモデル）によってexampleの`simple_tts`で正常に音声が生成されることを確認しました（ただし埋め込みファイル全体が正常なことをテストしているわけではない）。
- <https://github.com/aoirint/vvcore_simple_tts_armhf-docker/tree/68abca1141839bbfc52d210c0901f8e8f005f552>
- CMake 3.16以降を使用するためにUbuntu 20.04環境
- エミュレーションとCMake 3.16の相性のためか、1回目の`cmake -S . -B build`実行に失敗することのWorkaround入り
- デモモデルを使ったビルド成果物: <https://github.com/aoirint/voicevox_core/releases/tag/0.13.0-aoirint-1>
- close #132
> Hotfix: C++版のLinux armhf向けコアを製品版でビルドできるようにする

- README.md
READMEに追記しました。
close #242 
ドキュメントのURLなのですが、とりあえず↓にしてみました。
https://voicevox.github.io/voicevox_core/apis/c_api/globals_func.html
よりわかりやすい一覧ページがあればそちらにしたほうが良いかもです。
> APIドキュメントのリンクを追加

- docs/downloads/download.md
`--accelerator cuda`となるべき箇所が`--type cuda`のままなのを修正します。
> Fix download.md

- crates/voicevox_core/src/publish.rs
NOT_LOADED_OPENJTALK_DICT_ERRORのエラーメッセージを修正しました。
voicevox_load_openjtalk_dictはもう存在しません。
（なし）
（なし）
> Fix: NOT_LOADED_OPENJTALK_DICT_ERRORのメッセージを修正

- .cargo/config.toml
- .github/workflows/build_and_deploy.yml
- .github/workflows/generate_document.yml
- .github/workflows/test.yml
- Cargo.lock
- Cargo.toml
- README.md
- crates/voicevox_core_c_api/Cargo.toml
- crates/voicevox_core_c_api/build.rs
- crates/xtask/Cargo.toml
- crates/xtask/src/commands.rs
- crates/xtask/src/commands/generate_c_header.rs
- crates/xtask/src/main.rs
`cargo xtask generate-c-header`でvoicevox\_core.hを生成できるようにし、`voicevox_core_c_api/generate-c-header`を削除します。
Resolves #282.
`generate_document`については分単位の短縮になると考えられる
> cargo-xtaskでvoicevox_core.hを生成する

- .github/actions/cargo-binstall-cbindgen/action.yml
- .github/workflows/build_and_deploy.yml
- .github/workflows/generate_document.yml
- .github/workflows/test.yml
cargo-binstallでcbindgenをインストールする際、cargo-quickinstallでの再配布を明示的にダウンロード対象にすることでCIを直します。
> cbindgenのインストール時にcargo-quickinstallのリポジトリを明示的に指定する

- Cargo.lock
- crates/voicevox_core_c_api/Cargo.toml
- crates/voicevox_core_c_api/src/helpers.rs
- crates/voicevox_core_c_api/src/lib.rs
C API内でのエラー処理を`Result`中心のものにします。
Resolves #292.
> C API内でのエラー処理をRustらしくする

- crates/voicevox_core_c_api/src/helpers.rs
C APIではエラーが発生した場合、以下のようにエラー内容をstderrに出力します。
https://github.com/VOICEVOX/voicevox_core/blob/01c837195882dc32932e101d3e8e9db27d01b1bc/crates/voicevox_core_c_api/src/helpers.rs#L13-L16
```console
OpenJTalkの辞書が読み込まれていません
[crates/voicevox_core_c_api/src/helpers.rs:15] err = RustApi(
NotLoadedOpenjtalkDict,
)
```
これで十分な情報は出力されるのですが、`dbg!`はいわゆる「printデバッグ」に用いるものであり、ユーザーに向けたエラー表示に使うのは一般的ではないように思えます。
ref: [`clippy::dbg_macro`](https://rust-lang.github.io/rust-clippy/rust-1.64.0/index.html#dbg_macro)
(さらにこの`dbg!`で表示されるソースコード位置は`crates/voicevox_core_c_api/src/helpers.rs:15`で固定であり、役に立つ情報ではなくなっています)
このPRでは、エラーの出力を以下のような形式にします。
```console
Error(Display): OpenJTalkの辞書が読み込まれていません
Error(Debug): RustApi(
NotLoadedOpenjtalkDict,
)
```
> C APIにおけるエラー表示を改善

- crates/voicevox_core/src/engine/open_jtalk.rs
- crates/voicevox_core/src/error.rs
- crates/voicevox_core/src/status.rs
- crates/voicevox_core_c_api/src/lib.rs
`SourceError`を廃止し、`voicevox_core::Error`の`PartialEq`は手で実装します。
#297 における4.の選択肢を取りました。
Fixes #297.
> `SourceError`を廃止

- crates/voicevox_core/src/error.rs
`voicevox::Error::{InvalidSpeakerId, InvalidModelIndex}`の`Display`実装を変更しました。
```diff
========================================
-Display: 無効なspeaker_idです,無効なspeaker_idです
+Display: 無効なspeaker_idです: 999999
Debug: InvalidSpeakerId {
speaker_id: 999999,
}
========================================
-Display: 無効なmodel_indexです,無効なmodel_indexです
+Display: 無効なmodel_indexです: 999999
Debug: InvalidModelIndex {
model_index: 999999,
}
```
Fixes #302.
> `voicevox_core::Error`の`Display`実装を修正

- crates/voicevox_core/src/engine/synthesis_engine.rs
- crates/voicevox_core/src/status.rs
`SynthesisEngine`に対する不要な`unsafe impl Sync`を削除します ([`Sync`は`Mutex`が与えてくれる](https://doc.rust-lang.org/stable/std/sync/struct.Mutex.html#impl-Sync-for-Mutex%3CT%3E)ため)。
> 不要な`unsafe impl`を削除

- .github/workflows/build_and_deploy.yml
リリース時にwhlの名前をリネームします。
Maturin側でwhlの名付けをコントロールするのは面倒そうなので、whlの生成後にリネームするようにしました。
Fixes #304.
> Python APIだけlocal version segmentsを付ける

- .github/workflows/build_and_deploy.yml
mainブランチへのPRです（<https://github.com/VOICEVOX/voicevox_core/pull/311#pullrequestreview-1150911192>）。
`svenstaro/upload-release-action@v2`で自動作成されたリリースに紐づくtagが、メインブランチの最新コミットを指してしまう問題を修正し、CIが実行されたコミットを指すようにします。
tagのコミットIDを指定（`target_commitish: ${{ github.sha }}`）できる、`softprops/action-gh-release@v1`を使用するように変更しました。
- 動作確認: <https://github.com/aoirint/voicevox_core/actions/runs/3298041031>
- 自動作成されたリリース: <https://github.com/aoirint/voicevox_core/releases/tag/0.13.0-aoirint.8>
- ref <https://github.com/VOICEVOX/voicevox/issues/904>
- ref <https://github.com/VOICEVOX/voicevox_engine/pull/489>
- ref <https://github.com/VOICEVOX/voicevox/pull/985>
- ref <https://github.com/VOICEVOX/voicevox_core/pull/311>
> CI: 自動作成されるリリースのタグの場所を正しくする

- .github/workflows/build.yml
`svenstaro/upload-release-action@v2`で自動作成されたリリースに紐づくtagが、メインブランチの最新コミットを指してしまう問題を修正し、CIが実行されたコミットを指すようにします。
tagのコミットIDを指定（`target_commitish: ${{ github.sha }}`）できる、`softprops/action-gh-release@v1`を使用するように変更しました。
既存の誤ったタグはPRでは張り替えられないと思うので、そちらはそのままになります（コード署名が導入されてからのリリースが該当）。
- <https://github.com/aoirint/voicevox_core/actions/runs/3265943698> 
- <https://github.com/aoirint/voicevox_core/actions/runs/3266032425>
- デフォルトブランチに`workflow_dispatch`のWorkflowがないと、Run workflowボタンが現れないので、手元のforkでは一時的にデフォルトブランチをこのPRのブランチにしています
- このPRのブランチから、1コミット追加した別のブランチを生やし、Run workflowボタンの`Use workflow from`で使用しています
- 自動作成されたリリースは、デフォルトブランチの最新コミットではなく、1コミット進んだもの（CIが実行されたコミット）を指すように修正されていることが確認できます
- https://github.com/aoirint/voicevox_core/releases/tag/0.13.0-aoirint.6
GitHub Actionsでは、2022年4月にサポート終了したNode …
> Hotfix: CI: 自動作成されるリリースのタグの場所を正しくする

- .github/actions/rust-toolchain-from-file/action.yml
- .github/workflows/build_and_deploy.yml
- .github/workflows/test.yml
- .github/workflows/update_rust_toolchain.yml
このリポジトリで使っているactions-rs/toolchainをdtolnay/rust-toolchainに置き換えます。
Resolves #312.
> actions-rs/toolchainからdtolnay/rust-toolchainに切り替える

- .github/workflows/build_and_deploy.yml
C API の配布物内に Python API 向けの共有ライブラリ（例えば Linux では `libvoicevox_core_python_api.so`）が含まれてしまっていました（ #315 のテストリリース https://github.com/aoirint/voicevox_core/releases/tag/0.13.0-aoirint.8 の結果を見て気づきました。Python API 向けの共有ライブラリができている理由は、`voicevox_core_python_api` クレートの crate-type が cdylib だからと考えられます）。
```
voicevox_core-linux-x64-cpu-0.13.0-aoirint.8 $ ls
README.txt			libonnxruntime.so.1.11.1	libvoicevox_core_python_api.so <- これです
VERSION				libvoicevox_core.so		voicevox_core.h
```
これは意図的な同梱ではないはずなので、C API の共有ライブラリ（Linux の場合 `libvoicevox_core.so`）のみをコピーするように修正しました。
ref #315
> fix: Python API の共有ライブラリが C API の配布物に含まれないようにする

- .github/workflows/build_and_deploy.yml
`echo "::set-output name={key}::{value}"`というやりかたが[deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)になっており、Actionsの画面で警告も出ているため新しい方法に切り替えます。
> `set-output`から`>> "$GITHUB_OUTPUT"`に切り替える

- .github/workflows/build_and_deploy.yml
- .github/workflows/test.yml
ActionsでのCargoコマンドに`-vv` (`--verbose --verbose`)を付けることで、 #322 のようなことをするときに何が起きているかわかりやすくします。
> ActionsのCargoコマンドに`-vv`を付ける

- .github/workflows/build_and_deploy.yml
build_and_deploy.ymlにある`-latest`の指定を以下の通りに変更します。
- `windows-latest` → `windows-2019`
- `macos-latest` → `macos-11`
- `ubuntu-latest` → `ubuntu-20.04`
https://github.com/VOICEVOX/voicevox_engine/pull/510
> `latest`を指定するのをやめる

- README.md
- docs/downloads/download.md
~~`find -name '*.md' -exec sed -i 's/curl -sSL/curl-sSfL/' {} +`~~
`find -name '*.md' | xargs sed -i 's/curl -sSL/curl -sSfL/'`します。 (スペース入れ忘れてました)
before:
```console
❯ curl -sSL https://github.com/VOICEVOX/voicevox_core/releases/latest/download/download.sh
Not Found%
❯ echo "$?"
0
```
after:
```console
❯ curl -sSfL https://github.com/VOICEVOX/voicevox_core/releases/latest/download/download.sh
curl: (22) The requested URL returned error: 404
❯ echo "$?"
22
```
https://github.com/VOICEVOX/voicevox_core/issues/330
ダウンロードスクリプトとかには既にちゃんと`-f`が付いていました。
> Markdownドキュメントにある`curl`に`-f`を付ける

- .github/workflows/cargo-deny.yml
リリース時を除き、cargo-denyのエラーを警告に引き下げます。
https://github.com/VOICEVOX/voicevox_core/issues/333#issuecomment-1329234334
> リリース時以外はcargo-denyの`denied`を`warnings`に引き下げる

- .github/workflows/download_test.yml
- scripts/downloads/download.ps1
- scripts/downloads/download.sh
[エンジンデプロイ時にcoreのダウンロードスクリプトを使用するようにする](https://github.com/VOICEVOX/voicevox_engine/issues/514)  ためCPUアーキテクチャを指定してダウンロードスクリプトを実行できるように修正した
refs https://github.com/VOICEVOX/voicevox_engine/issues/514
> CPUアーキテクチャを指定してダウンロードできるように修正

- .github/workflows/psscriptanalyzer.yml
~~#334~~ #343 でこれを忘れていたため、`main`ブランチでworkflowが作動していません。
(それでもdownload.ps1を更新すれば動くと思いますが)
~~#334~~ #343
> `psscriptanalyzer`の起動条件にworkflow file自体の変更を加える

- .cargo/config.toml
- .github/workflows/build_and_deploy.yml
- crates/voicevox_core/Cargo.toml
Linux arm64用のビルドを作成します．
変更点
* 依存モジュールを更新
* CI設定を変更
* ```aarch64-unknown-linux-gnu```用にリンカ設定を追加
[手元のCI](https://github.com/haru3me/voicevox_core/actions)ではビルドが通りました．
よろしくお願いします．
> linux-arm64-cpu用ビルドの追加

- crates/voicevox_core_c_api/src/helpers.rs
- crates/voicevox_core_c_api/src/lib.rs
C APIにnull pointerの`open_jtalk_dict_dir`が与えられたとき、それをRustの`None::<PathBuf>`に変換します。
現在新C APIの`voicevox_initialize`を実行するとき、`VoicevoxInitializeOptions`がデフォルトのままだとnull pointer accessが起きます。
#217 のときからずっとこうだったようです。
<details>
<summary>再現コード</summary>
```rust
#!/usr/bin/env rust-script
//! ```cargo
//! [dependencies]
//! clap = { version = "4.0.32", features = ["derive"] }
//! duplicate = "0.4.1"
//! eyre = "0.6.8"
//! libloading = "0.7.4"
//! ```
use std::{ffi::c_char, path::PathBuf};
use clap::Parser as _;
use duplicate::duplicate;
use libloading::Library;
#[derive(clap::Parser)]
struct Args {
dll: PathBuf,
}
fn main() -> eyre::Result<()> {
let Args { dll } = Args::parse();
unsafe {
let dll = Library::new(dll)?;
duplicate! {
[
symbol_name                                  T;
[ …
```
> null pointerの`open_jtalk_dict_dir`を`None`と解釈する

- .github/workflows/test.yml
Cargo.lockの内容がCargo.tomlに合っていないとき、CargoはCargo.lockを可能な限り自動で修正します。例えばCargo.tomlのonnxruntime-rsやopen_jtalk-rsのバージョンだけ上げてCargo.lockを更新せずにPRを出したときCIは通るのですが、そのまま`main`にマージされてしまうと、手元で何かするたびにCargo.lockのdiffが発生することになります。
そこでそのような自動修正が必要なCargo.lockに対してエラーを発するようにします。実害は少ないとはいえ結構頻繁に発生しうると思ったので。
> 自動修正が必要なCargo.lockを弾く

- model/metas.json
[エンジン側のダミー](https://github.com/VOICEVOX/voicevox_engine/blob/755b9767d2c4d82f5284ec2526ab268eca15ff26/speaker_info/388f246b-8c41-4ac1-8e2d-5d79f3ff56d9/metas.json)を真似てみました。
- https://github.com/VOICEVOX/voicevox_core/issues/358#issuecomment-1368630053
> metas.jsonの中身をダミーだとわかりやすいようにする

- Cargo.lock
- Cargo.toml
- crates/voicevox_core/Cargo.toml
- crates/voicevox_core/src/engine/synthesis_engine.rs
- crates/voicevox_core/src/lib.rs
- crates/voicevox_core/src/numerics.rs
- crates/voicevox_core_python_api/Cargo.toml
`voicevox_core::engine`下で`f32`を[四捨五入](https://doc.rust-lang.org/stable/std/primitive.f32.html#method.round)している箇所を、偶数丸めになるように修正します。
- https://github.com/VOICEVOX/voicevox_engine/issues/552
- https://github.com/SHAREVOX/sharevox_core/commit/d647593df8a459a6579f731e89497ea774c157ac
> `voicevox_core::engine`下では偶数丸めで`round`するようにする

- crates/voicevox_core_c_api/src/lib.rs
`$RUST_LOG`がセットされていないときに、適切なデフォルト設定を使うようにします。
#338 の時点ではエディタ側で`$RUST_LOG`を設定して運用する方針になると考えていたのですが、それだと面倒だと思いました。
この変更により`$RUST_LOG`は「ロガーのデフォルト設定を上書きする」という役割になります。ログを一切出したくないときは`RUST_LOG=off`とすればよいです (`RUST_LOG=''`だと`RUST_LOG=error`と同じになります)。
> `$RUST_LOG`がセットされていないときのデフォルト設定を用意する

- Cargo.lock
- Cargo.toml
- crates/voicevox_core/Cargo.toml
- crates/voicevox_core/src/publish.rs
- crates/voicevox_core_python_api/Cargo.toml
Windows上でのみ、GPUの情報を`INFO`のレベルで流すようにします。
```console
> cargo run -q -- .\voicevox_core.dll
[src\main.rs:28] NvOptimusEnablement = 0
2022-12-30T19:45:58.937549Z  INFO voicevox_core::publish: 利用可能なGPU (DirectMLには1番目のGPUが使われます):
2022-12-30T19:45:58.945828Z  INFO voicevox_core::publish:   - "AMD Radeon(TM) Graphics" (495.77 MiB)
2022-12-30T19:45:58.945901Z  INFO voicevox_core::publish:   - "NVIDIA GeForce RTX 3070 Laptop GPU" (7.86 GiB)
2022-12-30T19:45:58.945940Z  INFO voicevox_core::publish:   - "Microsoft Basic Render Driver" (0 B)
```
```console
> cargo run -q --features optimus-enablement -- .\voicevox_core.dll
[src\main.rs:28] NvOptimusEnablement = 1
2022-12-30T19:46:16.355579Z  INFO voicevox_core::publish: 利用可能なGPU (DirectMLには1番目のGPUが使われます):
2022-12-30T19:46:16.363935Z  INFO …
```
> Windows上ではGPUの情報を出すようにする

- build_util/codesign.bash
`-v`は後ろで指定した変数名の変数が定義されているかどうか判別するもので、「`-v "${CERT_BASE64}"`は`$CERT_BASE64`の中身の値と同じ名前の変数名が定義されてるか」という意味になっていました。
上の`set -e`で「未定義の変数を使ったときはエラー」になっていたので、偶然止まっている感じでした。
> bashで-vの使い方を間違えていたので修正

- .github/workflows/build_and_deploy.yml
このままだとartifactディレクトリがrootになってしまうので修正。
ついでに7zコマンドはたしか全OSで使えるはずなので統一してみました。
- https://github.com/VOICEVOX/voicevox_core/pull/372
> 7zコマンドが間違っていたので修正

- README.md
タイトル通り。
（なし）
サンプルと同じことをするコードを [sevenc-nanashi/voicevox.rb:examples/cli.rb](https://github.com/sevenc-nanashi/voicevox.rb/blob/main/examples/cli.rb) で実装しています。こちらも追記するべきでしょうか？
> Add: 事例紹介にvoicevox.rbを追加

- .github/workflows/build_and_deploy.yml
- scripts/downloads/download.sh
`osx-aarch64-cpu`を`osx-arm64-cpu`に改名します。
Fixes #393.
Node.js的には`windows`も`win32`で`osx`も`darwin`なのでは?と思わなくもないですが、そこまでやる必要は無さそう?やるとしたら今をおいて他にないと思いますが...
> `osx-aarch64-cpu`を`osx-arm64-cpu`に改名する

- .github/workflows/download_test.yml
- crates/download/src/main.rs
- docs/downloads/download.md
- scripts/downloads/download.ps1
- scripts/downloads/download.sh
```diff
Usage: download [OPTIONS]
Options:
--min
ダウンロードするライブラリを最小限にするように指定
-o, --output <OUTPUT>
出力先の指定 [default: ./voicevox_core]
-v, --version <VERSION>
ダウンロードするvoicevox_coreのバージョンの指定 [default: latest]
--additional-libraries-version <ADDITIONAL_LIBRARIES_VERSION>
追加でダウンロードするライブラリのバージョン [default: latest]
-      --accelerator <ACCELERATOR>
-          ダウンロードするacceleratorを指定する(cudaはlinuxのみ) [default: cpu] [possible values: cpu, cuda, directml]
+      --device <DEVICE>
+          ダウンロードするデバイスを指定する(cudaはlinuxのみ) [default: cpu] [possible values: cpu, cuda, directml]
--cpu-arch <CPU_ARCH>
ダウンロードするcpuのアーキテクチャを指定する [default: x64] [possible values: x86, x64, arm64]
--os <OS>
ダウンロードする対象のOSを指定する [default: linux] [possible values: windows, linux, osx]
-h, --help
Print help information
```
```diff …
```
> `--accelerator`を`--device`に

- crates/voicevox_core/src/publish.rs
`VoicevoxCore::audio_query` メソッドを `kana` オプションを `true` に設定した状態で使用すると、`parse_kana` 関数で生成された `accent_phrases` に対して `predict_duration` および `predict_intonataion` を用いないようになっており、子音・母音の長さ等が未設定のまま（デフォルト値の 0 等のまま）出力されていました。
（これにより、この `audio_query` メソッドを呼び出している `VoicevoxCore::tts` メソッドにも影響があり、無音の wav が生成される結果となっていました。）
エンジンの Python コードには以下のような部分があり、これを参考に、`SynthesisEngine::replace_mora_data` メソッドに `parse_kana` で生成された `accent_phrases` を適用して、推論結果が反映された適切な `accent_phrases` を得られるようにしました。
https://github.com/VOICEVOX/voicevox_engine/blob/2c4f52a9ec80cda5936edecccc4c2aabd14a78f7/run.py#L303-L315
close #405
> fix: `audio_query` 関数で `kana` オプションを `true` に設定したときに適切な `accent_phrases` を得られるようにする

- crates/voicevox_core_python_api/python/voicevox_core/__init__.py
以下コメントの課題を解決します。
(`__all__`が駄目と書いたのは、間違えて名前の文字列ではなくてアイテムの実体を突っ込んでいたからでした)
<https://github.com/VOICEVOX/voicevox_core/pull/404#issuecomment-1410390009>
おそらく多くの人がPylanceを使っていると思うので、warningどころかerrorが出るのはそこそこ大きな問題なのではないかと思ってます。
> __init__.pyに`__all__`を追加

- scripts/downloads/download.sh
latestに紐付いているタグの出し方をHTTPヘッダから取らないように変更
#378
> 最新のタグのだしかたの改善

- .github/workflows/update_rust_toolchain.yml
update\_rust\_toolchainをforkしたリポジトリ上で動かないようにします。
SHAREVOXのようなプロジェクトを除けばそんなに困るものではありませんが、fork上で動作させる理由も得に無さそうに思えます。
- #233
- [SHAREVOX_CORE/sharevox_core#29](https://github.com/SHAREVOX/sharevox_core/pull/29)
参考: <https://grep.app/search?q=if%3A%20%28%5C%24%7B%7B%29%3F%20github.repository_owner%20%3D%3D%20%27&regexp=true&case=true&filter[lang][0]=YAML>
> fork上での`update_rust_toolchain`を停止する

- README.md
- docs/downloads/download.md
ダウンローダーをスクリプト版からrust版を使うようドキュメントを変更しました。
linux/macではどれ使うという問題は残っていますが…
ref #433
> ダウンローダーをスクリプト版からrust版を使うよう案内

- .cargo/config.toml
- .github/workflows/build_and_deploy.yml
- Cargo.lock
- crates/voicevox_core/Cargo.toml
Android arm64 でのC API ビルドを可能にします。
cargo build -p voicevox_core_c_api --target aarch64-linux-android 
Closes #437
> Android (arm64) 向けビルドの追加

- .github/workflows/build_and_deploy.yml
whl名が無いため`line 2: syntax error near unexpected token `;'`というエラーになります。
Android版はPython wheelが不要なので、通らないようにします。
> android版のビルドが通らない問題の解決（line 2: syntax error near unexpected token `;'）

- Cargo.lock
- crates/download/Cargo.toml
- deny.toml
<https://github.com/XAMPPRocky/octocrab/pull/296>が含まれたoctocrab v0.19.0が出たのでそちらに切り替えます。
`git`指定のdependencyは`cargo upgrade`の対象にならないため、やらないと忘れる類かと思うのでこうして単体でPRを出しておきます。
- #375
> octocrabを更新

- README.md
READMEにDiscordへの案内などを追加します。
またエディタとエンジンには書いてあった貢献者の方にお願いしたい流れを書けてなかったので書き足しました。
- https://github.com/VOICEVOX/voicevox/pull/1283
> READMEにDiscordへの案内などを追加

- .github/workflows/build_and_deploy.yml
- Cargo.lock
- Cargo.toml
- crates/voicevox_core/Cargo.toml
- crates/voicevox_core_c_api/build.rs
iOSの各アーキテクチャに対応します。
* Intel MacのiPhoneシミュレータ
* Apple Silicon MacのiPhoneシミュレータ
* iPhone
close #459 
process_pathについては、 https://github.com/wesleywiser/process_path/pull/16 が残念ながらMergeされる見込みが立たなかったため、 [VOICEVOX/process_path](https://github.com/VOICEVOX/process_path) へ移行しました。
> Add iOS support

- .cargo/config.toml
- .github/workflows/build_and_deploy.yml
- Cargo.lock
- crates/voicevox_core/Cargo.toml
タイトル通り。
- ref: voicevox/voicevox_project#10
> Add: x86_64-linux-androidを追加

- crates/voicevox_core_c_api/src/helpers.rs
- crates/voicevox_core_c_api/src/lib.rs
#392 で入った内容に対して、次の5つの変更を行います。変更はこれらの名前そのままの5つのコミットに分割してあります。
- `CStr`の長さは記憶しない
rust-lang/regexのC向けAPIである[rure](https://crates.io/crates/rure)の実装を参考にして、`CString`の長さはこちらでは記録しないようにしました。
- 余剰`capacity`は貸し出す前に削る
`Vec::into_boxed_slice`は余剰capacityをちゃんと消し飛ばしてくれることがわかっているため、余剰`capacity`は記憶しないようにします。
`T: Copy`を要求すれば`T: !Drop`が保証されるため、[`Layout`](https://doc.rust-lang.org/stable/std/alloc/struct.Layout.html)を保存してデアロケートに使うことにしました。
- パニックのメッセージを変更
`"すでに値が入っている状態はおかしい"`はともかく`"管理されていないポインタを渡した"`は実際にエラーメッセージとして機能する可能性があるので、ユーザー向けのメッセージにしました。
- 簡単なテストを追加する
soundnessを確認するテストは書けませんが、とりあえず一通り動作だけさせるものを追加しておきました。
(追記) 管理下にないポインタを入れるとパニックしてメッセージを出すものも追加しておきました。
- privateなrustdocはrustdocのスタイルで書く
Doxygen用でもないprivateな純粋なrustdocは、rustdocのスタイルに合わせるようにしました。
- #392
> Fix up #392

- crates/voicevox_core_python_api/python/voicevox_core/_rust.pyi
- crates/voicevox_core_python_api/src/lib.rs
タイトル通り。
- closes: #480
Rustは勉強中なので非効率的な書き方かも知れません。
<details>
<summary>サンプル</summary>
```py
import ctypes
import os
from pprint import pprint
ctypes.cdll.LoadLibrary(
"/home/sevenc7c/onnxruntime-linux-x64-1.14.0/lib/libonnxruntime.so.1.14.0"
)
os.environ["VV_MODELS_ROOT_DIR"] = "/home/sevenc7c/voicevox/core/model"
import voicevox_core
c = voicevox_core.VoicevoxCore(
open_jtalk_dict_dir="/home/sevenc7c/open_jtalk_dic_utf_8-1.11"
)
c.load_model(0)
base_phrases = c.accent_phrases("もち", 0)
pprint(base_phrases)
length_replaced = c.mora_length(base_phrases, 1)
pprint(length_replaced)
pitch_replaced = c.mora_pitch(base_phrases, 1)
pprint(pitch_replaced)
data_replaced = c.mora_data(base_phrases, 1)
pprint(data_replaced)
```
```
❯ python3 __gi_test.py 
[AccentPhrase(moras=[Mora(text='モ', …
```
> Add: #479 のPython APIを追加

- crates/voicevox_core/src/engine/model.rs
`#[serde(default)]`を入れて、ENGINEでは省略可能なフィールドを省略できるようにします。
- <https://github.com/VOICEVOX/voicevox_mobile/pull/19#discussion_r1187462625>
> `#[serde(default)]`を入れる

- crates/voicevox_core/src/engine/model.rs
- crates/voicevox_core/src/publish.rs
#486 においてcommit suggestionを押した後CIを待たずにマージした結果、ビルドが通らない状態になっているため直します。
- #486
Rustの`Option<T>`はPythonやTSのような合併型 (union type)ではなく、直和型 (sum type) (a.k.a. ADT, tagged union)と言えるものです。`T`は`Option<T>`のサブタイプではないため、値を書くときは`None`ではない場合も`Some(…)`と書く必要があります。
> Fix up #486

- README.md
README.mdの事例紹介の項に拙作[voicevoxcore.go](https://github.com/sh1ma/voicevoxcore.go)を追加しました。
特にありません。
特にありません。
> Docs: 事例紹介にvoicevoxcore.goを追加

- crates/voicevox_core/src/metas.rs
- crates/voicevox_core/src/voice_model.rs
- crates/voicevox_core/src/voice_synthesizer.rs
- crates/voicevox_core_c_api/include/voicevox_core.h
- crates/voicevox_core_c_api/src/lib.rs
- crates/voicevox_core_python_api/src/lib.rs
次の表記ゆれを統一します。
- "VoiceSynthesizer" → "Synthesizer" (`Synthesizer`/`VoicevoxSynthesizer`のはずなので)
- "音声合成モデル" → "音声モデル"
- #497
- <https://github.com/VOICEVOX/voicevox_core/pull/370#discussion_r1141398754>
- <https://github.com/VOICEVOX/voicevox_core/pull/370#discussion_r1141399252>
> [project-vvm-async-api] ドキュメントの表記ゆれを解消

- crates/voicevox_core_c_api/src/lib.rs
- crates/voicevox_core_python_api/src/lib.rs
C APIとPython APIが出す"version"を、Rust APIのものではなく各クレート自体のものにします。
<https://github.com/VOICEVOX/voicevox_core/pull/503#discussion_r1213507143>
今までPython APIではパッケージのバージョンが`0.14.4+cpu`であるにもかかわらず`__version__`が`"0.14.4"`になっていたという問題もあったので、それも理由です。
> [project-vvm-async-api] C/Python APIクレート側のバージョンを出す

- .github/workflows/build_and_deploy.yml
- Cargo.toml
Python APIを`panic=unwind`でビルドすることにより、ユーザー環境で万が一パニックが発生した際の挙動を「プロセスのabort」ではなく「例外の発生」に変えます。
C APIおよびPython APIでは現在(#218 によって)[パニック](https://doc.rust-jp.rs/book-ja/ch09-01-unrecoverable-errors-with-panic.html)発生時の動作がデフォルトの`panic=unwind`から`panic=abort`、すなわち「問答無用でのプロセスの強制終了」となっています。
提供するのがC APIのみならこれはバイナリサイズ縮小の効果しかありませんでした。なぜならパニックはそもそも[`extern "C"`の境界を越えられない](https://doc.rust-lang.org/nomicon/ffi.html#ffi-and-unwinding)からです(リンク先の`extern "C-unwind"`は[まだnightly-onlyです](https://github.com/rust-lang/rust/issues/74990))。
(なので<https://github.com/sh1ma/voicevoxcore.go/issues/5>のようなことはおそらく不可能です)
しかしPyO3であれば話は別です。PyO3はRustのパニックを`pyo3_runtime.PanicException`というC Pythonの例外に変換してくれます。[例外はCPythonのAPIを通じて外に出る](https://github.com/python/cpython/blob/3.12/Doc/c-api/exceptions.rst)ため、DLLの壁を越えることができます。 …
> Python APIでは`panic=unwind`にする

- crates/voicevox_core_c_api/include/voicevox_core.h
- crates/voicevox_core_c_api/src/c_impls.rs
- crates/voicevox_core_c_api/src/lib.rs
現在project-vvm-async-apiでは`VoicevoxSynthesizer`などの型はZST(**Z**ero **S**ized **T**ype)として.hに載せ、Rust側ではポインタのキャストを行っているという状態になっています。これをやめ、[repr(Rust)](https://doc.rust-lang.org/nomicon/repr-rust.html)にしてポインタのキャストをやめます。
さらにこれによりC側に提供される型は正しくopaqueになり、
```diff
-typedef struct VoicevoxSynthesizer {
-
-} VoicevoxSynthesizer;
+typedef struct VoicevoxSynthesizer VoicevoxSynthesizer;
```
次のコードのコンパイルは拒否されるようになります。
```c
sizeof(VoicevoxSynthesizer)
```
```c++
std::alignment_of<VoicevoxSynthesizer>()
```
```c
VoicevoxSynthesizer *ptr;
++ptr;
```
以下はこのPRを作るのを決断した理由です:
- ZSTにポインタキャストするのはC→Rustのときでは?
そもそもqwertyさんが何故ZSTにわざわざポインタのキャストをしていたのですが、Rustでは**Cの型をRustに**持って来るときに[1861-extern-types](https://rust-lang.github.io/rfcs/1861-extern-types.html)の代用としてZSTを使うという慣習があり、私が思うにおそらくそれに則ったのではないでしょうか。 …
> [project-vvm-async-api] ZSTにポインタキャストして提供するのをやめる

- Cargo.lock
- Cargo.toml
- crates/test_util/Cargo.toml
- crates/test_util/src/lib.rs
- crates/voicevox_core/Cargo.toml
- crates/voicevox_core/src/test_util.rs
project-vvm-async-apiにそろそろmainをマージしようと思ったのですが、こっちではこのままだと #508 が適用できないことに気付きました。
このPRはvoicevox\_coreクレート内で`$OUT_DIR`を使っているテストユーティリティを、test\_utilクレートに移動します。
#497
> [project-vvm-async-api] `$OUT_DIR`を使うものをtest_utilクレートに移動

- .github/workflows/download_test.yml
github actionsのwindows-2022が更新されたらしく、なぜか最新バージョンのgetができなくなったので対応です。
- https://github.com/VOICEVOX/voicevox_core/actions/runs/5179482508/jobs/9445000743
github cliのを使うようにしてみました。
原因は不明ですがとりあえず詳細メモ。
- https://github.com/VOICEVOX/voicevox_core/pull/516#issuecomment-1585751707
以前のと比較すると`Runner Image`が`Version: 20230606.1`になってました（以前のは`Version: 20230517.1`）
`Chocolatey`のメジャーバージョンアップ･･･？
```bash
diff \
<(curl https://raw.githubusercontent.com/actions/runner-images/win22/20230517.1/images/win/Windows2022-Readme.md) \
<(curl https://raw.githubusercontent.com/actions/runner-images/win22/20230606.1/images/win/Windows2022-Readme.md)
```
<details>
<summary>diff</summary>
```diff
3c3,5
< | [python2.7 will be removed from the images on May 22, 2023](https://github.com/actions/runner-images/issues/7401) | …
```
> windows-latestでなぜかdownload_testが落ちるのを改修

- crates/voicevox_core_c_api/cbindgen.toml
- crates/voicevox_core_c_api/include/voicevox_core.h
<https://github.com/VOICEVOX/voicevox_core/blob/5de8ddf705ef907ef1799a277e391a4c4bbee096/crates/voicevox_core_c_api/include/voicevox_core.h#L192-L201>
この空行を消します。
```diff
/**
* 初期化する
* @param [in] options 初期化オプション
* @return 結果コード #VoicevoxResultCode
*/
#ifdef _WIN32
__declspec(dllimport)
#endif
-
VoicevoxResultCode voicevox_initialize(struct VoicevoxInitializeOptions options);
```
Rustの最初の実装 (#126)からずっとこうだったようですが、この部分について何か議論した跡も無さそうなので、この空行はない方が視認性が高いかなと思いPRを出しておきます。
> cbindgenに`fn.args=vertical`を設定し、`__declspec`の後の空行を消す

- crates/voicevox_core_c_api/src/helpers.rs
- crates/voicevox_core_c_api/src/lib.rs
<https://github.com/VOICEVOX/voicevox_core/pull/516#discussion_r1225373597>のやつです。
使わなくなった`memorize_static_str`を削除して代わりに定数である`voicevox_version`のみに反応するようにする、というのを元々考えていました。
ただよく考えたら定数をfreeしようとする人は多分いないし、 あと #500 のときに忘れていたけど`voicevox_error_result_to_message`に対して`memorize_static_str`の出番があるはず、ということでこのようになりました。
- #500
- #497
このPRはmainの方に出すべきかもしれませんが、またマージするのも面倒だろうしこっちでいいかなと思いました。
> [project-vvm-async-api] Fix up #500

- .github/workflows/build_and_deploy.yml
- .github/workflows/cargo-deny.yml
- .github/workflows/download_test.yml
- .github/workflows/generate_document.yml
- .github/workflows/labeler.yml
- .github/workflows/psscriptanalyzer.yml
- .github/workflows/test.yml
- .github/workflows/typos.yml
- .github/workflows/update_rust_toolchain.yml
shell: bashを不要にできるオプションがあったので指定してみました。
とりあえずubuntu以外でのOSで実行していたworkflowにのみ付けています。
https://docs.github.com/ja/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun
2023/06/19 14:30追記
shell: bashを付けるか付けないかでubuntu/mac上の挙動が変わり、かつ付けたときのほうが良さそうなので全部に付けました。
> Github Actionsでshell: bashを毎回書かなくても良いようにする

- .github/workflows/build_and_deploy.yml
project-s用のfat_resourceと秘匿コードを使って製品版のモデルを使用可能にします。
https://github.com/VOICEVOX/voicevox_fat_resource/releases/tag/0.15.0-projects.0
ローカルでビルドした結果はこちらです
https://github.com/Hiroshiba/voicevox_core/releases/tag/0.15.0-checkprojects.1
- https://github.com/VOICEVOX/voicevox_project/issues/15
マージしてビルドしてみます。
> [project-s] project-s用のモデルを可能に

- crates/voicevox_core_c_api/src/lib.rs
- crates/voicevox_core_c_api/src/slice_owner.rs
C APIにおける`output_`系のポインタがunalignedであることを許可します。
Rustの[**参照** (_reference_)](https://doc.rust-lang.org/stable/std/primitive.reference.html)は**有効** (_valid_)であると同時に**アラインメントに沿って** (_aligned_)いなければなりません。そうでなければRustにおける**未定義動作** (_undefined behavior_)となります。そのためC側から渡される**生ポインタ** (_raw pointer_)を参照として解釈するときは、アラインメントにも注意する必要があります。
Cの`const VoicevoxSynthesizer*`を`&VoicevoxSynthesizer`として、`VoicevoxSynthesizer*`を`Box<VoicevoxSynthesizer>`として解釈するのにはアラインメント的な問題はありません。何故なら`VoicevoxSynthesizer`を作れるのはVOICEVOX COREだけであり、ユーザーは`VoicevoxSynthesizer`の実体に触れないようになっているため、「有効な`VoicevoxSynthesizer`のポインタ」がRustの世界で生まれたalignedなものであると言えるからです。また`const char*`を`&CStr`として読むときもアラインメントを気にする必要はありません。`c_char`は1バイトだからです。
しかしオブジェクトを"new"したり"create"したりする先の`T**`/`*mut *mut T`は別です。ドキュメントを通じてユーザーにお願いしない限り、`(T*)*`としてのアラインメントに沿わない …
> [project-vvm-async-api] `output_`系引数がunalignedであることを許す

- crates/voicevox_core_c_api/src/slice_owner.rs
#534 で、`write_unaligned`を間違えて`write_volatile`にしていた箇所があったので修正します。
(補完に出たのをそのまま打ってしまいました)
- #497
- #534
> [project-vvm-async-api] Fix up #534

- .github/workflows/test.yml
テスト時間を減らすためのプルリクエストです。
endtoendテストだけは全OSで行って、単体テストは単一のOSのみで行うようにしてみました。
テスト指定方法はこちらのコメントを参考にさせていただきました。
https://github.com/rust-lang/cargo/issues/10491#issuecomment-1074078912
- https://github.com/VOICEVOX/voicevox_core/pull/382
長いのはendtoendテストな気がするし、あまりあまり意味がないかも･･･。
> e2e系テストだけOS多めで、単体テストは１つのOSで

- .github/workflows/build_and_deploy.yml
- .github/workflows/test.yml
- https://github.com/VOICEVOX/voicevox_core/issues/373
の一環です。
プッシュするたびにかなり多くの環境と条件でビルドタスクが回っていて、その影響でテストがすごく時間かかっていました。
このプルリクエストでは簡易テストという概念を導入し、各OSにつき1つだけビルドテストするようにしてみました。
workflow_dispatch（Github Actionsから直接実行できるやつ）とreleaseの経路では全部のビルドを行います。
それ以外の経路（push・pull_request）では簡易テストとします。
- https://github.com/VOICEVOX/voicevox_core/issues/373
- https://github.com/VOICEVOX/voicevox_core/pull/382
条件matrixを動的に変更する必要があるのですが、現状のgithub actionsでは前段階としてジョブを実行し、その出力結果を持ってmatrixを変更する以外方法がありません。
なので前段階のジョブ側に全条件のjsonを作っておいてフィルタリングするようにしました。
さすがに見づらかったのでジョブごとに改行を導入しました。
> ビルドを全通り試さない簡易テストモードを追加する

- .github/workflows/build_and_deploy.yml
- .github/workflows/build_and_deploy_downloader.yml
- .github/workflows/test.yml
- https://github.com/VOICEVOX/voicevox_core/pull/382
関連タスク。
ダウンローダーがいつでも５並列でビルドされていて、各々5分くらいかかっていたので削減します。
ref #382
`precompiled`となっていたのですが、そういう案内をしていたのはここのyamlファイルだけあったので削除しました。
あと改行が全くなくてかなり読みづらかったので改行してみました。
> ダウンローダの自動ビルドを条件付きに

- .github/workflows/update_rust_toolchain.yml
定期的に実行されるRustのアップデートに関しての自動プルリクエストですが、1回プルリクエストを閉じて再オープンすることでテストを簡単に実行できることが分かりました。
忘れそうなので自分自身に案内してもらうように変更してみました。
- https://github.com/VOICEVOX/voicevox_core/pull/567#event-10004388002
> [docs] update-rust-branchの案内を追加

- .github/workflows/build_and_deploy.yml
製品版のvvmを作成したので、それらが使えるようにします。
↓のvvmファイルが読み込めるはずです。
https://github.com/VOICEVOX/voicevox_fat_resource/tree/0d952dabaee41c239af528c98fa6fea4b32054f8/core/model
- https://github.com/VOICEVOX/voicevox_core/issues/545
> 製品版VVMを使うようにする

- crates/voicevox_core_c_api/include/voicevox_core.h
- crates/voicevox_core_c_api/src/lib.rs
`C_STRING_DROP_CHECKER.whitelist` に入れられた文字列は、Rust側でfreeする必要があるが、
user_dictが出力しているjson文字列も対象であることがdocumentから抜け落ちていた。
それに対応し、C-Headerを再生成した。
> Fix: voicevox_json_freeの対象が漏れていたことの修正

- crates/voicevox_core/src/voice_model.rs
- model/README.md
- model/model.json
`get_all_models` 関数は `model` ディレクトリ内のファイルを列挙し、それぞれのファイルを `vvm` ファイルとして扱いロードを行う。
対象のディレクトリに `vvm` ファイル以外のファイルが含まれていた場合、そのファイルを `vvm` ファイルとして扱おうと処理を行い `VOICEVOX_OPEN_FILE_ERROR` を返してしまう。
`get_all_models` は `vvm` ファイルのみを対象とした関数としたほうが良いと考え、ディレクトリ内のファイルを検索した際、`vvm` の拡張子を持つファイルのみを読み込む対象にした。
> VoiceModelのget_all_modelsがvvm以外のファイルも読み込もうとしてクラッシュすることの修正

- crates/voicevox_core_c_api/src/c_impls.rs
- crates/voicevox_core_c_api/tests/e2e/snapshots.toml
- crates/voicevox_core_c_api/tests/e2e/symbols.rs
- crates/voicevox_core_c_api/tests/e2e/testcases.rs
- crates/voicevox_core_c_api/tests/e2e/testcases/synthesizer_new_with_initialize_output_json.rs
`new_with_initialize` を `load_all_models = true` な options で Synthesizerを初期化した後に、`voicevox_synthesizer_get_metas_json`  を呼び出すとmetasが空文字列で返ってきてしまう。
内部でmetasは取得できているのに default で返ってきてしまうのは不適切な挙動に見える。
そのため、空文字列で `metas_cstring ` を初期化せずに、先にsynthesizerを初期化し、そこから取得したmetasを初期値とした。
> C-APIのnew_with_initializeで初期化した場合、metas jsonが空になってしまうことの修正

- .github/workflows/build_and_deploy.yml
https://github.com/VOICEVOX/voicevox_core/releases/tag/0.15.0-preview.7
のビルドが失敗していました。
メインブランチのバージョンが進んでコンフリクトが発生しているためだったので、コンフリクトを解消したバージョンに置き換えました。
> 製品版のタグを0.15.0-preview.2に

- example/cpp/unix/simple_tts.cpp
- example/cpp/windows/simple_tts/simple_tts.cpp
- example/python/README.md
- example/python/run.py
https://github.com/VOICEVOX/voicevox_core/issues/562
ref #562 
README.mdの記載も変える必要がありますか？
> example下の"speaker_id"を、"style_id"に直す #562

- crates/voicevox_core_c_api/src/lib.rs
#534 の方針を継続し、FIXMEとしていた部分を解消します。
というより`VoicevoxUserDictWord`はby valueで渡した方がよいかもしれません。
> 引数の`VoicevoxUserDictWord*`がunalignedであることを許す

- crates/download/src/main.rs
`--min`が付く場合`--additional-libraries-version`は無意味なので、その組み合わせを弾くようにします。
```console
❯ cargo run -qp download -- --min --additional-libraries-version 0.1.0
error: The argument '--min' cannot be used with '--additional-libraries-version <ADDITIONAL_LIBRARIES_VERSION>'
Usage: download --min
For more information try '--help'
```
> ダウンローダで`--min`と`--additional-libraries-version`の同時使用を禁止

- crates/download/src/main.rs
[`clap::Arg::value_name`](https://docs.rs/clap/4/clap/struct.Arg.html#method.value_name)
```console
❯ cargo run -p download -- -h
```
```diff
Usage: download [OPTIONS]
Options:
--min
ダウンロードするライブラリを最小限にするように指定
-  -o, --output <OUTPUT>
+  -o, --output <DIRECTORY>
出力先の指定 [default: ./voicevox_core]
-  -v, --version <VERSION>
+  -v, --version <GIT_TAG_OR_LATEST>
ダウンロードするvoicevox_coreのバージョンの指定 [default: latest]
-      --additional-libraries-version <ADDITIONAL_LIBRARIES_VERSION>
+      --additional-libraries-version <GIT_TAG_OR_LATEST>
追加でダウンロードするライブラリのバージョン [default: latest]
--device <DEVICE>
ダウンロードするデバイスを指定する(cudaはlinuxのみ) [default: cpu] [possible values: cpu, cuda, directml]
--cpu-arch <CPU_ARCH>
ダウンロードするcpuのアーキテクチャを指定する [default: x64] [possible values: x86, x64, arm64]
--os <OS> …
```
> ダウンローダのCLIオプションで`clap::Arg::value_name`を設定

- .github/workflows/download_test.yml
ダウンローダーのテストはいつもlatestを見ているので、ダウンロード内容が変わった時にテストが必ず落ちるようになっています。
https://github.com/VOICEVOX/voicevox_core/pull/603#issuecomment-1712560245
プレリリースを含んだリリースのlatestを使うようにすれば、プレリリースしさえすればテストが落ちないようにすることができるはずなので、その提案を含めてプルリクエストを作ってみました。
- https://github.com/VOICEVOX/voicevox_core/pull/603
> download_testをデフォルトでprerelease込みのlatestが使われるように変更

- Cargo.lock
- crates/voicevox_core_c_api/Cargo.toml
- crates/voicevox_core_c_api/src/lib.rs
ANSI escape sequenceを出力すべきかどうかの判定に[rust-cli/anstyle](https://github.com/rust-cli/anstyle)を用いることで、 #386 を完全にします。
`ENABLE_VIRTUAL_TERMINAL_PROCESSING`がオフの場合でもオンにするようにしたので、これで古いコマンドプロンプトやPowerShellのターミナルでも色が出るようになるかと思います。
(前はPowerShellが壊れちゃってたはず)
[clap](https://docs.rs/crate/clap)は半年前、ターミナルに色を出すためのライブラリを[anstream](https://docs.rs/crate/anstream)に切り替えました。
<https://github.com/clap-rs/clap/pull/4765>
ターミナルに色を出すべきかどうかの判断は今はanstyle(ファミリー)の判定がデファクトになりつつあることから、これを採用しました。[Rust CLI WG](https://github.com/rust-cli)が手がけているというのもあります。
> ANSI escape sequenceの出力の判断を完全にする

- .github/workflows/build_and_deploy.yml
- .github/workflows/download_test.yml
build_and_deployワークフロー実行後にダウンロードテストを実行するようにしてみました。
先に↓のマージが必要です。
- https://github.com/VOICEVOX/voicevox_core/pull/608
こちらのプルリクエストの実行に必要なプルリクエストになってます
- https://github.com/VOICEVOX/voicevox_core/pull/603
> build_and_deployの最後にdownload_testを実行

- .github/workflows/download_test.yml
最新のmainブランチでビルドした結果をdownload_testすると落ちるようになっていたので修正です。
- https://github.com/VOICEVOX/voicevox_core/pull/609
> download_testを最新のもので通るように変更

- crates/voicevox_core_python_api/requirements.txt
Sphinxをv6に、他のプラグインを最新版に上げます。v7ではない理由は、Sphinx v7はPython 3.8を切っているからです。
<https://github.com/VOICEVOX/voicevox_core/pull/625#issuecomment-1741294505>の解決を目標にしています。
うちでもそろそろPython 3.8は切ってもいい感じがしています。
あとですが、もうPoetry入れましょう!!!
> Sphinxをv6に上げる

- crates/voicevox_core/src/devices.rs
- crates/voicevox_core/src/engine/full_context_label.rs
- crates/voicevox_core/src/engine/kana_parser.rs
- crates/voicevox_core/src/engine/open_jtalk.rs
- crates/voicevox_core/src/error.rs
- crates/voicevox_core/src/user_dict/dict.rs
- crates/voicevox_core/src/user_dict/word.rs
#580 で宣言した以下のことをします。
> - `Display`実装には[`source`](https://doc.rust-lang.org/stable/std/error/trait.Error.html#method.source)の内容を含めない
#580, #589, #600, #622, #623 の続きです。
ref #545
> (これは慣習としてどこかで明文化されていたはずですが、それがどこなのかを忘れました)
と書いてたのですが、これです。
- <https://blog.rust-lang.org/inside-rust/2021/07/01/What-the-error-handling-project-group-is-working-towards.html>
> **An error type with a source error should either return that error via `source` or include that source's error message in its own `Display` output, but never both.**
- <https://github.com/rust-lang/project-error-handling/issues/27#issuecomment-763950178>
> * **Return source errors via `Error::source` unless the source error's message is included in your own error message in `Display`.**
> エラーメッセージにおけるcontextとsourceを明確に区分する

- README.md
- https://github.com/VOICEVOX/voicevox_core/issues/631
の解決PRです。
理由は「一貫性を保つため」としています。
fix #631
> [docs] Rust以外の１つの言語でのコア機能追加実装はしない方針であることを明記

- .github/workflows/build_and_deploy.yml
- .github/workflows/build_and_deploy_downloader.yml
ビルド周りのgithubワークフローで、若干統一性がなかったのといくつか気になった点があったのでファクタリングしてみました。
* `github.event.inputs`は`inputs`にできるので短くした
* `ASSET_NAME`をステップ動的に定義するのではなく静的に定義できるようにした
* VSCodeだとステップ内で定義された環境変数は認識されなくてワーニングが出る
* `"contains(matrix.target, 'android')"`がエラーになっていたので直した
* `SKIP_UPLOADING_RELEASE_ASSET`はもう存在しないのでコード中から消した
* `env.VERSION != '0.0.0'`はリリース判定に使わなくなったので変更した
- https://github.com/VOICEVOX/voicevox_core/pull/603
の前作業です。
> ビルド周りのGithub Workflowのリファクタリング

- renovate.json
<https://github.com/VOICEVOX/voicevox_core/issues/470#issuecomment-1755725720>をなんとかします。
ref #470
fork(qryxip/voicevox_core)での確認はこれからします。
> Renovateの設定を直す

- .github/workflows/build_and_deploy.yml
- .github/workflows/build_and_deploy_downloader.yml
- https://github.com/VOICEVOX/voicevox_core/pull/636
のリファクタリングが勘違いしていたので更に修正です。
<s>fromJsonをつければtrueであろうと'true'であろうと正しくbooleanのtrueになるので、これを使うのが一番良さそうでした。</s>
action-lintに怒られるので、inputs由来はbooleanで、stringになる部分はfromJsonを付けるのを気をつけるしかなさそうでした。
actionlint、型の違う２つの比較を怒ってほしい･･･。
`'true'`と`'false'`で検索して対応しました。`== true`などはなかったです。
> Github Actionsのinputsはbooleanが正しくなるので修正

- Cargo.toml
workspace rootでClippyなどを動かそうとしたときに出るこれを解消します。
```console
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
```
`2`で揃える利点としては、再ビルドの発生が減ることが期待できる点です。
(特に今の/crates/test_utilは問答無用で辞書(100MB)を再ダウンロードしたりするので)
> `workspace.resolver`を設定

- Cargo.lock
- Cargo.toml
- crates/download/Cargo.toml
- crates/download/src/main.rs
- crates/voicevox_core/Cargo.toml
ダウンローダーに以下の2つのオプションを追加します。
```console
--only <TARGET>...
ダウンロード対象を限定する [possible values: core, models, additional-libraries, dict]
--exclude <TARGET>...
ダウンロード対象を除外する [possible values: core, models, additional-libraries, dict]
```
Resolves #642.
> ダウンローダーに`--only <TARGET>...`と`--exclude <TARGET>...`を追加

- crates/voicevox_core_java_api/src/open_jtalk.rs
- crates/voicevox_core_java_api/src/user_dict.rs
- crates/voicevox_core_java_api/src/voice_model.rs
> - `JavaApiError::Utf8`: `<JavaStr<'_, '_, '_> as Deref<Target = CStr>>::to_str`としているところをすべて`<Cow<'_, str> as From<&JavaStr<'_, '_, '_>>>::from`に変えることで、存在自体を消しました。
<https://github.com/VOICEVOX/voicevox_core/pull/640#discussion_r1367796728>
以上の内容を独立したPRにしました。
[`JavaStr`](https://docs.rs/jni/0.21/jni/strings/struct.JavaStr.html)の内容は、ドキュメントに書かれている通り"Modified UTF-8"であるため、[`<Cow<'_, str> as From<&JavaStr<'_, '_, '_>>>`](https://docs.rs/jni/0.21.1/jni/strings/struct.JavaStr.html#impl-From<%26'java_str+JavaStr<'local,+'other_local,+'obj_ref>>-for-Cow<'java_str,+str>)を利用するのが適切です。
[中の実装](https://docs.rs/jni/0.21.1/src/jni/wrapper/strings/ffi_str.rs.html#54-63)を見るとちゃんとinfallibleであるか不安にはなるのですが、それでも少なくとも[`Utf8Error`](https://doc.rust-lang.org/stable/std/str/struct.Utf8Error.html)ではなく[`cesu8::Cesu8Dec …
> `JavaStr`の内容を直にUTF-8として読まない

- .github/workflows/python_lint.yml
poetry.lockに対し、<https://github.com/VOICEVOX/voicevox_core/pull/357>と同等のことをします。
Rustのときと比べ、どちらかというと<https://github.com/VOICEVOX/voicevox_engine/issues/750>の対策です。
ちなみに`poetry check (--lock)`は古いpoetry.lockを素通ししました。
> 古いpoetry.lockを弾く

- README.md
READMEの順番を、エンジンと同様にユーザー目線に揃えたいと思います。
APIの使い方→貢献者の方へ→ビルド方法等　にしてみました。
APIの使い方を一番上に持ってきました。
あと貢献者の方へをサンプルの下あたりにしました。
> [docs] READMEのドキュメントの順番を整理

- example/python/run.py
- https://github.com/VOICEVOX/voicevox_core/issues/662
にて気づいたPython版の難しさを少しでも低減するために、一番最初のトラップになり得るであろう「asyncを外して書く」や「def mainを書かない」人を少しでも少なくするためのコメントを追記してみました。
他にも必要な案内などがあれば言っていただければ書こうと思います。
#662
> [docs] Python版exampleで、asyncやawaitは必須であることをコメントで書いておく

- crates/test_util/build.rs
test\_utilクレートが事あるごとにOpenJTalkの辞書(約100MB)を再ダウンロードするのを防ぎます。
> test_utilがOpenJTalkの辞書を常に再ダウンロードしないようにする

- Cargo.lock
- crates/voicevox_core_java_api/src/synthesizer.rs
- crates/voicevox_core_python_api/Cargo.toml
- crates/voicevox_core_python_api/src/lib.rs
Python APIとJava APIでの、（ #553 により不要になっているはずの）`Synthesizer`に対する`Mutex`を外します。
<https://github.com/VOICEVOX/voicevox_core/issues/662#issuecomment-1784080580>
@sevenc-nanashi  Java APIの方が`Mutex`になってたのって、何か理由があったりしますか?
> `Synthesizer`から`Mutex`を外す

- crates/voicevox_core/src/error.rs
- crates/voicevox_core/src/status.rs
現状ONNX Runtimeの`Run`が失敗した場合、エラーの内容は破棄されて`Error::InferenceFailed`という情報だけが得られるような状態です。
このPRではONNX Runtimeのエラーを`Error::InferenceFailed`に設定し、COREユーザー側ログ及びENGINEのログでその内容を見られるようにします。
ref #545
ref #580, #589, #600, #622, #623, #624, #625, #640
> `Error::InferenceFailed`にsourceとして`OrtError`を持たせる

- crates/voicevox_core/src/engine/open_jtalk.rs
- crates/voicevox_core/src/engine/synthesis_engine.rs
- crates/voicevox_core/src/inference_core.rs
- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core_c_api/include/voicevox_core.h
- crates/voicevox_core_c_api/src/c_impls.rs
- crates/voicevox_core_c_api/src/compatible_engine.rs
- crates/voicevox_core_c_api/src/lib.rs
- crates/voicevox_core_c_api/tests/e2e/snapshots.toml
- crates/voicevox_core_c_api/tests/e2e/symbols.rs
- crates/voicevox_core_c_api/tests/e2e/testcases.rs
- crates/voicevox_core_c_api/tests/e2e/testcases/simple_tts.rs
- crates/voicevox_core_c_api/tests/e2e/testcases/synthesizer_new_output_json.rs
- crates/voicevox_core_c_api/tests/e2e/testcases/tts_via_audio_query.rs
- crates/voicevox_core_c_api/tests/e2e/testcases/user_dict_load.rs
- crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/OpenJtalk.java
- crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/Synthesizer.java
- crates/voicevox_core_java_api/src/open_jtalk.rs
- crates/voicevox_core_java_api/src/synthesizer.rs
- crates/voicevox_core_python_api/python/test/test_pseudo_raii_for_synthesizer.py
- crates/voicevox_core_python_api/python/test/test_user_dict_load.py
- crates/voicevox_core_python_api/python/voicevox_core/_rust.pyi
- crates/voicevox_core_python_api/src/lib.rs
- example/cpp/unix/simple_tts.cpp
- example/cpp/windows/simple_tts/simple_tts.cpp
- example/python/run.py
`Synthesizer::new_with_initialize`と`OpenJtalk::new_with_initialize`、およびそれに対応するFFIをすべてリネームします。
`Synthesizer`の方にはそもそも今は「initialize抜きのnew」が存在せず、`OpenJtalk`の方は`Option<OpenJtalk>`として運用すればよいです。
（このあたりの話はどこかでした気がするけど、見あたらない…）
#545
> "new_with_initialize" → "new"

- crates/voicevox_core/src/engine/synthesis_engine.rs
- crates/voicevox_core/src/inference_core.rs
- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core_c_api/src/c_impls.rs
- crates/voicevox_core_c_api/src/compatible_engine.rs
- crates/voicevox_core_c_api/src/lib.rs
- crates/voicevox_core_java_api/src/synthesizer.rs
- crates/voicevox_core_python_api/python/test/test_pseudo_raii_for_synthesizer.py
- crates/voicevox_core_python_api/python/test/test_user_dict_load.py
- crates/voicevox_core_python_api/python/voicevox_core/_rust.pyi
- crates/voicevox_core_python_api/src/lib.rs
- example/python/run.py
`Synthesizer::new`にはもともと`load_all_models`というオプションがありましたが、今は #587 により無くなっています。なので今は`Synthesizer::new`は何のIOも重たい処理もせずに、数十μsで完了します (ちなみに数十μsの大部分は`SupportedDevices`を毎回作りなおしているところかと思われます)。
なのでもうasyncは不要でもあり、適切でもなくなっているかと思いました。
#545
> `Synthesizer::new`を非asyncにする

- crates/voicevox_core_python_api/python/voicevox_core/__init__.py
- crates/voicevox_core_python_api/python/voicevox_core/_models.py
- crates/voicevox_core_python_api/python/voicevox_core/_rust.pyi
Python APIに以下の`NewType`を追加します。
```python
StyleId = NewType("StyleId", int)
StyleVersion = NewType("StyleVersion", str)
VoiceModelId = NewType("VoiceModelId", str)
```
`Synthesizer`のメソッドの引数では`style_id: StyleId | int`のようにし、`int`も型チェックが通るようにします。
#545
Javaには手を付けていません。
(GSONがこの手のものを扱えるか未検証)
> Python APIに`NewType`を導入

- crates/voicevox_core/src/__internal.rs
- crates/voicevox_core/src/__internal/doctest_fixtures.rs
- crates/voicevox_core/src/synthesizer.rs
Rust APIのdoctestにおいてコピペ状態になっていた部分を、`__internal`下に分離しました。
> Rust APIのdoctestのボイラープレートをfixtureとして分離

- crates/voicevox_core/src/infer.rs
- crates/voicevox_core/src/infer/runtimes/onnxruntime.rs
- crates/voicevox_core_macros/src/inference_domain.rs
FIXMEを一つ解消します。
文脈: <https://github.com/VOICEVOX/voicevox_core/pull/675#discussion_r1390170812>
#545
> 入力テンソルをvisitor patternで捌く

- crates/downloader/Cargo.toml
- crates/test_util/Cargo.toml
- crates/voicevox_core/Cargo.toml
- crates/voicevox_core/src/lib.rs
- crates/voicevox_core_c_api/Cargo.toml
- crates/voicevox_core_java_api/Cargo.toml
- crates/voicevox_core_java_api/src/common.rs
- crates/voicevox_core_macros/Cargo.toml
- crates/voicevox_core_python_api/Cargo.toml
- crates/voicevox_core_python_api/src/convert.rs
- crates/voicevox_core_python_api/src/lib.rs
- crates/xtask/Cargo.toml
Rust 1.74で追加された[Cargoの`lints`設定](https://blog.rust-lang.org/2023/11/16/Rust-1.74.0.html#lint-configuration-through-cargo)を利用します。
ついでに[`rust-2018-idioms`](https://doc.rust-lang.org/rustc/lints/groups.html)も有効化します。
#681
> Cargoの`lints`設定を利用する

- crates/voicevox_core/src/user_dict/word.rs
> Fix: UserDict.to_mecab_formatが2重に改行していたのを修正

- Cargo.lock
- Cargo.toml
- crates/downloader/Cargo.toml
- crates/test_util/Cargo.toml
- crates/voicevox_core/Cargo.toml
- crates/voicevox_core_c_api/Cargo.toml
- crates/voicevox_core_java_api/Cargo.toml
- crates/voicevox_core_macros/Cargo.toml
- crates/voicevox_core_python_api/Cargo.toml
- crates/xtask/Cargo.toml
Cargo.tomlのdependenciesについて、
1. `version`は`workspace.dependencies`に
2. `features`はpackageの`dependencies`系に
書くようにします。
1.についてはrust-lang/cargo自体がやっています。
2.については、次のコマンドが通るように`features`の補足も行いました。
```console
❯ find ./crates/ -name Cargo.toml -exec cargo clippy --manifest-path {} ';'
❯ find ./crates/ -name Cargo.toml -exec cargo clippy --manifest-path {} --all-targets ';'
```
> クレートのversionはworkspace設定に、featureはpackage設定に

- crates/voicevox_core/src/__internal.rs
- crates/voicevox_core/src/__internal/interop.rs
- crates/voicevox_core/src/engine/open_jtalk.rs
- crates/voicevox_core/src/infer/status.rs
- crates/voicevox_core/src/lib.rs
- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core/src/task.rs
- crates/voicevox_core_c_api/src/compatible_engine.rs
- crates/voicevox_core_java_api/src/synthesizer.rs
- crates/voicevox_core_python_api/src/lib.rs
`Synthesizer`の音声合成系のメソッドを、すべて丸ごとスレッド分離して実行するようにし、asyncのランタイムを阻害しないようにします。
#545 の以下のタスクを完全に解決します。
>     - [ ] モデルを実行するところとかは`tokio::task::spawn_blocking`で囲ったりするべきでは?
#545
> 音声合成の処理を丸ごとスレッド分離して実行する

- crates/voicevox_core/src/__internal/doctest_fixtures.rs
- crates/voicevox_core/src/engine/open_jtalk.rs
- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core_c_api/src/c_impls.rs
- crates/voicevox_core_c_api/src/compatible_engine.rs
- crates/voicevox_core_c_api/src/lib.rs
- crates/voicevox_core_java_api/src/open_jtalk.rs
- crates/voicevox_core_java_api/src/synthesizer.rs
- crates/voicevox_core_python_api/src/lib.rs
`struct OpenJtalk`を`Synthesizer<OpenJtalk> | Synthesizer<()>`として持つようにします。
（Rust APIはパブリックではないので暫定）
これにより、`OpenJtalk`は必ずシステム辞書を読み込んでいる状態になります。
変更しているpublic APIはRust APIのみです。C（`compatible_engine`を除く）もPythonもJavaも現状Open JTalkが必須となっているのですが、もし必須ではなくするとしたら、設計については議論の余地があると思っています。
考慮すべきはこんな感じだと思っていて、
- アドホック多相（`Synthesizer<()>`からはメソッドが生えなくて、`Synthesizer<OpenJtalk>`からは生えてくる）があると仮定しない
- Rust APIはまた組み直す
- classの継承があると仮定しない（Rust以外にもGoとかがある）
- ~~関数の引数や戻り値に動的ディスパッチされるinterfaceが使えると仮定しない~~
- interfaceとかabstract classに該当するものは、現代的な言語には流石にあるはず
- classの継承があるなら、親側をabstractということにすればいけるはず。例えばOCamlやSML#でも[多相バリアント](https://ocaml.jp/refman/ch04s02.html)で部分型付けが表現できるのでどうにかなるはず（[参考](https://zenn.dev/akabe/articles/phantom-types-subtyping-introduction)）
- 言語間で**多少**形が違うくらいは許容してもよいはず。例えばCは、`void*`で扱って実行時チェックとするしかないはず …
> `OpenJtalk`を`Synthesizer<OpenJtalk> | Synthesizer<()>`として持つ

- crates/voicevox_core_python_api/poetry.lock
- crates/voicevox_core_python_api/pyproject.toml
- crates/voicevox_core_python_api/python/voicevox_core/_models.py
Pydanticをv2に上げます。
[マイグレーションガイド](https://docs.pydantic.dev/latest/migration/#validator-and-root_validator-are-deprecated)
#545
> Pydanticをv2に上げる

- crates/voicevox_core/src/engine/model.rs
- crates/voicevox_core_python_api/python/test/test_audio_query.py
- crates/voicevox_core_python_api/python/voicevox_core/_models.py
Python APIにおける以下のdataclassのフィールドを、Rust APIとENGINEに合わせてオプショナルにします。
- `Mora.consonant: Optional[str]`
- `Mora.consonant_length: Optional[str]`
- `AccentPhrase.pause_mora: Optional[Mora]`
- `AccentPhrase.is_interrogative: bool`
- `AudioQuery.kana: Optional[str]`
0.14からユーザーに提供している部分への修正となります。
<https://github.com/VOICEVOX/voicevox_core/pull/695#discussion_r1405403733>
Java APIについてですが、GSONはそもそも`"null"`とか`"{}"`みたいなものも受理するようです。
> dataclassでオプショナルになっているべきフィールドをオプショナルにする

- .github/workflows/test.yml
Python Exampleの動作チェックを追加します。
- closes: #674 
（なし）
> Add: Exampleの動作チェックを追加

- README.md
- docs/downloader.md
- docs/usage.md
0.15に向けて少しドキュメントを整理しました。
* READMEからユーザーガイドをリンク
* ユーザーガイドからVVMのリンク追加
* 利用規約があることをREADME、ユーザーガイド、ダウンローダー説明内に追記
- https://github.com/VOICEVOX/voicevox_project/discussions/22#discussioncomment-7295062
- https://github.com/VOICEVOX/voicevox_core/issues/545
> [docs] ドキュメント整理（ユーザーガイドをリンク、VVMのリンク追加、利用規約があることを案内）

- crates/test_util/src/lib.rs
- crates/voicevox_core/src/devices.rs
- crates/voicevox_core/src/engine/acoustic_feature_extractor.rs
- crates/voicevox_core/src/engine/kana_parser.rs
- crates/voicevox_core/src/engine/mod.rs
- crates/voicevox_core/src/engine/model.rs
- crates/voicevox_core/src/engine/mora_list.rs
- crates/voicevox_core/src/engine/open_jtalk.rs
- crates/voicevox_core/src/error.rs
- crates/voicevox_core/src/infer/status.rs
- crates/voicevox_core/src/lib.rs
- crates/voicevox_core/src/manifest.rs
- crates/voicevox_core/src/metas.rs
- crates/voicevox_core/src/result.rs
- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core/src/user_dict/dict.rs
- crates/voicevox_core/src/user_dict/mod.rs
- crates/voicevox_core/src/user_dict/word.rs
- crates/voicevox_core/src/version.rs
- crates/voicevox_core/src/voice_model.rs
- crates/voicevox_core_c_api/src/c_impls.rs
- crates/voicevox_core_c_api/src/compatible_engine.rs
- crates/voicevox_core_c_api/src/helpers.rs
- crates/voicevox_core_c_api/src/lib.rs
- crates/voicevox_core_python_api/src/lib.rs
`use super::*`や`use self::foo::*`のようなglob importを取り除きます。
ただし次のような、**`fn`内での**enumのバリアントに対するものは残します。なぜならこれらは影響範囲が限定的だからです（人間の認知にとっても）。
<https://github.com/VOICEVOX/voicevox_core/blob/0788c2ef225f0665cbe371b80ee3f3b53a869f2a/crates/voicevox_core_c_api/src/helpers.rs#L25-L32>
コードエティタの支援の仕組みが完全に整っていなかったRust出始めの数年(2010年代後半)とは違ってRust Analyzerがある現在、glob importの恩恵は少なくなっていると思います。加えてこのリポジトリの場合、パブリックにする必要のないアイテムまで`pub`が付けられることによって結構カオスなことになっていると感じています。先日のブロッキング版APIのときもちょくちょく牙を剥いてくるように感じました。
glob importを使った方が適切な箇所があったとしても、いったん可視性について設計し直したあと改めてglob importにする、という流れの方がよいかなと思いました。
Resolves #467.
> モジュールレベルのglob importをすべて取り除く

- crates/voicevox_core/src/__internal/interop.rs
- crates/voicevox_core/src/engine/open_jtalk.rs
- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core/src/user_dict/dict.rs
- crates/voicevox_core/src/voice_model.rs
- crates/voicevox_core_c_api/tests/e2e/log_mask.rs
#702 で実装した`blocking`版の`impl`と`tokio`版の`impl`は、Gitのdiffを出さないためだけにこうしていました。
```rust
impl self::blocking::PublicStruct {
// …
}
impl self::tokio::PublicStruct {
// …
}
pub(crate) mod blocking {
pub struct PublicStruct;
}
pub(crate) mod tokio {
pub struct PublicStruct;
}
```
これを次のようにします。
```rust
pub(crate) mod blocking {
pub struct PublicStruct;
impl self::PublicStruct {
// …
}
}
pub(crate) mod tokio {
pub struct PublicStruct;
impl self::PublicStruct {
// …
}
}
```
> `blocking`版と`tokio`版の`impl`を`mod`内に移す

- crates/downloader/Cargo.toml
- crates/test_util/Cargo.toml
- crates/xtask/Cargo.toml
Rust 1.75より、Cargo.tomlの`package.version`は省略可能になります。デフォルト値は`0.0.0`になります。また`package.version`を省略した場合、`package.publish = false`と同じ効果が発生します。
このPRは、ライブラリ/バイナリとしてリリースすることが無いであろう3つのクレートの`package.version`を省略します。`cargo set-version`は`package.version`が無くても普通に新規で挿入してくれるみたいなので全クレートでもよさそうですが、いったん様子見で。
> downloader, test_util, xtaskの`package.version`を省略する

- Cargo.lock
clang++ ver 15.0.0のiOSビルドできるようにした。
warning: clang: error: unknown argument: '-arch arm64'
でコンパイルできない件の修正。
Cコンパイラのccを1.0.73から1.0.83へ上げた。
ref #524 
1.0.79であれば上記エラーはなくなりますが、最新の1.0.83としました。
コンパイラのバージョンアップのためマージの際は影響を確認ください。
（今のワークアラウンドのclangのバージョンを下げてのコンパイルのほうに影響があれば少し心配かも）
> ccを1.0.73から1.0.83へupdate

- crates/voicevox_core/src/publish.rs
- crates/voicevox_core/src/status.rs
- crates/voicevox_core/src/status/model_file.rs
- crates/voicevox_core_c_api/src/compatible_engine.rs
題の通りです。
テストは一旦無視しています。
また、ダミーモデルも既存のものを適当に刺しているため、動きません。
各ネーミングは適当なので、後で書き換えたほうがいいかもしれない...?
> [project-s] ハミング機能・歌機能向けのモデル・API(compatible_engineのみ)を追加

- crates/voicevox_core/src/publish.rs
ハミング機能・歌機能両方があるスタイルのモデル読み込み判定がおかしかったので、修正しました。
- ref VOICEVOX/voicevox#1728
> fix is model loaded bug

- crates/voicevox_core/src/publish.rs
project-sモデルへ入力する値をすべて`(1, data length)`のような形にreshapeしました。
また、`predict_sing_volume`のTODOを解決し、f0を入力するようにしました。
ref #712
> [project-s] モデルへの入力の形・データを修正

- crates/voicevox_core/src/publish.rs
- crates/voicevox_core/src/status.rs
- crates/voicevox_core/src/status/model_file.rs
- model/metas.json
project-s用のテストを書きました。
とりあえず推論が通ることを確認するだけです。
まだサンプルのonnxがGithub内にないので、とりあえずコメントアウトしています。
とりあえずpushするのが目的なのでマージしなくても良いかもです。
- https://github.com/VOICEVOX/voicevox_project/issues/15
> [project-s] project-s用のテストを作成（モデルがないのでコメントアウト中）

- Cargo.lock
- Cargo.toml
- crates/voicevox_core/Cargo.toml
- crates/voicevox_core/src/__internal/doctest_fixtures.rs
- crates/voicevox_core/src/engine/open_jtalk.rs
- crates/voicevox_core_c_api/Cargo.toml
- crates/voicevox_core_c_api/src/c_impls.rs
- crates/voicevox_core_python_api/Cargo.toml
- crates/voicevox_core_python_api/src/convert.rs
- crates/voicevox_core_python_api/src/lib.rs
- <https://github.com/VOICEVOX/open_jtalk-rs/pull/18>
- <https://github.com/VOICEVOX/open_jtalk-rs/pull/29>
> open_jtalk-rsを更新し、caminoを利用

- crates/voicevox_core/src/lib.rs
- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core/src/text_analyzer.rs
#730 で話されている，`TextAnalyzer` interfaceを実装するための準備として，Rust側に`TextAnalyzer` traitを生やしました．
また，
- AquesTalk風記法からAccentPhraseの配列を生成するTextAnalyzer
- OpenJtalkからAccentPhraseの配列を生成するTextAnalyzer
を実装するためにSynthesizerからコードを移動し，これら2つのTextAnalyzerをSynthesizerに持たせました．
Issue全体の実装をする(_kana系APIとOpenJTalkの統合)を行うと，Synthesizerを触る部分全体にAPI変更が波及してしまうため，外から見たAPIの変更は現時点では全く行っていません．
#730
> TextAnalyzer traitにstring->AccentPhraseModel[]を移動

- crates/voicevox_core_c_api/src/lib.rs
- crates/voicevox_core_python_api/src/convert.rs
- crates/voicevox_core_python_api/src/lib.rs
次の変更を加えます。
- C API
- `voicevox_synthesizer_is_loaded_voice_model`: 引数`model_id`がUTF-8ではない場合、パニックする代わりに黙って`false`を返す。
- Python API
- `VoiceModel::is_loaded_voice_model`: 引数にRustの`str`ではなくPythonの`str`を要求し、UTF-8ではない場合黙って`False`を返す(C APIと一貫性を持たせる)。
- `VoiceModel::from_path`: 引数がUTF-8であることを要求しない。
Java APIについては、MUTF-8 → UTF-8の変換が多分必ず成功するので、`isLoadedVoiceModel`も含めそのままです。
あとユーザー辞書については、別PRにしようと思います。
> C APIとPython APIの不必要なUTF-8の要求を外す

- crates/voicevox_core_python_api/src/lib.rs
Python APIの`asyncio` (with `tokio`)版実装に対し、 #710 と同じことをします。
#710
> Python APIの`asyncio`版実装を`mod`内に移す

- crates/test_util/src/lib.rs
- crates/voicevox_core/src/engine/acoustic_feature_extractor.rs
- crates/voicevox_core/src/engine/kana_parser.rs
- crates/voicevox_core/src/engine/mora_list.rs
- crates/voicevox_core/src/infer/status.rs
- crates/voicevox_core/src/lib.rs
- crates/voicevox_core/src/test_util.rs
- crates/voicevox_core/src/text_analyzer.rs
- crates/voicevox_core/src/user_dict/part_of_speech_data.rs
- crates/voicevox_core/src/user_dict/word.rs
- crates/voicevox_core_c_api/src/helpers.rs
- crates/voicevox_core_java_api/src/common.rs
- crates/voicevox_core_python_api/src/convert.rs
Rustコードの全アイテムの可視性(_visibility_)を、可能な限り狭めます。
(いくつか見落としがあるかもしれません)
Resolves #594.
> アイテムの可視性を必要最低限にする

- crates/voicevox_core/src/status.rs
> [release-0.15] .onnx/.binファイルの読み込みを遅延させる

- .github/workflows/test.yml
`macos-latest`が`macos-14` (AArch64)になったためそれに対応します。
<https://github.com/qryxip/voicevox_core/actions/runs/8869988493/job/24351267440>
> `macos-latest` = `macos-14`に適応する

- renovate.json
[Renovateのページ](https://developer.mend.io/github/VOICEVOX/voicevox_core)を開いたらこんな表示があったので対応します。ちなみにこのメッセージは、このリポジトリのissueにあるdashboardでも見れます。
"packagePatterns"と"depPatterns"の違いは以下のような感じらしいです。`^Rust$`は実際"packageName"ではなく"depName"を指していますし、上記のメッセージがその"warning"っぽい(ログを見ても同内容のwarningがある)ので、指示に従って置き換えるのが正解だと思います。
> `matchPackagePatterns` will try matching `packageName` first and then fall back to matching `depName`. If the fallback is used, Renovate will log a warning, because the fallback will be removed in a future release. Use `matchDepPatterns` instead.
[`matchPackagePatterns` - Configuration Options - Renovate Docs](https://docs.renovatebot.com/configuration-options/#matchpackagepatterns)
> chore: renovate.jsonの"packagePatterns"を"depPatterns"に

- .github/actions/create-venv/action.yml
- .github/actions/rust-toolchain-from-file/action.yml
- .github/workflows/build_and_deploy.yml
- .github/workflows/generate_document.yml
- .github/workflows/java_lint.yml
以下の二つを行い、2024-05-09にリリースされた[actionlint v1.7.0](https://github.com/rhysd/actionlint/releases/tag/v1.7.0)に対応します。
1. .github/actionsにあるローカルのアクションの、`name`と`description`を埋める
2. Node.jsのバージョン（?）が古いと言われているアクションを更新
> chore: actionlint v1.7.0に適応する

- crates/voicevox_core/src/manifest.rs
- crates/voicevox_core/src/status.rs
- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core/src/voice_model.rs
- model/sample.vvm/manifest.json
<https://github.com/VOICEVOX/voicevox_core/issues/581#issuecomment-1837168657>の2.です。`style_id_to_model_inner_id`を`style_id_to_inner_voice_id`にします。
ref #581
> change: `style_id_to_model_inner_id` → `style_id_to_inner_voice_id`

- crates/voicevox_core_c_api/src/lib.rs
Rust 1.79に上げるとC APIのテストがSEGV(多分)することがわかりました。
<https://github.com/VOICEVOX/voicevox_core/actions/runs/9505427859?pr=799>
原因は`voicevox_user_dict_add_word`の実装です。起こっていることはおそらくこんな感じです。
<https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3d7d63d7dd6216fbb5172391013be984>
`voicevox_user_dict_add_word`は現在`output_word`に書き込む方法を誤っており、16バイトではなく16×16=256バイトを`memmove`してスタックを破壊しています。書き込む方法を正しくすることで修正を行います。
> fix: `voicevox_user_dict_add_word`がスタックを破壊するのを修正

- .github/workflows/build_and_deploy.yml
- .github/workflows/build_and_deploy_downloader.yml
- .github/workflows/test.yml
`macos-11`がついに動かなくなったのでmacOS 11のサポートを切ります。
また、`macos-11`と`macos-12`でテストを回していたところはそれぞれ`12`と`13`にします。
VOICEVOX/voicevox_engine#1205
> change: macOS 11のサポートを切る

- .github/workflows/generate_document.yml
- docs/apis/index.html
Rust APIのAPIドキュメントをデプロイするようにします。
出力例:
<https://github.com/qryxip/voicevox_core/actions/runs/9764883634>
<https://qryxip.github.io/voicevox_core/apis/>
ref #388
> add: Rust APIのAPIドキュメントをデプロイするようにする

- crates/voicevox_core/src/engine/full_context_label.rs
- crates/voicevox_core/src/engine/kana_parser.rs
- crates/voicevox_core/src/engine/mod.rs
- crates/voicevox_core/src/engine/model.rs
- crates/voicevox_core/src/lib.rs
- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core/src/text_analyzer.rs
- crates/voicevox_core_c_api/src/helpers.rs
- crates/voicevox_core_c_api/src/lib.rs
- crates/voicevox_core_java_api/src/synthesizer.rs
- crates/voicevox_core_python_api/src/convert.rs
- crates/voicevox_core_python_api/src/lib.rs
<https://github.com/VOICEVOX/voicevox_core/pull/742#issuecomment-1961075655>
型名に"Model"と付ける意味は今だと全部消失していると思いました。
またRust APIからは`Mora`がエクスポートされていないことがわかったので、このPRではそれも修正しています。
(「`jlabel::Mora`との区別については、`jlabel::Mora`と`crate::Mora`とでもしておけば」の一部として)
ref #388
> refactor: Rust APIのAudioQuery系の型名から接尾辞"Model"を削除

- crates/voicevox_core/src/devices.rs
- crates/voicevox_core/src/engine/full_context_label.rs
- crates/voicevox_core/src/engine/kana_parser.rs
- crates/voicevox_core/src/engine/model.rs
- crates/voicevox_core/src/metas.rs
- crates/voicevox_core/src/status.rs
- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core/src/user_dict/word.rs
- crates/voicevox_core/src/voice_model.rs
- crates/voicevox_core_c_api/src/compatible_engine.rs
- crates/voicevox_core_c_api/src/lib.rs
- crates/voicevox_core_java_api/src/voice_model.rs
- crates/voicevox_core_python_api/src/lib.rs
題の通りです。
- `SupportedDevices`, `SpeakerMeta`系: VOICEVOX CORE側から一方的に返すものなので[open struct](https://chatgpt.com/share/7b23fd9b-3db3-48d7-bd3d-0199f97e4ff2)でよい
- `AudioQuery`系: 「不正な`AudioQuery`」という概念は一応今は定義されていないため、open structでよい
- `UserDictWord`: 上記とは異なり、「不正な`UserDictWord`」という概念が存在するためgetterを定義
- `surface`と`pronunciation`と`priority`だけだったら`UserDictWord{Surface,…}`を作ればよいのだが、「`accent_type`は単語のモーラ数を超過してはならない」という制約もある
ref #388
> refactor: Rust APIにおけるgetterをパブリックAPIとして整える

- README.md
バージョン0.20をビルドするために、まずは以前の片付けをします。
どうやら前回は0.14で、まだreleaseブランチをmainにマージしていなさそうだったので、マージします。
> merge release 0.14

- README.md
- https://github.com/VOICEVOX/voicevox_core/pull/811
をリバートします。
* Nemo COREと間違えた
* READMEがNemo用になってしまう変更
* 宛先もmainではなくrelease-0.14になってた
* sqashじゃなくff mergeしてしまったので、revertもそうしようと思います
> Revert "merge release 0.14"

- .github/workflows/build_and_deploy.yml
- .github/workflows/test.yml
release-0.15でまたアップデートリリースする可能性があるので、release-0.15ブランチのmacos-11をmacos-12にアップデートしておきます。
（というより、Nemo側でmacos-12を試してエラーになったのでこちらでも試してみようかなと･･･）
> [release-0.15] macos-11をmacos-12にアップデートしておく

- renovate.json
#814 を調べたら、[GitHub App](https://github.com/apps/renovate)上で動くRenovate本体のバージョンが8月6日に37.440.7から38.18.17に上がったことがわかりました。そのため[Renovate v37 → v38での破壊的変更](https://docs.renovatebot.com/release-notes-for-major-versions/#breaking-changes-for-38)に対応することで問題を解決します。
ただ、changelogを見てもよくわからなかったのでエラーメッセージの内容から推察して適当に弄って直しました。qryxip/voicevox\_core上で動かしましたが、おそらく以前の通りに動きます。
ref #814 (設定として直り次第Renovate側からcloseされるはず)
> ci: Renovate v38に適応する

- renovate.json
最近rust-lang/rustの緊急パッチリリース (e.g. 最近の1.80.1)はGitHub Releaseの方から出ない傾向にあり、今のRenovateの設定だと反応しません。そのため設定の`datasourceTemplate`を[`github-releases`](https://docs.renovatebot.com/modules/datasource/github-releases/)から[`github-tags`](https://docs.renovatebot.com/modules/datasource/github-tags/)に変えることで拾えるようにします。
#817 に依存します。
> ci: Renovateのdatasourceを`github-tags`にする

- README.md
README の冒頭にある「現在の main ブランチは……」が参照するように言っているバージョンが古いので新しくしました．
ところで，[0.15.4](https://github.com/VOICEVOX/voicevox_core/tree/0.15.4) には「0.13.0をご利用ください」とありますけど，大丈夫なんでしょうか……？
> Update jump-to version on README

- crates/test_util/src/lib.rs
- crates/voicevox_core/src/devices.rs
- crates/voicevox_core/src/engine/acoustic_feature_extractor.rs
- crates/voicevox_core/src/infer.rs
- crates/voicevox_core/src/lib.rs
- crates/voicevox_core/src/manifest.rs
- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core/src/user_dict/word.rs
- crates/voicevox_core_c_api/src/lib.rs
- crates/voicevox_core_c_api/src/result_code.rs
- crates/voicevox_core_python_api/src/lib.rs
[Announcing Rust 1.81.0 | Rust Blog](https://blog.rust-lang.org/2024/09/05/Rust-1.81.0.html)
- `#[allow(…)]`を`#[expect(…)]`に置き換えます。不要になった警告抑制をすみやかに消せるようにするためです。
- C APIの`non_camel_case_types`だけ、Rust Analyzerがまだ`#[expect(…)]`に対応していなくてClippyとは別に文句を言ってくるため`#[allow(…)]`のままにしています。
\[追記\] test_utilで生成しているc_api.rsについても、OSによってbindgenの生成コードが変わって管理が面倒なので`#[expect(…)]`にするのは諦めました。
- `#[allow(…)]`, `#[expect(…)]`, `#[forbid(…)]`のすべてに`reason = "…"`を書きます。
- `allow`と`expect`の`reason`をどういう文体で書くか迷ったのですが、コメントのような感じで書くことにしました。`forbid`の方はエラーメッセージとしての文体に。
Rust 1.81: #826
前回: #816
> chore: Rust 1.81で追加された機能を利用する

- crates/voicevox_core/Cargo.toml
- crates/voicevox_core/src/engine/acoustic_feature_extractor.rs
- crates/voicevox_core/src/engine/open_jtalk.rs
- crates/voicevox_core/src/infer/domains.rs
- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core/src/voice_model.rs
- crates/voicevox_core_c_api/build.rs
- crates/voicevox_core_c_api/src/lib.rs
- crates/voicevox_core_c_api/tests/e2e/snapshots.toml
- crates/voicevox_core_c_api/tests/e2e/testcases/user_dict_load.rs
- crates/voicevox_core_java_api/src/logger.rs
- crates/voicevox_core_python_api/python/test/test_nop.py
- crates/voicevox_core_python_api/python/voicevox_core/_load_dlls.py
単体でPRを出すには微妙な、細かいリファクタです。
主に不要なコードの削除と、嘘コメントの訂正です。diffの範囲が大きくなりそうなやつは見送りました。
> chore: minor refactor

- crates/voicevox_core/Cargo.toml
- crates/voicevox_core/src/asyncs.rs
- crates/voicevox_core/src/user_dict/dict.rs
#830 の`Inner<A: Async>`で共通化する設計を`UserDict`でもやり、それと共にasync-fsを導入することでasync APIとしての質を向上させます。
> #830 の設計を`UserDict`にも

- crates/voicevox_core/src/user_dict/dict.rs
- crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/UserDict.java
- crates/voicevox_core_java_api/src/user_dict.rs
- crates/voicevox_core_python_api/python/voicevox_core/_rust/asyncio.pyi
- crates/voicevox_core_python_api/python/voicevox_core/_rust/blocking.pyi
- crates/voicevox_core_python_api/src/convert.rs
- crates/voicevox_core_python_api/src/lib.rs
`UserDict`のパブリックAPIについて以下の変更を加えます。
1. `load`と`store`が引数に取るファイルパスについて:
* Rust APIでは`&str`から`impl AsRef<Path>`にする
* Python APIでは[`StrPath`](https://github.com/python/typeshed/blob/6cddd30ff2a64f6a3e509c992684c4a0a357fe71/stdlib/_typeshed/__init__.pyi#L173)相当にする
* Java APIでは`java.io.File`と`java.nio.file.Path`のオーバーロードを追加する
2. Rust APIの`with_words`から`&mut IndexMap<…>`が得られるようにします。
本当は`dict`や`java.util.HashMap`へ変換するやつについても手を入れたかったのですが、やるならそこそこ大々的にやった方がよいかなと思い見送りました。
> change: minor changes for `UserDict` API

- docs/apis/index.html
<https://voicevox.github.io/voicevox_core/apis/>のC APIとPython APIのリンク先が不親切なことになっているので、置き換えます。
#496 (?)
> chore: voicevox.github.io/voicevox_core/apis内のリンクを置き換え

- README.md
- docs/apis/index.html
#269 の頃からあるリンクの宛先を<https://voicevox.github.io/voicevox_core/apis/>直下にします。
#496 (Discordの会話: <https://discord.com/channels/879570910208733277/893889888208977960/1109301082502484108>)
> chore: READMEからvoicevox.github.io/voicevox_core/apisにリンク

- README.md
頂いたコメントをもとに、自分でビルドした場合はサンプルモデルしか読み込めないことがわかるようにしてみました。
- https://github.com/VOICEVOX/voicevox_core/issues/492#issuecomment-2377448309
close #492 
書き方をちょっと迷いました。
「自分で一からビルドした場合は、model フォルダにある onnx モデルのみが利用できます。」と書いていますが、実際は自分で作ったonnxモデルとかも読み込めるといえば読み込めるので･･･。
「製品版VOICEVOXのvvmは読み込めません。」の方がよければそっちにしても良いかも。
ただまぁどちらにせよ voicevox_onnxrutime 構想になれば不要になる一文なので、あまり考えすぎる必要もないかなと思って、元の文章からほとんど変わらない形を採用してみた次第です。
> docs: READMEのビルド周りの記載を更新し、自分でビルドした場合は製品版のVVMが読めないことをわかるように

- Cargo.toml
- crates/downloader/Cargo.toml
- crates/test_util/Cargo.toml
- crates/voicevox_core/Cargo.toml
- crates/voicevox_core_c_api/Cargo.toml
- crates/voicevox_core_java_api/Cargo.toml
- crates/voicevox_core_macros/Cargo.toml
- crates/voicevox_core_python_api/Cargo.toml
- crates/xtask/Cargo.toml
- renovate.json5
[`package.rust-version`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field)を書きます。
#388
現在このリポジトリでは[PRのマージ時にコミットメッセージ本文を書く運用をしている](https://github.com/VOICEVOX/voicevox_project/issues/56)のですが、このPRのものはwhyも書かずに空欄にしようかなと思っています。
> chore: `package.rust-version`を書く

- crates/voicevox_core/src/status.rs
- crates/voicevox_core/src/user_dict/dict.rs
indexmapを新しいバージョンに上げると以下の警告が出るため、その対応です。
（このPRではindexmapのバージョンはそのままにして、アップデートはRenovateに任せます）
```console
warning: use of deprecated method `indexmap::IndexMap::<K, V, S>::remove`: `remove` disrupts the map order -- use `swap_remove` or `shift_remove` for explicit behavior.
--> crates/voicevox_core/src/status.rs:274:19
|
274 |         if self.0.remove(&model_id).is_none() {
|                   ^^^^^^
|
= note: `#[warn(deprecated)]` on by default
warning: use of deprecated method `indexmap::IndexMap::<K, V, S>::remove`: `remove` disrupts the map order -- use `swap_remove` or `shift_remove` for explicit behavior.
--> crates/voicevox_core/src/user_dict/dict.rs:64:56
|
64 |         let Some(word) = self.with_words(|words| words.remove(&word_uuid)) else {
| …
```
> fix: `IndexMap::`{`remove`→`shift_remove`}

- crates/voicevox_core/src/__internal/doctest_fixtures.rs
- crates/voicevox_core/src/synthesizer.rs
Rust APIの`Synthesizer`について、以下のFIXMEを解消します。
```rs
pub(crate) mod blocking {
// FIXME: ここのdocのコードブロックはasync版のものなので、`nonblocking`モジュールの方に移した上で、
// (ブロッキング版をpublic APIにするならの話ではあるが)ブロッキング版はブロッキング版でコード例
// を用意する
```
> docs: Rust APIの`Synthesizer`のドキュメントを訂正

- renovate.json5
Renovateのpush通知がノイズになるのを軽減するため、"non-major dependencies"のPRは出しっぱなしにせず、必要に応じて手動トリガーで作成して即マージする運用にする。
<https://github.com/VOICEVOX/voicevox_core/issues/470#issuecomment-2386511058>
これによりRust本体のバージョンについては自動PRは作られなくなるが、 @qryxip が手動で"non-major dependencies"を起動することによりアップデートするようにする。
Discordでの会話:
<https://discord.com/channels/879570910208733277/893889888208977960/1291727262445469878>
#841 はちょうど今CIが通っている状態になっていてマージ可能なので、本PRのマージ後に続けてマージすれば片付く。
> ci: non-major dependenciesでは`dependencyDashboardApproval=true`

- crates/voicevox_core/src/__internal/interop.rs
- crates/voicevox_core/src/voice_model.rs
- crates/voicevox_core_c_api/include/voicevox_core.h
- crates/voicevox_core_c_api/src/c_impls.rs
- crates/voicevox_core_c_api/src/lib.rs
`VoicevoxVoiceModelFile`の次のゲッター関数を、ゲッター関数ではなくする。
- `voicevox_voice_model_file_id`
`uint8_t (*output_voice_model_id)[16]`に吐き出すようにする。
- `voicevox_voice_model_file_get_metas_json`
`voicevox_voice_model_file_create_metas_json`に改名。
ねらいとしては #832 のような設計をC APIでも行うことで、サードパーティのバインディング製作者の労力を減らすため。上記のゲッター関数がゲッターではなくなれば、オブジェクトへのアクセスを完全に管理できる。
<https://github.com/VOICEVOX/voicevox_core/pull/849#issuecomment-2395467528>
#836
CC: @yamachu
> change: C APIからゲッター関数を無くす

- Cargo.lock
- Cargo.toml
- crates/voicevox_core/src/infer.rs
- crates/voicevox_core/src/infer/domains.rs
- crates/voicevox_core/src/infer/domains/talk.rs
- crates/voicevox_core/src/manifest.rs
- crates/voicevox_core/src/status.rs
- crates/voicevox_core/src/voice_model.rs
- crates/voicevox_core_macros/Cargo.toml
- crates/voicevox_core_macros/src/inference_domains.rs
- crates/voicevox_core_macros/src/lib.rs
#737 に向け。また #851 の後にdecode.onnx入りのVVMに対応するときも同様に役に立つはず。
#737
#851 とはコンフリクトしないはず。多分。
> refactor: `InferenceDomainMapValues`のインスタンスをマクロで作る

- .github/workflows/build_and_deploy.yml
- crates/voicevox_core_java_api/README.md
- crates/voicevox_core_java_api/lib/build-android.gradle
- crates/voicevox_core_java_api/lib/build.gradle
- crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/Dll.java
- crates/voicevox_core_java_api/settings.gradle
#802 により不要になり、また #825 の支障になるであろうJavaの`onnxruntime{,_gpu}`パッケージを削除する。
またそれに伴い、`artifactId`をEPごとにリネームするのをやめる。
Refs: #802, #764, #858
Cc: @sevenc-nanashi
> feat(java)!: com.microsoft.onnxruntime/onnxruntime{,_gpu}を削除

- crates/voicevox_core_python_api/python/voicevox_core/_rust/blocking.pyi
- crates/voicevox_core_python_api/python/voicevox_core/blocking.py
- example/python/run.py
Refs: <https://github.com/VOICEVOX/voicevox_core/pull/854#discussion_r1806646080>
> fix: Python APIとexample/python/run.pyの型付けを直す

- crates/voicevox_core/src/status.rs
- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core/src/voice_model.rs
- crates/voicevox_core_c_api/tests/e2e/snapshots.toml
- crates/voicevox_core_python_api/src/lib.rs
#831 で残した次のTODOのうち、`Synthesizer`についてだけ解決します。
````rs
// TODO: `VoiceModelFile`のように、次のような設計にする。
//
// ```
// pub(crate) mod blocking {
//     pub struct Synthesizer(Inner<SingleTasked>);
//     // …
// }
// pub(crate) mod nonblocking {
//     pub struct Synthesizer(Inner<BlockingThreadPool>);
//     // …
// }
// ```
````
#687 のようなことを行うのを円滑にする目的です。今後ソングとかストリーミングとかで`Synthesizer`に手を入れることが予定されているので、その前に早めにやった方がよいと思った次第です。
なんかパフォーマンス的にはもしかしたら破壊的になってるかもですが、もしそうでもパフォーマンスだけならということでcommit typeは`refactor:`としてしまいました。
Refs: #831, #687
そこそこ大きく手を入れているので、今度こそスナップショットテストを作った方がよいかも？
> refactor: `Synthesizer`の実装を`Inner<_, A: Async>`の形にする

- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core/src/voice_model.rs
- crates/voicevox_core_python_api/src/convert.rs
- crates/voicevox_core_python_api/src/lib.rs
非同期APIに関して以下の二つを行う。
* `load_voice_model`にて、ONNX Runtimeの`Session`作成（結構重い）をスレッドプール上でやるようにする。
* Python APIの`Synthesizer`にて、`Closable`の機構が適切に役割を果たすようにする。
> fix: 非同期関連のtodoとfixmeを解消

- crates/voicevox_core_c_api/src/compatible_engine.rs
compatible_engineに、VOICEVOX ENGINEが守る必要がある事前条件を書く。
また、ENGINEから渡されるポインタがアラインメントに沿っているかのアサートを入れる。
([mis-alignedな](https://numpy.org/doc/2.1/dev/alignment.html)データが渡されるとENGINEごと即死するようになるが、どっちにしろ現状のcompatible_engineの実装ではmisalignedであってはならないため)
> fix: compatible_engineにsafety requirementとアサートを入れる

- README.md
- docs/guide/dev/api-design.md
#632 に続く形で、独立した"APIデザイン ガイドライン"を追加する。
内容としてはとりあえず`Rust 以外の言語の API`として、newtype以外も言及したものを用意する。
Refs: #631, <https://github.com/VOICEVOX/voicevox_core/pull/854#discussion_r1803451117>
> docs: "APIデザイン ガイドライン"を追加

- crates/voicevox_core/src/engine/model.rs
- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/AudioQuery.java
- crates/voicevox_core_python_api/python/voicevox_core/_models.py
`AudioQuery`に`pause_length{,_scale}`を追加する。ただしそれぞれ`null`と`1.`のみを許し、無音時間調整自体はまだ実装しない。
Refs: VOICEVOX/voicevox_engine#1308, VOICEVOX/voicevox_engine#1425
> feat: `pause_length{,_scale}`をデフォルト値限定で受け入れる

- Cargo.lock
- Cargo.toml
- crates/voicevox_core_c_api/src/lib.rs
- crates/voicevox_core_c_api/tests/e2e/snapshots.toml
Resolves #859.
Refs: VOICEVOX/ort#8, VOICEVOX/ort#9, VOICEVOX/ort#10
> chore(deps)!: bump ort

- .github/workflows/build_and_deploy.yml
- .github/workflows/build_and_deploy_downloader.yml
- .github/workflows/download_test.yml
- .github/workflows/test.yml
#323 以降Cargoコマンドに付けていた`-vv` (`--verbose --verbose`)を`-v` (`--verbose`)にする。理由としてはこの二年で依存ライブラリが増大したことにより、ログ出力の量がMB単位になる場合が出てきたため。
Cargoコマンドによってはギリギリプレビューできる範囲に収まっているが、個々について考えるのも面倒だし、一貫性の観点からも一括して置き換えてしまう。
Refs: #323
> ci: `-vv` → `-v`

- crates/test_util/build.rs
- crates/test_util/compatible_engine.h
- crates/test_util/src/typing.rs
- crates/voicevox_core_c_api/Cargo.toml
- crates/voicevox_core_c_api/src/compatible_engine.rs
- crates/voicevox_core_c_api/tests/e2e/testcases/compatible_engine.rs
ストリーミング処理をC APIとして実装
testcaseとして一括変換・ストリーム変換の二つの生成結果を追加し、元の生成音声と比較して十分近いことを確かめた
close #866
> Streaming decoder for compatible engine

- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core_python_api/python/voicevox_core/_rust/blocking.pyi
- crates/voicevox_core_python_api/src/lib.rs
- docs/guide/dev/api-design.md
`Synthesizer::render`の引数の範囲指定部分を次のようにする。
Rust API: `range: Range<usize>`
Python API: `start: int, stop: int`
以前の議論:
<https://github.com/VOICEVOX/voicevox_core/pull/870#discussion_r1835573095>
CC: @Yosshi999
> feat!: `render`の引数の範囲指定部分を各言語の慣習に合わせる

- crates/voicevox_core/src/__internal/interop.rs
- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core_c_api/src/compatible_engine.rs
#875 で追加された以下のコードに対し、
<https://github.com/VOICEVOX/voicevox_core/blob/d8e021e1f132582c6167a8ab948bf5dfed059ed9/crates/voicevox_core_c_api/src/compatible_engine.rs#L384-L385>
以下の変更を加える。
`MARGIN_WIDTH`: Rust APIのものを持って来るようにすることで重複を避ける
`FEATURE_SIZE`: 出力サイズのチェック時に失敗したとき、`ncols`が`FEATURE_SIZE`と異なるならパニックメッセージを別のものにする
Refs: #875
Cc: @Yosshi999
> feat: fix up #875 about `MARGIN_WIDTH` and `FEATURE_SIZE`

- example/python/run-asyncio.py
- example/python/run.py
次のFIXMEを解消する。
> ```py
>     # FIXME: 流石に多くなってきたので、`dataclass`化する
> ```
> refactor: Python APIのexampleのCLI引数をdataclass化

- .github/workflows/build_and_deploy.yml
- .github/workflows/build_and_deploy_downloader.yml
- .github/workflows/test.yml
理由: actions/runner-images#10721
前回のは #801
> remove!: macOS 12のサポートを切る

- Cargo.lock
- Cargo.toml
- crates/voicevox_core_c_api/src/lib.rs
次の二つの回避のため。
* [RUSTSEC-2024-0402](https://rustsec.org/advisories/RUSTSEC-2024-0402)
* [RUSTSEC-2024-0404](https://rustsec.org/advisories/RUSTSEC-2024-0404)
cargo-denyが反応しているやつなので、最優先。
@Hiroshiba
> chore(deps): bump `anstream` to 0.6.18, `hashbrown@15` to 0.15.2

- Cargo.lock
- Cargo.toml
- crates/voicevox_core/src/infer.rs
- crates/voicevox_core/src/infer/runtimes/onnxruntime.rs
- crates/voicevox_core/src/infer/session_set.rs
- crates/voicevox_core/src/status.rs
- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core_macros/src/inference_domain.rs
- crates/voicevox_core_python_api/python/test/test_asyncio_user_dict_load.py
- example/python/run-asyncio.py
- example/python/run.py
非同期APIにおける推論に[`ort::Session::run_async`](https://docs.rs/ort/2.0.0-rc.4/ort/struct.Session.html#method.run_async)を使うようにする。これにより、推論がキャンセル可能になる。
#888 の影響を受け推論が失敗するので、CIを通すため、Python APIのテストとexampleについては（すべてのプラットフォームで）`cpu_num_threads=max(multiprocessing.cpu_cout(), 2)`とする。
BREAKING-CHANGE: 非同期APIにおいて、INTRA Thread Countが`1`だと推論がすべてエラーになるようになる。
Resolves #687.
Refs: VOICEVOX/ort#11
> feat!: `RunAsync`を使う

- Cargo.lock
- Cargo.toml
- deny.toml
[RUSTSEC-2024-0421](https://rustsec.org/advisories/RUSTSEC-2024-0421)が登録されたことによりcargo-denyが反応するようになったため。
See-also: [Unicode License v3](https://spdx.org/licenses/Unicode-3.0.html)
> chore(deps): bump `url` to v2.5.4

- .github/workflows/build_and_deploy.yml
- crates/voicevox_core/src/error.rs
- crates/voicevox_core/src/publish.rs
- crates/voicevox_core/src/result_code.rs
- crates/voicevox_core_c_api/src/helpers.rs
> chore: [0.15] remove obsolete parts

- .github/workflows/build_and_deploy.yml
- .github/workflows/test.yml
release-0.15ブランチにmacos-12部分が残っていたので、macos-13にアップデートします。
また`release`始まりにしてしまったのでブランチプロテクションかかってしまったかも･･･。
あとで消しておきます･･･。
メインブランチの変更は↓
- https://github.com/VOICEVOX/voicevox_core/pull/884/files
> add: [release-0.15] macos-12 to macos-13

- crates/voicevox_core/src/nonblocking.rs
- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core_python_api/python/voicevox_core/_rust/asyncio.pyi
- crates/voicevox_core_python_api/python/voicevox_core/asyncio.py
- crates/voicevox_core_python_api/python/voicevox_core/blocking.py
非同期APIの
1. モジュール
2. `cpu_num_threads`
において、 #902 についての注意書きを書く。
> docs: #902 の注意書き

- .github/actions/cargo-binstall-cbindgen/action.yml
- .github/workflows/build_and_deploy.yml
`$OS`となってますが、おそらく正解は`$RUNNER_OS`です。
release-0.15でビルドするとなぜかcbindgenがインストールされておらず、いろいろ調べたところここじゃないかとなりました。
よくよく確認すると、この前[macos-12をmacos-13に上げるrelease-0.15へのPRのGithub Workflow](https://github.com/VOICEVOX/voicevox_core/actions/runs/12459741230/job/34776980065)でもそこで落ちてました。
２箇所変更していますが、`.github/actions/cargo-binstall-cbindgen/action.yml`側は現在のmainブランチには存在してません。
`.github/workflows/build_and_deploy.yml`側の`.exe`を付けるか判定はこれでより正しくなるはず。
でも`$OS`はWindowsでだけ`Windows_NT`と値が入ってるので、switch caseの仕様によっては正しく動作してるかも。
試してみた結果が[こちら](https://github.com/Hiroshiba/test_actions/actions/runs/12496485243/job/34868255598#:~:text=6s,OS%3A%20windows%2Dlatest%22)
なんで以前はちゃんとOS判定できてた？のか不明。
判定はできてなくて、cbindgenがなぜか入ってたのか、あるいはキャッシュがヒットしてたとか･･･？
> fix: [release-0.15] os to runner_os

- crates/voicevox_core/src/__internal/doctest_fixtures.rs
- crates/voicevox_core/src/__internal/interop.rs
- crates/voicevox_core/src/blocking.rs
- crates/voicevox_core/src/lib.rs
- crates/voicevox_core/src/nonblocking.rs
- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core_c_api/src/c_impls.rs
- crates/voicevox_core_c_api/src/compatible_engine.rs
- crates/voicevox_core_c_api/src/helpers.rs
- crates/voicevox_core_c_api/src/lib.rs
- crates/voicevox_core_java_api/src/synthesizer.rs
- crates/voicevox_core_python_api/src/lib.rs
api-design.mdでの方針に従い、Rust APIの表層から`{Initialize,Synthesis,Tts}Options`を消してビルダースタイルにする。
<https://github.com/VOICEVOX/voicevox_core/blob/babb3b764313ee43cef57e1006a8500785c96064/docs/guide/dev/api-design.md?plain=1#L13>
Refs: #388
帰省の途中、航空機内で実装しました。これが丁度よさそうだったので…
> refactor: Rust APIの`Synthesizer`のメソッドをビルダースタイルに

- crates/voicevox_core_java_api/lib/src/test/java/jp/hiroshiba/voicevoxcore/blocking/SynthesizerTest.java
> test: Java APIの`tts`のテストが動いてなかったのを修正

- .github/workflows/test.yml
- crates/voicevox_core_python_api/Cargo.toml
これをやらないとwhl名が"…-cp38-abi3-…"のままになり、誤解を生じさせることが予想できるため。
See-also: https://pyo3.rs/v0.23.4/building-and-distribution#minimum-python-version-for-abi3
> fix: fix up #915: bump the PyO3's `abi3` feature to `abi3-py310`

- crates/voicevox_core/src/lib.rs
確か何かをしているときに間違えて消したままコミットしてしまい、レビューも素通りしてしまったという経緯だったような記憶。
> fix!: 間違って消していた`__internal`の`#[doc(hidden)]`を復活

- crates/voicevox_core/src/lib.rs
- crates/voicevox_core/src/metas.rs
- crates/voicevox_core/src/status.rs
- crates/voicevox_core/src/voice_model.rs
- crates/voicevox_core_c_api/src/lib.rs
- crates/voicevox_core_java_api/src/voice_model.rs
- crates/voicevox_core_python_api/src/lib.rs
#370 から続いている、Rust APIのnewtypeの形を変える。
当時どういう意図だったのかは正確にはわかりませんが、二年経っての現状を鑑みても、「透過的」であるように振る舞った方がよいのではないかと思った次第です。
（一応当時の時点で私はVOICEVOX ONNX Runtimeのアイデアを思い付いて提案してたと思うので、Rust APIを前提にしていたとは思います）
See-also: https://rust-lang.github.io/api-guidelines/type-safety.html#newtypes-provide-static-distinctions-c-newtype
> feat!: Rust APIのnewtypeをopenなstructにし、`Raw`を消す

- crates/voicevox_core/src/devices.rs
- crates/voicevox_core/src/engine/model.rs
- crates/voicevox_core/src/error.rs
- crates/voicevox_core/src/metas.rs
- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core/src/user_dict/word.rs
- crates/voicevox_core_c_api/src/helpers.rs
- crates/voicevox_core_java_api/src/common.rs
- crates/voicevox_core_python_api/src/convert.rs
\[追記\] 目的としては将来の後方互換性の確保のため。
いくつかのenumだけこのようにする。
```rs
#[expect(
clippy::manual_non_exhaustive,
reason = "バインディングを作るときはexhaustiveとして扱いたい"
)]
pub enum … {
…,
#[doc(hidden)]
__NonExhaustive,
}
```
> feat!: `#[non_exhaustive]`

- .github/workflows/download_test.yml
- crates/downloader/src/main.rs
VVMやVOICEVOX ONNX Runtimeのみをダウンロードする(`--only models onnxruntime`)用途が見えてきてる今、「コア」とはC APIのことであるとはっきりと明示した方がよいかなと思った次第です。
BREAKING-CHANGE: `core` → `c-api`。
BREAKING-CHANGE: `-v, --version` → `--c-api-version`。
BREAKING-CHANGE: `--core-repo` → `--c-api-repo`。
> feat!: [downloader] rename `core` to `c-api`

- crates/voicevox_core_python_api/pyproject.toml
Maturinの機能で埋め込む。whlの内容は次のようになる。
```diff
├── voicevox_core
│   └── …
└── voicevox_core-{version}.dist-info
+    ├── licenses
+    │   └── LICENSE
├── METADATA
├── RECORD
└── WHEEL
```
Refs: #938
ちなみにONNX Runtimeのwhlでは、dist-infoではなくonnxruntime/下に無造作に置かれていました。
あとreadmeについては今こうなっていますが、
<https://github.com/VOICEVOX/voicevox_core/blob/8112ecb297e96d20aa1aa203ae7f9886b98456ea/crates/voicevox_core_python_api/pyproject.toml#L16-L17>
どうもMaturinが自動でREADME.mdを見つけて埋め込むようで、今METADATAには[crates/voicevox_core_python_api/README.md](https://github.com/VOICEVOX/voicevox_core/blob/8112ecb297e96d20aa1aa203ae7f9886b98456ea/crates/voicevox_core_python_api/README.md)がそのまま埋め込まれています。
> feat: whlにLICENSEファイルを含める

- docs/guide/user/usage.md
- example/cpp/windows/README.md
- example/cpp/windows/simple_tts/simple_tts.cpp
- example/python/README.md
- example/python/run-asyncio.py
- example/python/run.py
> docs: ダウンローダー周りの記述を更新

- docs/ghpages/apis/python_api/conf.py
Resolves: #951
数時間調べたけど、これ以外に方法は無さそう。
> docs: [Python] 型エイリアス系へのリンクについてワークアラウンド

- crates/voicevox_core/src/devices.rs
- crates/voicevox_core_c_api/tests/e2e/testcases/compatible_engine.rs
- crates/voicevox_core_c_api/tests/e2e/testcases/global_info.rs
- crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/GlobalInfo.java
- crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/blocking/Onnxruntime.java
- crates/voicevox_core_java_api/src/onnxruntime.rs
- crates/voicevox_core_python_api/python/voicevox_core/_models/__init__.py
- crates/voicevox_core_python_api/src/convert.rs
- crates/voicevox_core_python_api/src/lib.rs
#941 の続き。
#941 において`SupportedDevices`も`#[non_exhaustive]`にしたが、一つ困った問題が生じた。`SupportedDevices`のフィールドは現状全部requiredな形になっている。そして`SupportedDevices`はシリアライズ（オブジェクト → JSONの変換）と共にデシリアライズ（JSON → オブジェクトの変換）もできるようになっているため、このままだとフィールドを追加するのに困る。特に**近いうちに**ROCmを入れたい。
解決法としては次の二つが考えられた。
1. `cuda`と`dml`、あるいは`cpu`も含めた全てのフィールドをoptionalにする
2. これから追加するであろう`rocm`とかをoptionalにし、今あるものはrequiredのままにする
3. デシアライズ（JSON → `SupportedDevices`）の禁止
このPRでは3.を選んだ。というのもそもそも`SupportedDevices`のコンストラクトは不要であるべきだからである。
BREAKING-CHANGE: Rust, Python, Java APIにおいてJSON → `SupportedDevices`の変換が禁止される。
> feat!: `SupportedDevices`からデシアライズ機能を剥奪

- crates/voicevox_core_python_api/poetry.lock
- crates/voicevox_core_python_api/pyproject.toml
目当てはv1.7.6の PyO3/maturin#2332 。
あとなんかPython 3.13t（GIL抜きPython）用whlのビルドとかもできるっぽい…
（今後世界的にGIL抜きPythonの需要がどうなるかわかんないので、何とも言えない。もしかすると一年ちょっとくらいで流行る可能性もありうる？）
PyO3が古いままなのが懸念点だったが、なんかまだ普通に動くっぽいので最新版であるMaturin v1.8.1に上げてしまう。
> build: bump Maturin to 1.8.1

- .github/workflows/build_and_deploy.yml
#947 に続き。
Refs: #938
ちなみに今C APIだけREADME.mdはREADME.txtとして入っているようです。
(blameしたら #196 の初案段階からあって、誰も言及していないっぽい)
なのでPython APIやRust APIとはちょっと違う形になってるかと思います。
\[追記\] あと今Android用にだけリリースしているJava APIですが、そっちはちょっと調査が必要そう。どうもそういう文化が無い（!?）ようなので…
> build: C APIにもLICENSEファイルを同梱

- crates/voicevox_core/src/blocking.rs
- crates/voicevox_core/src/engine/audio_file.rs
- crates/voicevox_core/src/lib.rs
- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core_python_api/python/voicevox_core/__init__.py
- crates/voicevox_core_python_api/python/voicevox_core/_rust/blocking.pyi
- crates/voicevox_core_python_api/python/voicevox_core/blocking.py
- crates/voicevox_core_python_api/src/lib.rs
- example/python/run.py
以下のRust APIのアイテムと、それらに対応するPython APIのものを封印する。
- `voicevox_core::wav_from_file`
- `voicevox_core::blocking::Synthesizer::{,precompute_}render`
- `voicevox_core::blocking::synthesizer::PrecomputeRender`
Resolves: #970
CC: @Yosshi999
> feat!: ストリーミングAPIを封印する

- crates/voicevox_core/src/engine/open_jtalk.rs
- crates/voicevox_core/src/error.rs
- crates/voicevox_core/src/infer/runtimes/onnxruntime.rs
- crates/voicevox_core/src/lib.rs
- crates/voicevox_core/src/metas.rs
- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core/src/user_dict/dict.rs
- crates/voicevox_core/src/user_dict/word.rs
- crates/voicevox_core/src/version.rs
- crates/voicevox_core/src/voice_model.rs
- crates/voicevox_core_c_api/include/voicevox_core.h
- crates/voicevox_core_c_api/src/lib.rs
- crates/voicevox_core_c_api/src/result_code.rs
- docs/ghpages/apis/c_api/doxygen/Doxyfile
Rust API側において`#[doc(alias(…))]`機能でC APIの名前に紐付かせ、C API側からはそのエイリアスに対してリンクを張る (`?search=…`)。
(補足として、エイリアスは完全一致でしか引っ掛からないためRust APIでの検索を阻害することは基本無い)
ユーザーにRust APIのことを意識させることによって、 #975 のようなことに対する緩和をねらう。
See-also: https://doc.rust-lang.org/rustdoc/advanced-features.html#add-aliases-for-an-item-in-documentation-search
> docs: [C] 各アイテムからRust APIにリンクを張る

- README.md
タイトルの通りで
- https://github.com/VOICEVOX/voicevox_core/issues/938
の解決プルリクエストです。
VOICEVOX COREのソースコードとビルド成果物はMITライセンスだということがわかりやすくなりました。
あとこのREADMEを`c_api`ディレクトリに放り込んでおけば、`voicevox_core.dll`とか`voiecvox_core.so`とかもちゃんとMITライセンスだということが分かりやすいはず！
#938 
「VOICEVOX CORE のソースコード及びビルド成果物のライセンスは」
と書いてるけど、これは多分もっと短くして
「VOICEVOX CORE のライセンスは」
でも問題ない気はしてます。どっちの方がいいですかねぇ。。
あとreleasesに置いてある過去のコアライブラリはライセンスが違うことを残しておいてみました。
ここに書く必要があるかわからないけど、差分が少なくなるのでとりあえず書き換えただけです。
（この文面じゃないとダメという意図ではない）
> docs: READMEのライセンス周りの表記をわかりやすくする

- crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/AccentPhrase.java
- crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/AudioQuery.java
- crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/CharacterMeta.java
- crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/GlobalInfo.java
- crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/Mora.java
- crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/StyleMeta.java
- crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/UserDictWord.java
- crates/voicevox_core_python_api/python/voicevox_core/_models/__init__.py
脱Pydanticと脱GSONをv0.17でやることを前提にし、ちょっと弱めの表現にしてある。
Resolves: #963
Refs: #960, #984
> docs: [Python, Java] 各アイテムにPydanticとGSONの廃止案内を載せる

- crates/voicevox_core_python_api/python/voicevox_core/_rust/asyncio.pyi
- crates/voicevox_core_python_api/python/voicevox_core/_rust/blocking.pyi
- crates/voicevox_core_python_api/src/lib.rs
現在`VoiceModelFile`と`Onnxruntime`には通常のコンストラクタが存在しない。正確に言えば`__new__`は存在してはいるが、それを呼ぶと`TypeError`になる。その「存在しないコンストラクタ」について次の2つを行う。
1. エラーメッセージの改善。
Before (PyO3(?)が出しているやつ):
```console
TypeError: No constructor defined
```
After:
```console
TypeError: `Onnxruntime` does not have a normal constructor. Use `Onnxruntime.load_once` or `Onnxruntime.get` to construct
```
2. pyiに`__new__`について記述。
シグネチャは`(cls, *args, **kwargs) -> NoReturn`。
**これをやらないとデフォルトコンストラクタ (`() -> Self`)が存在することになってしまう**。
ちなみにPyright/Pylanceとmypy（多分）にのみ影響。Sphinxには`__new__`の記述は無視されてしまった。
> feat: [Python] 「存在しないコンストラクタ」についてケア

- crates/voicevox_core/src/lib.rs
rustdocの冒頭だけですます調になっていたので、これをである調に直すことで統一する。
> docs: APIドキュメントはである調に統一

- crates/voicevox_core_java_api/src/common.rs
- crates/voicevox_core_python_api/src/lib.rs
- example/python/README.md
次のようなメッセージをやめる。
```console
[WARNING] voicevox_core_python_api: デストラクタにより`Synthesizer`のクローズを行います。通常は、可能な限り`__exit__`でクローズするようにして下さい
```
カジュアルな用途だと相当にうっとおしいはずなので。
> feat: [Python, Java] fix up #832: `Drop`のメッセージをやめる

- crates/voicevox_core/src/metas.rs
- crates/voicevox_core_c_api/include/voicevox_core.h
- crates/voicevox_core_c_api/src/lib.rs
- crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/CharacterMeta.java
- crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/StyleMeta.java
- crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/StyleType.java
- crates/voicevox_core_python_api/python/voicevox_core/_models/__init__.py
Sphinxの表示が壊れており警告も出ている状態だったため、それを直すとともに、以下のような記述で統一する。
> <i>キャラクター</i>のメタ情報。
> <i>スタイル</i>のメタ情報。
> VOICEVOXにおける、ある[<i>キャラクター</i>]のある[<i>スタイル</i>]を指す。
[<i>キャラクター</i>]: https://voicevox.github.io/voicevox_core/apis/rust_api/voicevox_core/struct.CharacterMeta.html
[<i>スタイル</i>]: https://voicevox.github.io/voicevox_core/apis/rust_api/voicevox_core/struct.StyleMeta.html
> docs: APIドキュメントの`{Character,Style}Meta`周りの記述を統一

- crates/voicevox_core_python_api/python/voicevox_core/_rust/asyncio.pyi
- crates/voicevox_core_python_api/python/voicevox_core/_rust/blocking.pyi
- crates/voicevox_core_python_api/src/lib.rs
> feat!: [Python] デフォルト引数の前に一律で`*,`を挟む

- crates/voicevox_core/src/__internal/interop.rs
- crates/voicevox_core/src/user_dict/mod.rs
- crates/voicevox_core/src/user_dict/word.rs
- crates/voicevox_core_c_api/include/voicevox_core.h
- crates/voicevox_core_c_api/src/lib.rs
- crates/voicevox_core_c_api/tests/e2e/testcases/user_dict_load.rs
- crates/voicevox_core_c_api/tests/e2e/testcases/user_dict_manipulate.rs
- crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/UserDictWord.java
- crates/voicevox_core_java_api/lib/src/test/java/jp/hiroshiba/voicevoxcore/blocking/UserDictTest.java
- crates/voicevox_core_python_api/python/test/test_asyncio_user_dict_load.py
- crates/voicevox_core_python_api/python/test/test_asyncio_user_dict_manipulate.py
- crates/voicevox_core_python_api/python/test/test_blocking_user_dict_load.py
- crates/voicevox_core_python_api/python/test/test_blocking_user_dict_manipulate.py
- crates/voicevox_core_python_api/python/voicevox_core/_models/__init__.py
1. C APIとRust APIのみ`priority`のデフォルトが`5`ではなく`0`になっていたため、`5`に合わせることでPython, Java, VOICEVOX ENGINEに合わせる。
2. VOICEVOX ENGINEにならった場合、`surface`, `pronounciation`と同様`accent_type`もrequiredであるはずなので、そうしてしまう。
3. `impl Default for UserDictWord`を削除
> fix!: various fix for `UserDictWord`

- crates/voicevox_core/src/user_dict/word.rs
- crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/UserDictWord.java
- crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/blocking/UserDict.java
- crates/voicevox_core_java_api/src/common.rs
- crates/voicevox_core_java_api/src/user_dict.rs
- crates/voicevox_core_python_api/python/test/test_asyncio_user_dict_manipulate.py
- crates/voicevox_core_python_api/python/test/test_blocking_user_dict_manipulate.py
- crates/voicevox_core_python_api/python/voicevox_core/_models/__init__.py
- crates/voicevox_core_python_api/python/voicevox_core/_rust/__init__.pyi
- crates/voicevox_core_python_api/src/convert.rs
- crates/voicevox_core_python_api/src/lib.rs
`UserDictWord`の**シリアライズ形式だけを**ENGINEと同じにする。
COREで`UserDict.save`したユーザー辞書をENGINEで`/import_user_dict`、およびENGINEで`/user_dict`でダンプしたものをCOREで`UserDict.load`できることを確認。
`UserDictWord`として編集できる部分以外、例えば`inflectional_type`などをJSON上で編集するとエラーになるようにする。また`word_type`のデシリアライズについては、`PartOfSpeechDetail`を線形探索することで判別する。
BREAKING-CHANGE: シリアライズ形式がENGINEと同じになる。
BREAKING-CHANGE: Pythonにおいて、Pydanticが外される (#960 の部分達成)。
BREAKING-CHANGE: Pythonにおいて、dataclassとして`frozen`となる。
BREAKING-CHANGE: Pythonにおいて、コンストラクト時点で各種バリデートがされるように。
BREAKING-CHANGE: Javaにおいて、GSONが外される。
See-also: #946
> feat!: ユーザー辞書単語のJSON表現をENGINEと同じにする

- README.md
#1017 における以下のものを解決する。
> - [ ] `Releases にビルド済みのコアライブラリ（.so/.dll/.dylib）があります。`　←ドメイン用語が今と違うかも。「コアライブラリ」は`.zip`を指すけどたぶんなくなってる。「C API」があります、もしくは「各言語向けのAPIライブラリ」がありますとか？（ちょっと適当です）
> - [ ] `コアライブラリ`という名称は古いかも。コアAPIとか？
> - [ ] `model フォルダにある onnx モデルのみが利用できます`　←古そう
「コアライブラリ」は「C APIライブラリ」、あるいは単に「（ビルド済み）ライブラリ」とする。
sample.vvmのみが利用可能と言っていた部分については、単に消してしまう。
（もし代わりに何か書くとしたら、「VOICEVOX ONNX Runtimeの代わりに純正ONNX Runtimeを使うことができますが、その場合はsample.vvmのみ利用可能です」みたいな感じになると思います）
Refs: #1017
> docs(fix): readmeの古い記述を更新

- docs/guide/dev/vvm.md
- docs/guide/user/usage.md
voicevox_fat_resourceを参照していた部分をvoicevox_vvmのリンクに置き換えました。
https://github.com/VOICEVOX/voicevox_core/issues/922
こちらのissueの議論の流れを一通り読ませていただいて、現在VVMはvoicevox_fat_resourceリポジトリではなく、voicevox_vvmリポジトリで管理されることになったという認識です。
よってドキュメントのリンクなども更新しておいたほうがよいのではないかと思いPR作成いたしました。
https://github.com/VOICEVOX/voicevox_core/issues/922
> docs: vvm周りのリンクを更新

- crates/voicevox_core/src/__internal/interop.rs
- crates/voicevox_core/src/infer.rs
- crates/voicevox_core/src/infer/runtimes/onnxruntime.rs
- crates/voicevox_core/src/infer/session_set.rs
- crates/voicevox_core/src/status.rs
- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core_python_api/python/voicevox_core/_rust/asyncio.pyi
- crates/voicevox_core_python_api/src/lib.rs
デフォルトで`OrtApi::RunAsync`ではなく`OrtApi::Run`を使うようにする。その代わり非同期APIにおけるdecode系の推論のみ、`cancellable`というオプションで`RunAsync`を使うようにする。predict系の推論は完全にキャンセル不可となる。
BREAKING-CHANGE: 推論の挙動の変更。
Refs: https://github.com/VOICEVOX/voicevox_core/issues/968#issuecomment-2683857839
> feat!: デフォルトで`RunAsync`ではなく`Run`を使う

- crates/voicevox_core_python_api/src/lib.rs
#1025 のテストを書こうとして発覚。
Rustの`Result<T, _>`は`IntoIterator<Item = T>`であり、`Vec<_>`とするところを誤って`Result<Vec<_>, _>`としてしまったために`voicevox_core.asyncio.Synthesizer.create_accent_phrases`が`list[list[AccentPhrase]]`を返していた。
通常[`for x in result`のようなことをすれば怒られる](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_lint/for_loops_over_fallibles/static.FOR_LOOPS_OVER_FALLIBLES.html)が、関数の引数として入れる分には警告が出なかった。
> fix: [Python] fix up #962: async版`create_accent_phrases`を直す

- .github/workflows/audit.yml
- .github/workflows/build_and_deploy.yml
- .github/workflows/build_and_deploy_downloader.yml
- .github/workflows/licenses.yml
- .github/workflows/test.yml
`ubuntu-20.04`のbrownoutが開始したため。
See-also: https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/
> build!: Ubuntu 20.04のサポートを切る

- crates/downloader/src/main.rs
downloaderを使っているときに遭遇したエラーメッセージに違和感があったため、より自然な表現になるよう以下のように修正しました。
`{repo}`の`{tag_name}`の中から条件に合致するビルド**が**見つけることができませんでした
↓
`{repo}`の`{tag_name}`の中から条件に合致するビルド**を**見つけることができませんでした
> fix: downloaderの違和感のあるエラーメッセージを修正

- crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/GlobalInfo.java
- crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/SupportedDevices.java
- crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/blocking/Onnxruntime.java
- crates/voicevox_core_java_api/lib/src/test/java/jp/hiroshiba/voicevoxcore/InfoTest.java
- crates/voicevox_core_java_api/src/onnxruntime.rs
TODOを解消する形。
BREAKING-CHANGE: `GlobalInfo$SupportedDevices` → `SupportedDevices`。
> fix!: [Java] fix up #802: `SupportedDevices`を移動

- crates/voicevox_core_java_api/lib/build.gradle
Windowsで`gradle javadoc`を試みるとこうなるので、UTF-8を指定することで直す。
> build(fix): [Java] `javadoc.options.encoding = 'UTF-8'`

- .github/workflows/check-release-target-tuples.yml
#1006 の副産物。deny.tomlのこの部分をテストする。
<https://github.com/VOICEVOX/voicevox_core/blob/60790a18924b81404b086ffeffb2ac68bded230e/deny.toml#L2-L14>
See-also: rust-lang/rust#125579
See-also: https://rust-lang.zulipchat.com/#narrow/channel/131828-t-compiler/topic/--print.20host.5B-tuple.7C-triple.5D/near/452327295
> ci: `Check release target tuples`ワークフローを追加

- docs/ghpages/apis/index.html
APIドキュメントのポータルのTODOを外し、Java APIを一旦隠すようにしました。
これで↓をcloseできるはず･･･？
- https://github.com/VOICEVOX/voicevox_core/issues/1017
close #1017
> docs: APIドキュメントのポータルのTODOを外し、Java APIを一旦隠す

- crates/voicevox_core_python_api/python/voicevox_core/_rust/asyncio.pyi
- crates/voicevox_core_python_api/python/voicevox_core/_rust/blocking.pyi
誤: `*args: tuple[object], **kwargs: dict[object, object]`
生: `*args: object, **kwargs: object`
普通にユーザーが目にする範囲ではあるので、直す。
> fix(python): ダミー`__new__`の型付けを直す

- CONTRIBUTING.md
- crates/voicevox_core_python_api/README.md
C APIとJava APIにはテスト方法を書いてあるが、Rust APIとPython APIに書かれてなかったので書く。また、CONTRIBUTING.mdにも案内を書く。
Resolves: #1051
> docs: テストの方法を案内する

- crates/voicevox_core_java_api/lib/src/main/java/jp/hiroshiba/voicevoxcore/blocking/UserDict.java
- crates/voicevox_core_java_api/lib/src/test/java/jp/hiroshiba/voicevoxcore/blocking/UserDictTest.java
- crates/voicevox_core_java_api/src/common.rs
- crates/voicevox_core_java_api/src/user_dict.rs
BREAKING-CHANGE: `UserDict`のメソッドの引数と返り値を変更する。
> feat(java)!: `String uuid` → `UUID uuid`

- .github/workflows/build_and_deploy_downloader.yml
タイトルのとおりです。
0.16に間に合わせられない気がするので、ちょっとダウンローダーだけ署名なしにしようと思います！
> fix(ci): downloaderビルドのenvironment指定を直す

- docs/guide/user/usage.md
- example/python/README.md
#926 によってwhlファイルの名前に含まれるPythonバージョンが、`cp38`から`cp310`に変更されましたが、ドキュメントが追従していなかったので更新します。
ref #915 
ref #926
> docs: ドキュメント内のwhlファイルの古いバージョン記述を更新

- deny.toml
Refs: #1020
[`audit`が一ヶ月間落ち続けている](https://github.com/VOICEVOX/voicevox_core/actions/workflows/audit.yml)のもなんとかしたい。毎日通知が来る。
(ちなみに問題なのはring v0.16に対する[RUSTSEC-2025-0010](https://rustsec.org/advisories/RUSTSEC-2025-0010)。これに対する真っ当な対処方はoctocrabなどのメジャーバージョンアップデートなので、ignoreでの対応は避けたい。毎日落ち続けてる方がまだよい)
\[追記\] とはいえこの一ヶ月にPyO3やらTokioやらCrossbeamの`vulnerability`が入ってきてるようだし、こういうのも認知できなくなるのはよくない。そろそろ対応が必要。もちろん真っ当な方の対処法で。
> chore: deny.tomlの`bans`を直す

- .github/workflows/check-shebangs-and-filemodes.yml
#1077 の続き。
このリポジトリ内のすべてのファイルに対し、以下のチェックを義務付ける。
```bash
if has_shebang && ! is_executable; then
echo 'A shebanged file must be executable (note: if you are using Windows, please change the filemode with `git update-index --chmod+x`)'
exit 1
fi
if is_shellscript && ! is_executable; then
echo 'A shell script file must be executable (note: if you are using Windows, please change the filemode with `git update-index --chmod+x`)'
exit 1
fi
if is_executable && ! has_shebang; then
echo 'An executable blob must have a shebang'
exit 1
fi
```
> ci: `check-shebangs-and-filemodes`ワークフローを追加

- Cargo.lock
- Cargo.toml
- crates/downloader/Cargo.toml
私のArch Linuxの/usr/bin/gccがv15になったことで trishume/syntect#583 を踏み抜いたため。
[rust-onig/rust-onig](https://github.com/rust-onig/rust-onig)のmainブランチでは解決されている問題なのでリリースを待てばよい話ではあるが、rust-onigの活動が最近あまり活発ではないためすぐにリリースが行われることが期待できない。下手するとGHAの`ubuntu-latest`のGCCが15になっても行われないかもしれない。
そもそも[Oniguruma](https://github.com/kkos/oniguruma)なんて使わなくていいはずなので、comrakの`default-features`を切ることで対応する。
> chore(deps): disable `comrak`'s `default-features`

- crates/downloader/Cargo.toml
- crates/voicevox_core_c_api/Cargo.toml
- crates/voicevox_core_java_api/Cargo.toml
`default-features = false`は`workspace.dependencies`と各パッケージ側の`dependencies`の両方に記述する必要は無いため、前者のみを書くように統一する。
> refactor(cargo): `default-features = false`を`workspace`側のみに

- .github/workflows/build_and_deploy.yml
- .github/workflows/build_and_deploy_downloader.yml
- .github/workflows/test.yml
[brownoutが始まった](https://github.com/actions/runner-images/issues/12045)ため。
BREAKING-CHANGE: リリースにおけるWindowsのランナーが`windows-2022`になる。ただしVOICEVOX ONNX Runtimeの方は元々`windows-2022`でビルドされているため、通常の用途においては特に変わらないはず。
> build!: drop `windows-2019`

- .github/workflows/build_and_deploy.yml
GHAのUbuntuイメージ備え付けの`$ANDROID_NDK` ([現時点ではバージョン27](https://github.com/actions/runner-images/blob/4bd4d1bbeb9f9e54aa01e4e2ee8adc0271844a63/images/ubuntu/Ubuntu2204-Readme.md))を使う。"latest"としてr28もあるようだが、LTSの方を選んでおく。
これにより、AndroidビルドにおけるC++シンボルの問題が解決されるはずである。
Resolves: #1103
Closes: #1105
> build(android): use default `$ANDROID_NDK`

- crates/downloader/src/main.rs
#1098 で追加した`-t, --tries`のhelp表示を直す。「リトライ回数」は不正確なので「試行回数」とし、[`value_name`](https://docs.rs/clap/4/clap/struct.Arg.html#method.value_name)も`<NUMBER>`にしておく。Wgetと同じようにする。
```
-t, --tries <NUMBER>
ダウンロードにおける試行回数。'0'か'inf'で無限にリトライ [default: 5]
```
```console
❯ man wget 2>/dev/null | rg -e '-t number' -A 3
-t number
--tries=number
Set number of tries to number. Specify 0 or inf for infinite retrying.  The default is to retry 20 times, with the  exception  of  fatal  errors
like "connection refused" or "not found" (404), which are not retried.
```
#1109 をやっているときに気付きました。
> fix(downloader): `-t, --tries`のhelpを正確に書く

- .github/workflows/build_and_deploy.yml
- .github/workflows/build_and_deploy_downloader.yml
- CHANGELOG.md
- Cargo.toml
- crates/downloader/Cargo.toml
- crates/downloader/src/main.rs
#1115 の結論によりダウンローダーとコアはバージョンを共にするということになったので、以下のように`-V, --version`で「VOICEVOX COREのバージョン」を出力できるようにする。
```console
❯ download -V
VOICEVOX CORE 0.16.1 downloader
```
Resolves: #1115
> feat(downloader): COREとしてのバージョンを出す`-V, --version`

- crates/downloader/src/main.rs
`size`という変数が`i64`→`usize`→`u64`という形でキャストされていたので、これを`i64`→`u64`にする。ちなみに`i64`は[octocrab](https://docs.rs/crate/octocrab)が返してくるもので、`u64`は[indicatif](https://docs.rs/crate/indicatif)が要求するもの。
最終的な`u64`に影響があるとしたらそれは「ダウンローダーを32-bitでビルドして動かし、4GB超えのアセットを扱う」というケースであるが、その場合32-bitアプリケーションとして4GB超えのファイルを扱えないことには変わりない。よってこのPRは表面的な変化をもたらさないと考えられるため、このPRの題名は"refactor"としてある。
> refactor(downloader): `i64`→`usize`→`u64`の変換から`usize`を抜く

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/downloader/Cargo.toml
- crates/downloader/src/main.rs
docs/guide/user/downloader.mdの「ダウンローダーがダウンロードするもの」と「…する場合」の内容を、"Options:"の下に続く形でhelpに書く。ただし`-h`ではなく`--help`に対してのみ。
これにより、`-h`と`--help`で別々の表示がされるようになる。
<details><summary><code>-h</code>の表示 (従来の形式)</summary>
```console
簡潔な説明を見るには`-h`、詳細な説明を見るには`--help`を使ってください。
Usage: download [OPTIONS]
Options:
--only <TARGET>...
ダウンロード対象を限定する [possible values: c-api, onnxruntime, additional-libraries, models, dict]
--exclude <TARGET>...
ダウンロード対象を除外する [possible values: c-api, onnxruntime, additional-libraries, models, dict]
--min
`--only c-api`のエイリアス
-o, --output <DIRECTORY>
出力先の指定 [default: ./voicevox_core]
--c-api-version <GIT_TAG_OR_LATEST>
ダウンロードするVOICEVOX CORE C APIのバージョンの指定 [default: latest]
--onnxruntime-version <GIT_TAG_OR_LATEST>
ダウンロードするONNX Runtimeのバージョンの指定 [default: latest] …
```
> feat(downloader): downloader.mdの内容を`--help`に追加

- CHANGELOG.md
- crates/downloader/src/main.rs
`c-api`, `onnxruntime`, `additional-libraries`でダウンロードされるzipやtgzに対しては、HTTPステータスもSHA-256もチェックされていなかった。そのためレートリミットに到達したときやGitHubの調子が悪いときは、壊れたzip/tgzを解凍しようとして失敗するという挙動になっていた（はず）。そこで壊れていそうなzip/tgzをダウンロードしてしまったときに明示的なエラーを出すようにする。エラーメッセージの文面を少々適当にしてしまったが、この対応がワークアラウンドである間しかこの文面は存在しないはずなので、あまり深く考えていない。
```console
Error: 予期しない応答をGitHubが返しました: {"message":"API rate limit exceeded for {ip-address}. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"} (Note: レートリミットによるエラーの可能性があります。認証トークンを設定すると制限が緩和されます。詳細は`--help`をご覧ください)
```
また #1118 では`models`もGitHub Releasesからの取得になるため、そのための準備でもある …
> fix(downloader): 壊れたzipとtgzに対しては明示的にエラーにする

- CHANGELOG.md
- crates/downloader/src/main.rs
#1098 で導入されたリトライ機構においてリトライ回数を使いきったとき、最後のエラーのみが表示される仕様だった。これを改め、すべてのエラーを並べて表示するようにする。
```console
Error: 5回のダウンロード試行がすべて失敗しました
Caused by:
- failed to create directory `./voicevox_core/c_api`
Caused by: File exists (os error 17)
- failed to create directory `./voicevox_core/c_api`
Caused by: File exists (os error 17)
- failed to create directory `./voicevox_core/c_api`
Caused by: File exists (os error 17)
- failed to create directory `./voicevox_core/c_api`
Caused by: File exists (os error 17)
- failed to create directory `./voicevox_core/c_api`
Caused by: File exists (os error 17)
```
#1127 のうちエラー表示の部分の解決になる。
> fix(downloader): fixup #1098: エラー表示を改善

- .github/workflows/test.yml
- crates/voicevox_core/Cargo.toml
- crates/voicevox_core/src/__internal/interop.rs
- crates/voicevox_core/src/core/infer.rs
- crates/voicevox_core/src/core/infer/runtimes/onnxruntime.rs
- crates/voicevox_core/src/core/manifest.rs
- crates/voicevox_core/src/core/status.rs
- crates/voicevox_core/src/core/voice_model.rs
- crates/voicevox_core/src/engine/acoustic_feature_extractor.rs
- crates/voicevox_core/src/engine/talk.rs
- crates/voicevox_core/src/engine/talk/full_context_label.rs
- crates/voicevox_core/src/engine/talk/interpret_query.rs
- crates/voicevox_core/src/engine/talk/open_jtalk.rs
- crates/voicevox_core/src/engine/talk/user_dict.rs
- crates/voicevox_core/src/engine/talk/user_dict/dict.rs
- crates/voicevox_core/src/engine/talk/user_dict/word.rs
- crates/voicevox_core/src/error.rs
- crates/voicevox_core/src/lib.rs
- crates/voicevox_core/src/synthesizer.rs
- crates/voicevox_core_macros/Cargo.toml
- crates/voicevox_core_macros/src/extract.rs
- crates/voicevox_core_macros/src/inference_domain.rs
- crates/voicevox_core_macros/src/inference_domains.rs
MSRVを0.16.0のものにすることで #1130 を先延ばしにする。また、MSRVで`cargo check`を行うCIも追加する。
diffの大半はedition違いのRustfmtによるもの。
> feat(rust): MSRVを1.84.0に戻す

- crates/voicevox_core/benches/benches.rs
#1153 で作ったベンチの仕組みにおいて、手元でのベンチ実行時にはイテレーション数を増やすようにしたが、一部(CPUバウンドの軽い処理)において10倍にするつもりが誤って100倍にしてしまっていた。
> test: fixup #1153: 手元実行でのイテレーション数が一部多すぎた

- .github/workflows/benchmarks.yml
CodSpeedHQ/codspeed-rust#122 が入ったcargo-codspeed v4がリリースされてCIが落ちたので、v4の方式に適応する。
> ci: cargo-codspeed v4に適応する
